import { StyleSheet } from 'react-native';
import { colors, radius, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    topbar: {
        paddingHorizontal: 20,
        paddingTop: 12,
        paddingBottom: 10,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    avatarWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
    },
    avatar: {
        width: 42,
        height: 42,
        borderRadius: 21,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 4,
    },
    avatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: 14,
    },
    avatarName: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text,
    },
    topbarIcons: { flexDirection: 'row', gap: 8 },
    notifDot: {
        position: 'absolute',
        top: 7,
        right: 7,
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: colors.cDanger,
        borderWidth: 1.5,
        borderColor: colors.card,
    },

    /* ── HERO BANNER ── */
    hero: {
        marginHorizontal: 16,
        marginTop: 4,
        marginBottom: 20,
        borderRadius: 20,
        overflow: 'hidden',
    },
    heroGradient: {
        padding: 20,
        position: 'relative',
    },
    heroDeco: {
        position: 'absolute',
        right: 16,
        top: 16,
        opacity: 0.12,
    },
    heroGreeting: {
        fontFamily: typography.font.medium,
        fontSize: 12,
        color: 'rgba(255,255,255,0.65)',
        marginBottom: 6,
    },
    heroTitle: {
        fontFamily: typography.font.black,
        fontSize: 26,
        lineHeight: 33,
        color: '#fff',
        letterSpacing: -0.3,
        marginBottom: 16,
    },
    heroTitleHighlight: {
        color: '#A5F3FC',
    },
    modeToggle: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderRadius: 50,
        padding: 3,
    },
    modeBtn: {
        flex: 1,
        borderRadius: 50,
        alignItems: 'center',
        paddingVertical: 6,
    },
    modeBtnActive: {
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.14,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    modeTxt: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: 'rgba(255,255,255,0.6)',
    },
    modeTxtActive: {
        color: colors.primary,
    },

    /* ── SECTIONS ── */
    section: {
        paddingHorizontal: 16,
        marginBottom: 8,
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    sectionTitle: {
        fontFamily: typography.font.bold,
        fontSize: 15,
        color: colors.text,
    },
    seeAll: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.primary,
    },

    /* ── STAT GRID ── */
    statGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: 10,
        marginBottom: 24,
    },
    statCard: {
        width: '48%',
        backgroundColor: colors.card,
        borderRadius: radius.md,
        padding: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...shadows.card,
    },
    statTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 10,
    },
    statIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    statBadge: {
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 20,
    },
    statBadgeText: { fontFamily: typography.font.bold, fontSize: 10 },
    statValue: {
        fontFamily: typography.font.black,
        fontSize: 26,
        color: colors.text,
        lineHeight: 28,
    },
    statLabel: {
        fontFamily: typography.font.medium,
        fontSize: 11,
        color: colors.text2,
        marginTop: 4,
    },
    statSub: {
        fontFamily: typography.font.regular,
        fontSize: 10,
        color: colors.text3,
        marginTop: 2,
    },
    progWrap: { marginTop: 8 },
    progTrack: {
        height: 4,
        borderRadius: 4,
        overflow: 'hidden',
        backgroundColor: colors.border,
    },
    progFill: {
        height: '100%',
        borderRadius: 4,
    },

    /* ── FAMILY ── */
    familyScroll: {
        paddingHorizontal: 16,
        paddingBottom: 24,
        paddingTop: 4,
        gap: 10,
    },
    famCard: {
        width: 76,
        borderRadius: 14,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        paddingVertical: 14,
        paddingHorizontal: 10,
        ...shadows.card,
    },
    famCardActive: {
        borderColor: colors.cFamily,
        shadowColor: '#8B5CF6',
        shadowOpacity: 0.14,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    famAvatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    famAvatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: 12,
    },
    famName: {
        marginTop: 5,
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text,
    },
    famRole: {
        fontFamily: typography.font.regular,
        fontSize: 10,
        color: colors.text3,
    },
    famStatus: { width: 7, height: 7, borderRadius: 4, marginTop: 1 },
    addFam: {
        width: 64,
        borderRadius: 14,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 14,
        gap: 6,
    },
    addFamLabel: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
    },

    /* ── SCHEDULE ── */
    schedCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: radius.sm,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: 12,
        paddingHorizontal: 14,
        marginBottom: 8,
        overflow: 'hidden',
        ...shadows.card,
    },
    schedLeftStrip: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: 3,
        borderTopLeftRadius: 3,
        borderBottomLeftRadius: 3,
    },
    schedAvatar: {
        width: 34,
        height: 34,
        borderRadius: 17,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    schedAvatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: 11,
    },
    schedInfo: { flex: 1, minWidth: 0 },
    schedTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text,
    },
    schedMeta: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text2,
        marginTop: 2,
    },
    schedTime: { alignItems: 'flex-end', flexShrink: 0 },
    schedTimeVal: { fontFamily: typography.font.bold, fontSize: 12 },
    schedTimeDay: {
        fontFamily: typography.font.regular,
        fontSize: 10,
        color: colors.text3,
        marginTop: 2,
    },
    schedCardHover: {
        borderColor: colors.primaryLight,
        shadowColor: '#0f172a',
        shadowOpacity: 0.1,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
        transform: [{ translateY: -1 }],
    },

    /* ── MEDICINE ── */
    medCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: radius.sm,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: 12,
        paddingHorizontal: 14,
        marginBottom: 8,
        ...shadows.card,
    },
    medCardHover: {
        borderColor: colors.cReminder,
        shadowColor: '#F59E0B',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
        transform: [{ translateY: -1 }],
    },
    medCardNotTaken: {
        borderColor: colors.cReminder,
        backgroundColor: '#FFFDF5',
    },
    medCardSelected: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
        shadowColor: '#2563EB',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 4 },
        elevation: 4,
    },
    medIcon: {
        width: 36,
        height: 36,
        borderRadius: 10,
        marginRight: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    medInfo: { flex: 1 },
    medName: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text,
    },
    medDose: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text2,
        marginTop: 2,
    },
    medTimeTag: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.cReminder,
        backgroundColor: colors.cReminderBg,
        paddingHorizontal: 9,
        paddingVertical: 3,
        borderRadius: 20,
        marginRight: 8,
        overflow: 'hidden',
    },
    toggle: {
        width: 36,
        height: 20,
        borderRadius: 10,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        paddingHorizontal: 3,
    },
    toggleOff: {
        backgroundColor: colors.border,
    },
    toggleKnob: {
        width: 14,
        height: 14,
        borderRadius: 7,
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: 1 },
        elevation: 2,
    },
    toggleKnobOn: {
        alignSelf: 'flex-end',
    },
    toggleKnobOff: {
        alignSelf: 'flex-start',
    },

    /* ── CHATBOT ── */
    chatbotWrap: {
        marginHorizontal: 16,
        marginTop: 24,
        borderRadius: 20,
        overflow: 'hidden',
        shadowColor: '#2563EB',
        shadowOpacity: 0.22,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
    },
    chatbotGradient: {
        padding: 18,
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    chatbotIcon: {
        width: 46,
        height: 46,
        borderRadius: 14,
        backgroundColor: 'rgba(255,255,255,0.18)',
        marginRight: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatbotTitle: {
        fontFamily: typography.font.bold,
        fontSize: 14,
        color: '#fff',
        marginBottom: 3,
    },
    chatbotDesc: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: 'rgba(255,255,255,0.72)',
        lineHeight: 18,
    },

    /* ── ARTICLES ── */
    articlesScroll: {
        paddingHorizontal: 16,
        paddingVertical: 4,
        marginBottom: 8,
    },
    articleCard: {
        width: 168,
        borderRadius: radius.md,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        marginRight: 10,
        overflow: 'hidden',
        ...shadows.card,
    },
    articleImg: { height: 100, width: '100%' },
    articleBody: { paddingHorizontal: 12, paddingVertical: 10 },
    articleTag: {
        fontFamily: typography.font.bold,
        fontSize: 9,
        marginBottom: 5,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 20,
        overflow: 'hidden',
        alignSelf: 'flex-start',
    },
    articleTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.text,
        lineHeight: 17,
    },

    /* ── FAMILY PICKER SHEET ── */
    sheetBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    sheetContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        paddingBottom: 36,
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 40,
        shadowOffset: { width: 0, height: -8 },
        elevation: 12,
    },
    sheetHandle: {
        width: 36,
        height: 4,
        borderRadius: 4,
        backgroundColor: '#E4EAF2',
        alignSelf: 'center',
        marginTop: 12,
        marginBottom: 16,
    },
    sheetHeader: {
        paddingHorizontal: 20,
        paddingBottom: 14,
        borderBottomWidth: 1.5,
        borderBottomColor: '#E4EAF2',
    },
    sheetTitle: {
        fontFamily: typography.font.black,
        fontSize: 17,
        color: '#0C1A2E',
    },
    sheetSubtitle: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: '#9BABB8',
        marginTop: 3,
    },
    fpRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        paddingVertical: 14,
        paddingHorizontal: 20,
    },
    fpRowActive: {
        backgroundColor: colors.primaryBg,
    },
    fpIcon: {
        width: 46,
        height: 46,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fpName: {
        fontFamily: typography.font.bold,
        fontSize: 15,
        color: '#0C1A2E',
    },
    fpMeta: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: '#9BABB8',
        marginTop: 2,
    },
    fpCheck: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
});
