import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { colors, radius, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    topbar: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(10),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    avatarWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
    },
    avatar: {
        width: moderateScale(42),
        height: moderateScale(42),
        borderRadius: moderateScale(21),
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOpacity: 0.3,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 4,
    },
    avatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
    },
    avatarName: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    topbarIcons: { flexDirection: 'row', gap: scale(8) },
    notifDot: {
        position: 'absolute',
        top: verticalScale(7),
        right: scale(7),
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
        backgroundColor: colors.cDanger,
        borderWidth: 1.5,
        borderColor: colors.card,
    },

    /* ── HERO BANNER ── */
    hero: {
        marginHorizontal: scale(16),
        marginTop: verticalScale(4),
        marginBottom: verticalScale(20),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
    },
    heroGradient: {
        padding: scale(20),
        position: 'relative',
        backgroundColor: colors.primary,
    },
    heroGlowLg: {
        position: 'absolute',
        right: -scale(28),
        top: -verticalScale(28),
        width: moderateScale(148),
        height: moderateScale(148),
        borderRadius: moderateScale(74),
        backgroundColor: 'rgba(45, 212, 191, 0.28)',
    },
    heroGlowSm: {
        position: 'absolute',
        right: scale(72),
        bottom: -verticalScale(44),
        width: moderateScale(124),
        height: moderateScale(124),
        borderRadius: moderateScale(62),
        backgroundColor: 'rgba(14, 165, 233, 0.18)',
    },
    heroDeco: {
        position: 'absolute',
        right: scale(16),
        top: verticalScale(16),
        opacity: 0.12,
    },
    heroGreeting: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: 'rgba(255,255,255,0.65)',
        marginBottom: verticalScale(6),
    },
    heroTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        lineHeight: verticalScale(33),
        color: '#fff',
        letterSpacing: -0.3,
        marginBottom: verticalScale(16),
    },
    heroTitleHighlight: {
        color: '#A5F3FC',
    },
    modeToggle: {
        flexDirection: 'row',
        backgroundColor: 'rgba(255,255,255,0.12)',
        borderRadius: moderateScale(50),
        padding: moderateScale(3),
    },
    modeBtn: {
        flex: 1,
        borderRadius: moderateScale(50),
        alignItems: 'center',
        paddingVertical: verticalScale(6),
    },
    modeBtnActive: {
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.14,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    modeTxt: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: 'rgba(255,255,255,0.6)',
    },
    modeTxtActive: {
        color: colors.primary,
    },

    /* ── SECTIONS ── */
    section: {
        paddingHorizontal: scale(16),
        marginBottom: verticalScale(8),
    },
    sectionHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(12),
    },
    sectionTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(15),
        color: colors.text,
    },
    seeAll: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },

    /* ── STAT GRID ── */
    statGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        rowGap: verticalScale(10),
        marginBottom: verticalScale(24),
    },
    statCard: {
        width: '48%',
        backgroundColor: colors.card,
        borderRadius: radius.md,
        padding: scale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        ...shadows.card,
    },
    statTop: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    statIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
    },
    statBadge: {
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
    },
    statBadgeText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
    },
    statValue: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        color: colors.text,
        lineHeight: verticalScale(28),
    },
    statLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(4),
    },
    statSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    progWrap: { marginTop: verticalScale(8) },
    progTrack: {
        height: verticalScale(4),
        borderRadius: moderateScale(4),
        overflow: 'hidden',
        backgroundColor: colors.border,
    },
    progFill: {
        height: '100%',
        borderRadius: moderateScale(4),
    },

    /* ── FAMILY ── */
    familyScroll: {
        paddingHorizontal: scale(16),
        paddingBottom: verticalScale(24),
        paddingTop: verticalScale(4),
        gap: scale(10),
    },
    famCard: {
        width: scale(76),
        borderRadius: moderateScale(14),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(10),
        ...shadows.card,
    },
    famCardActive: {
        borderColor: colors.cFamily,
        shadowColor: '#8B5CF6',
        shadowOpacity: 0.14,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
    },
    famAvatar: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(20),
        alignItems: 'center',
        justifyContent: 'center',
    },
    famAvatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
    },
    famName: {
        marginTop: verticalScale(5),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text,
    },
    famRole: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
    },
    famStatus: {
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
        marginTop: verticalScale(1),
    },
    addFam: {
        width: scale(64),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(14),
        gap: scale(6),
    },
    addFamLabel: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },

    /* ── SCHEDULE ── */
    schedCard: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: radius.sm,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(14),
        marginBottom: verticalScale(8),
        overflow: 'hidden',
        ...shadows.card,
    },
    schedLeftStrip: {
        position: 'absolute',
        left: 0,
        top: 0,
        bottom: 0,
        width: scale(3),
        borderTopLeftRadius: moderateScale(3),
        borderBottomLeftRadius: moderateScale(3),
    },
    schedAvatar: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    schedAvatarText: {
        color: '#fff',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
    },
    schedInfo: { flex: 1, minWidth: 0 },
    schedTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    schedMeta: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(2),
    },
    schedTime: { alignItems: 'flex-end', flexShrink: 0 },
    schedTimeVal: { fontFamily: typography.font.bold, fontSize: scaleFont(12) },
    schedTimeDay: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    schedCardHover: {
        borderColor: colors.primaryLight,
        shadowColor: '#0f172a',
        shadowOpacity: 0.1,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
        transform: [{ translateY: verticalScale(-1) }],
    },

    /* ── MEDICINE ── */
    medCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: radius.sm,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(14),
        marginBottom: verticalScale(8),
        ...shadows.card,
    },
    medCardHover: {
        borderColor: colors.cReminder,
        shadowColor: '#F59E0B',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
        transform: [{ translateY: verticalScale(-1) }],
    },
    medCardNotTaken: {
        borderColor: colors.cReminder,
        backgroundColor: '#FFFDF5',
    },
    medCardSelected: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
        shadowColor: '#2563EB',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 4,
    },
    medIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(10),
        marginRight: scale(12),
        alignItems: 'center',
        justifyContent: 'center',
    },
    medInfo: { flex: 1 },
    medName: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    medDose: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(2),
    },
    medTimeTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.cReminder,
        backgroundColor: colors.cReminderBg,
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        marginRight: scale(8),
        overflow: 'hidden',
    },
    toggle: {
        width: scale(36),
        height: verticalScale(20),
        borderRadius: moderateScale(10),
        backgroundColor: colors.primary,
        justifyContent: 'center',
        paddingHorizontal: scale(3),
    },
    toggleOff: {
        backgroundColor: colors.border,
    },
    toggleKnob: {
        width: moderateScale(14),
        height: moderateScale(14),
        borderRadius: moderateScale(7),
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.15,
        shadowRadius: 3,
        shadowOffset: { width: 0, height: verticalScale(1) },
        elevation: 2,
    },
    toggleKnobOn: {
        alignSelf: 'flex-end',
    },
    toggleKnobOff: {
        alignSelf: 'flex-start',
    },

    /* ── CHATBOT ── */
    chatbotWrap: {
        marginHorizontal: scale(16),
        marginTop: verticalScale(24),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        shadowColor: '#2563EB',
        shadowOpacity: 0.22,
        shadowRadius: 24,
        shadowOffset: { width: 0, height: verticalScale(6) },
        elevation: 6,
    },
    chatbotGradient: {
        padding: scale(18),
        flexDirection: 'row',
        alignItems: 'center',
        position: 'relative',
        overflow: 'hidden',
    },
    chatbotIcon: {
        width: moderateScale(46),
        height: moderateScale(46),
        borderRadius: moderateScale(14),
        backgroundColor: 'rgba(255,255,255,0.18)',
        marginRight: scale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    chatbotTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: '#fff',
        marginBottom: verticalScale(3),
    },
    chatbotDesc: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: 'rgba(255,255,255,0.72)',
        lineHeight: verticalScale(18),
    },

    /* ── ARTICLES ── */
    articlesScroll: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(4),
        marginBottom: verticalScale(8),
    },
    articleCard: {
        width: scale(168),
        borderRadius: radius.md,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        marginRight: scale(10),
        overflow: 'hidden',
        ...shadows.card,
    },
    articleImg: { height: verticalScale(100), width: '100%' },
    articleBody: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
    },
    articleTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(9),
        marginBottom: verticalScale(5),
        textTransform: 'uppercase',
        letterSpacing: 0.8,
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        alignSelf: 'flex-start',
    },
    articleTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text,
        lineHeight: verticalScale(17),
    },

    /* ── FAMILY PICKER SHEET ── */
    sheetBackdrop: {
        ...StyleSheet.absoluteFillObject,
        backgroundColor: 'rgba(0,0,0,0.45)',
    },
    sheetContainer: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#fff',
        borderTopLeftRadius: moderateScale(28),
        borderTopRightRadius: moderateScale(28),
        paddingBottom: verticalScale(36),
        shadowColor: '#000',
        shadowOpacity: 0.18,
        shadowRadius: 40,
        shadowOffset: { width: 0, height: verticalScale(-8) },
        elevation: 12,
    },
    sheetHandle: {
        width: scale(36),
        height: verticalScale(4),
        borderRadius: moderateScale(4),
        backgroundColor: '#E4EAF2',
        alignSelf: 'center',
        marginTop: verticalScale(12),
        marginBottom: verticalScale(16),
    },
    sheetHeader: {
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1.5,
        borderBottomColor: '#E4EAF2',
    },
    sheetTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: '#0C1A2E',
    },
    sheetSubtitle: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: '#9BABB8',
        marginTop: verticalScale(3),
    },
    fpRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
        paddingVertical: verticalScale(14),
        paddingHorizontal: scale(20),
    },
    fpRowActive: {
        backgroundColor: colors.primaryBg,
    },
    fpIcon: {
        width: moderateScale(46),
        height: moderateScale(46),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    fpName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(15),
        color: '#0C1A2E',
    },
    fpMeta: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: '#9BABB8',
        marginTop: verticalScale(2),
    },
    fpCheck: {
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
});
