import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { buttonSystem, formSystem, inputSystem } from '../../styles/shared';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    /* ── PROGRESS DOTS ── */
    dotsWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: scale(6),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(6),
    },
    dot: {
        width: scale(8),
        height: verticalScale(4),
        borderRadius: moderateScale(4),
        backgroundColor: colors.border,
    },
    dotActive: {
        width: scale(28),
        backgroundColor: colors.primary,
    },
    dotDone: {
        width: scale(8),
        backgroundColor: colors.primaryLight,
    },
    /* ── SHARED SCROLL & FIXED BOTTOM ── */
    sScroll: {
        paddingHorizontal: scale(24),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(120),
        flexGrow: 1,
    },
    sBtn: {
        paddingHorizontal: scale(24),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(28),
        backgroundColor: colors.bg,
    },
    onboardPrimaryBtn: {
        width: '100%',
        ...buttonSystem.primary,
        backgroundColor: colors.primary,
        minHeight: verticalScale(45),
        borderRadius: moderateScale(11),
        overflow: 'hidden',
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 5,
    },
    onboardPrimaryBtnText: {
        ...buttonSystem.textPrimary,
        fontSize: scaleFont(13.5),
        letterSpacing: 0.1,
        backgroundColor: 'transparent',
        includeFontPadding: false,
    },
    onboardPrimaryBtnContent: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
    },
    onboardOutlineBtn: {
        width: '100%',
        minHeight: verticalScale(45),
        borderRadius: moderateScale(11),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(10),
    },
    onboardOutlineBtnText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12.5),
        color: colors.text,
    },
    /* ── S1 WELCOME ── */
    s1Content: {
        flex: 1,
        justifyContent: 'center',
    },
    s1Hero: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(24),
    },
    heroCircle1: {
        position: 'absolute',
        width: moderateScale(280),
        height: moderateScale(280),
        borderRadius: moderateScale(140),
        backgroundColor: 'rgba(37,99,235,0.06)',
        top: verticalScale(-40),
        right: scale(-40),
    },
    heroCircle2: {
        position: 'absolute',
        width: moderateScale(180),
        height: moderateScale(180),
        borderRadius: moderateScale(90),
        backgroundColor: 'rgba(20,184,166,0.07)',
        bottom: verticalScale(-20),
        left: scale(-30),
    },
    illusWrap: {
        width: moderateScale(260),
        height: moderateScale(260),
        alignItems: 'center',
        justifyContent: 'center',
    },
    illusRing: {
        position: 'absolute',
        width: moderateScale(240),
        height: moderateScale(240),
        borderRadius: moderateScale(120),
        borderWidth: 2,
        borderColor: 'rgba(37,99,235,0.15)',
        borderStyle: 'dashed',
    },
    illusRing2: {
        position: 'absolute',
        width: moderateScale(188),
        height: moderateScale(188),
        borderRadius: moderateScale(94),
        borderWidth: 2,
        borderColor: 'rgba(20,184,166,0.15)',
        borderStyle: 'dashed',
    },
    illusCenter: {
        width: moderateScale(110),
        height: moderateScale(110),
        borderRadius: moderateScale(55),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.secondary,
        shadowColor: colors.secondary,
        shadowOpacity: 0.35,
        shadowRadius: 28,
        shadowOffset: { width: 0, height: verticalScale(14) },
        elevation: 10,
    },
    chip: {
        position: 'absolute',
        borderRadius: moderateScale(12),
        paddingVertical: verticalScale(7),
        paddingHorizontal: scale(11),
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(7),
        shadowColor: colors.text,
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 6,
    },
    chip1: { top: verticalScale(12), left: scale(-8) },
    chip2: { top: verticalScale(12), right: scale(-16) },
    chip3: { bottom: verticalScale(16), left: scale(-10) },
    chip4: { bottom: verticalScale(16), right: scale(-8) },
    chipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text,
    },
    chipSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(9),
        color: colors.text2,
        marginTop: verticalScale(1),
    },
    s1BodyText: {
        paddingHorizontal: scale(24),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(4),
    },
    s1Title: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(28),
        color: colors.text,
        lineHeight: verticalScale(36),
        marginBottom: verticalScale(8),
        letterSpacing: -0.3,
    },
    s1Desc: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(14),
        color: colors.text2,
        lineHeight: verticalScale(22),
        marginBottom: verticalScale(4),
    },
    /* ── S2 FEATURES ── */
    s2Title: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        color: colors.text,
        lineHeight: verticalScale(33),
        marginBottom: verticalScale(6),
        letterSpacing: -0.3,
    },
    s2Desc: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(14),
        color: colors.text2,
        lineHeight: verticalScale(22),
        marginBottom: verticalScale(16),
    },
    featList: {
        gap: verticalScale(10),
        marginBottom: verticalScale(16),
    },
    featCard: {
        borderRadius: moderateScale(16),
        padding: scale(14),
        paddingHorizontal: scale(16),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    featIcon: {
        width: moderateScale(44),
        height: moderateScale(44),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(14),
    },
    featName: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
        marginBottom: verticalScale(2),
    },
    featDesc: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text2,
        lineHeight: verticalScale(17),
    },
    featArrow: {
        fontSize: scaleFont(18),
        color: colors.text3,
        marginLeft: scale(8),
    },
    proofBanner: {
        backgroundColor: colors.primaryBg,
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(16),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    proofTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    proofSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(1),
    },
    /* ── S3 PERMISSION ── */
    s3Illo: {
        borderRadius: moderateScale(20),
        paddingVertical: verticalScale(20),
        paddingHorizontal: scale(20),
        backgroundColor: colors.warningBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(12),
    },
    s3PulseRing1: {
        position: 'absolute',
        width: moderateScale(80),
        height: moderateScale(80),
        borderRadius: moderateScale(40),
        borderWidth: 2,
        borderColor: 'rgba(245,158,11,0.15)',
        top: verticalScale(20),
        left: scale(20),
    },
    s3PulseRing2: {
        position: 'absolute',
        width: moderateScale(110),
        height: moderateScale(110),
        borderRadius: moderateScale(55),
        borderWidth: 2,
        borderColor: 'rgba(245,158,11,0.08)',
        top: verticalScale(5),
        left: scale(5),
    },
    s3BellArea: {
        width: moderateScale(120),
        height: moderateScale(120),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(4),
    },
    bellWrap: {
        marginBottom: 0,
    },
    s3IlloTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: '#D97706',
    },
    s3Desc: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(14),
        color: colors.text2,
        lineHeight: verticalScale(22),
        marginBottom: verticalScale(14),
    },
    permList: {
        gap: verticalScale(8),
        marginBottom: verticalScale(8),
    },
    permRow: {
        borderRadius: moderateScale(14),
        padding: scale(12),
        paddingHorizontal: scale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    permIcon: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    permTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    permDetail: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(1),
    },
    permCheck: {
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnSkip: {
        marginTop: verticalScale(6),
        paddingVertical: verticalScale(10),
        alignItems: 'center',
    },
    btnSkipText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    /* ── S4 AUTH ── */
    s4Top: {
        alignItems: 'center',
        paddingTop: verticalScale(42),
        paddingBottom: verticalScale(16),
    },
    s4Logo: {
        width: moderateScale(56),
        height: moderateScale(56),
        borderRadius: moderateScale(16),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(10),
        backgroundColor: colors.secondary,
        shadowColor: colors.secondary,
        shadowOpacity: 0.28,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: verticalScale(8) },
        elevation: 6,
    },
    s4App: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        letterSpacing: 2,
        textTransform: 'uppercase',
        color: colors.primary,
        marginBottom: verticalScale(6),
    },
    s4Title: {
        textAlign: 'center',
        fontFamily: typography.font.black,
        fontSize: scaleFont(22),
        color: colors.text,
        lineHeight: verticalScale(28),
        letterSpacing: -0.2,
    },
    s4Sub: {
        textAlign: 'center',
        marginTop: verticalScale(5),
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text2,
        lineHeight: verticalScale(20),
    },
    authTabs: {
        flexDirection: 'row',
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        padding: scale(3),
        marginBottom: verticalScale(16),
    },
    authTab: {
        flex: 1,
        borderRadius: moderateScale(9),
        alignItems: 'center',
        paddingVertical: verticalScale(9),
    },
    authTabActive: {
        backgroundColor: colors.card,
        ...shadows.card,
    },
    authTabText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text2,
    },
    authTabActiveText: {
        color: colors.primary,
    },
    inputGroup: {
        marginBottom: verticalScale(12),
    },
    inputLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(5),
    },
    inputWrap: {
        ...inputSystem.fieldSoft,
    },
    textInput: {
        ...inputSystem.text,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
    },
    forgot: {
        alignSelf: 'flex-end',
        marginBottom: verticalScale(4),
    },
    forgotText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.primary,
    },
    orRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        marginVertical: verticalScale(10),
    },
    orLine: {
        flex: 1,
        height: 1,
        backgroundColor: colors.border,
    },
    orText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    socialRow: {
        flexDirection: 'row',
        gap: scale(10),
    },
    btnGoogle: {
        flex: 1,
        borderRadius: moderateScale(12),
        paddingVertical: verticalScale(13),
        borderWidth: 1,
        borderColor: '#DADCE0',
        backgroundColor: '#FFFFFF',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(10),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.08,
        shadowRadius: 3,
        elevation: 2,
    },
    googleLogo: {
        width: scale(20),
        height: scale(20),
    },
    btnSocialLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    btnApple: {
        flex: 1,
        borderRadius: moderateScale(12),
        paddingVertical: verticalScale(12),
        borderWidth: 1.5,
        borderColor: colors.text,
        backgroundColor: colors.text,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
    },
    btnAppleText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: '#fff',
    },
    trustRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(16),
        marginTop: verticalScale(10),
    },
    trustItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
    },
    trustText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    termsText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        textAlign: 'center',
        marginTop: verticalScale(10),
        lineHeight: verticalScale(18),
    },
    termsLink: {
        fontFamily: typography.font.medium,
        color: colors.primary,
    },
});
