import { StyleSheet } from 'react-native';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    page: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    /* ── PROGRESS DOTS ── */
    dotsWrap: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        gap: 6,
        paddingTop: 14,
        paddingBottom: 6,
    },
    dot: {
        width: 8,
        height: 4,
        borderRadius: 4,
        backgroundColor: colors.border,
    },
    dotActive: {
        width: 28,
        backgroundColor: colors.primary,
    },
    dotDone: {
        width: 8,
        backgroundColor: colors.primaryLight,
    },
    /* ── SHARED SCROLL & FIXED BOTTOM ── */
    sScroll: {
        paddingHorizontal: 24,
        paddingTop: 16,
        paddingBottom: 12,
        flexGrow: 1,
    },
    sBtn: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 28,
        backgroundColor: colors.bg,
    },
    /* ── S1 WELCOME ── */
    s1Content: {
        flex: 1,
        justifyContent: 'center',
    },
    s1Hero: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 24,
    },
    heroCircle1: {
        position: 'absolute',
        width: 280,
        height: 280,
        borderRadius: 140,
        backgroundColor: 'rgba(37,99,235,0.06)',
        top: -40,
        right: -40,
    },
    heroCircle2: {
        position: 'absolute',
        width: 180,
        height: 180,
        borderRadius: 90,
        backgroundColor: 'rgba(20,184,166,0.07)',
        bottom: -20,
        left: -30,
    },
    illusWrap: {
        width: 260,
        height: 260,
        alignItems: 'center',
        justifyContent: 'center',
    },
    illusRing: {
        position: 'absolute',
        width: 240,
        height: 240,
        borderRadius: 120,
        borderWidth: 2,
        borderColor: 'rgba(37,99,235,0.15)',
        borderStyle: 'dashed',
    },
    illusRing2: {
        position: 'absolute',
        width: 188,
        height: 188,
        borderRadius: 94,
        borderWidth: 2,
        borderColor: 'rgba(20,184,166,0.15)',
        borderStyle: 'dashed',
    },
    illusCenter: {
        width: 110,
        height: 110,
        borderRadius: 55,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        shadowColor: colors.primary,
        shadowOpacity: 0.35,
        shadowRadius: 28,
        shadowOffset: { width: 0, height: 14 },
        elevation: 10,
    },
    chip: {
        position: 'absolute',
        borderRadius: 12,
        paddingVertical: 7,
        paddingHorizontal: 11,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 7,
        shadowColor: colors.text,
        shadowOpacity: 0.1,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 4 },
        elevation: 6,
    },
    chip1: { top: 12, left: -8 },
    chip2: { top: 12, right: -16 },
    chip3: { bottom: 16, left: -10 },
    chip4: { bottom: 16, right: -8 },
    chipText: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text,
    },
    chipSub: {
        fontFamily: typography.font.regular,
        fontSize: 9,
        color: colors.text2,
        marginTop: 1,
    },
    s1BodyText: {
        paddingHorizontal: 24,
        paddingTop: 8,
        paddingBottom: 4,
    },
    s1Title: {
        fontFamily: typography.font.black,
        fontSize: 28,
        color: colors.text,
        lineHeight: 36,
        marginBottom: 8,
        letterSpacing: -0.3,
    },
    s1Desc: {
        fontFamily: typography.font.regular,
        fontSize: 14,
        color: colors.text2,
        lineHeight: 22,
        marginBottom: 4,
    },
    /* ── S2 FEATURES ── */
    s2Title: {
        fontFamily: typography.font.black,
        fontSize: 26,
        color: colors.text,
        lineHeight: 33,
        marginBottom: 6,
        letterSpacing: -0.3,
    },
    s2Desc: {
        fontFamily: typography.font.regular,
        fontSize: 14,
        color: colors.text2,
        lineHeight: 22,
        marginBottom: 16,
    },
    featList: {
        gap: 10,
        marginBottom: 16,
    },
    featCard: {
        borderRadius: 16,
        padding: 14,
        paddingHorizontal: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    featIcon: {
        width: 44,
        height: 44,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    featName: {
        fontFamily: typography.font.semiBold,
        fontSize: 14,
        color: colors.text,
        marginBottom: 2,
    },
    featDesc: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text2,
        lineHeight: 17,
    },
    featArrow: { fontSize: 18, color: colors.text3, marginLeft: 8 },
    proofBanner: {
        backgroundColor: colors.primaryBg,
        borderRadius: 14,
        paddingVertical: 12,
        paddingHorizontal: 16,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    proofTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text,
    },
    proofSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text2,
        marginTop: 1,
    },
    /* ── S3 PERMISSION ── */
    s3Illo: {
        borderRadius: 20,
        paddingVertical: 28,
        paddingHorizontal: 24,
        backgroundColor: colors.cReminderBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 18,
    },
    s3PulseRing1: {
        position: 'absolute',
        width: 100,
        height: 100,
        borderRadius: 50,
        borderWidth: 2,
        borderColor: 'rgba(245,158,11,0.15)',
        top: 25,
        left: 25,
    },
    s3PulseRing2: {
        position: 'absolute',
        width: 140,
        height: 140,
        borderRadius: 70,
        borderWidth: 2,
        borderColor: 'rgba(245,158,11,0.08)',
        top: 5,
        left: 5,
    },
    s3BellArea: {
        width: 150,
        height: 150,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 8,
    },
    bellWrap: {
        marginBottom: 0,
    },
    s3IlloTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: '#D97706',
    },
    s3Desc: {
        fontFamily: typography.font.regular,
        fontSize: 14,
        color: colors.text2,
        lineHeight: 22,
        marginBottom: 14,
    },
    permList: {
        gap: 8,
        marginBottom: 8,
    },
    permRow: {
        borderRadius: 14,
        padding: 12,
        paddingHorizontal: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    permIcon: {
        width: 38,
        height: 38,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    permTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text,
    },
    permDetail: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text2,
        marginTop: 1,
    },
    permCheck: {
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    btnSkip: {
        marginTop: 6,
        paddingVertical: 10,
        alignItems: 'center',
    },
    btnSkipText: {
        fontFamily: typography.font.regular,
        fontSize: 13,
        color: colors.text3,
    },
    /* ── S4 AUTH ── */
    s4Top: {
        alignItems: 'center',
        paddingTop: 4,
        paddingBottom: 16,
    },
    s4Logo: {
        width: 56,
        height: 56,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 10,
        backgroundColor: colors.primary,
        shadowColor: colors.primary,
        shadowOpacity: 0.28,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 8 },
        elevation: 6,
    },
    s4App: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        letterSpacing: 2,
        textTransform: 'uppercase',
        color: colors.primary,
        marginBottom: 6,
    },
    s4Title: {
        textAlign: 'center',
        fontFamily: typography.font.black,
        fontSize: 22,
        color: colors.text,
        lineHeight: 28,
        letterSpacing: -0.2,
    },
    s4Sub: {
        textAlign: 'center',
        marginTop: 5,
        fontFamily: typography.font.regular,
        fontSize: 13,
        color: colors.text2,
        lineHeight: 20,
    },
    authTabs: {
        flexDirection: 'row',
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        padding: 3,
        marginBottom: 16,
    },
    authTab: {
        flex: 1,
        borderRadius: 9,
        alignItems: 'center',
        paddingVertical: 9,
    },
    authTabActive: {
        backgroundColor: colors.card,
        ...shadows.card,
    },
    authTabText: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text2,
    },
    authTabActiveText: {
        color: colors.primary,
    },
    inputGroup: {
        marginBottom: 12,
    },
    inputLabel: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: 5,
    },
    inputWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        paddingHorizontal: 14,
        paddingVertical: 12,
    },
    textInput: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: 14,
        color: colors.text,
        padding: 0,
    },
    forgot: {
        alignSelf: 'flex-end',
        marginBottom: 4,
    },
    forgotText: {
        fontFamily: typography.font.medium,
        fontSize: 12,
        color: colors.primary,
    },
    orRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginVertical: 10,
    },
    orLine: {
        flex: 1,
        height: 1,
        backgroundColor: colors.border,
    },
    orText: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text3,
    },
    socialRow: {
        flexDirection: 'row',
        gap: 10,
    },
    btnGoogle: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 12,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    googleG: {
        fontSize: 18,
        fontWeight: '700',
        color: '#4285F4',
    },
    btnSocialLabel: {
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
    },
    btnApple: {
        flex: 1,
        borderRadius: 12,
        paddingVertical: 12,
        borderWidth: 1.5,
        borderColor: colors.text,
        backgroundColor: colors.text,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    btnAppleText: {
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: '#fff',
    },
    trustRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 16,
        marginTop: 10,
    },
    trustItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    trustText: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
    },
    termsText: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        textAlign: 'center',
        marginTop: 10,
        lineHeight: 18,
    },
    termsLink: {
        fontFamily: typography.font.medium,
        color: colors.primary,
    },
});
