import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    statusTopSpacer: { height: verticalScale(4) },
    topbar: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
    },
    topbarRight: {
        flexDirection: 'row',
        gap: scale(8),
    },
    member: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        borderRadius: moderateScale(16),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: verticalScale(11),
        paddingHorizontal: scale(14),
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    mAvatar: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(19),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(11),
    },
    mAvatarText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    mDot: {
        position: 'absolute',
        bottom: verticalScale(1),
        right: scale(1),
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
        backgroundColor: colors.cHealth,
        borderWidth: 2,
        borderColor: colors.card,
    },
    mInfo: { flex: 1 },
    mName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    mRole: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    bmiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    bmiIcon: {
        width: moderateScale(44),
        height: moderateScale(44),
        borderRadius: moderateScale(13),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(14),
    },
    bmiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(4),
    },
    bmiValueRow: { flexDirection: 'row', alignItems: 'flex-end' },
    bmiValue: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(28),
        color: colors.text,
        letterSpacing: -1,
    },
    bmiUnit: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginLeft: scale(5),
    },
    bmiSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    bmiBadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.cHealth,
        backgroundColor: colors.cHealthBg,
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(20),
    },
    bmiGaugeWrap: {
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
    },
    bmiGaugeTrack: {
        height: verticalScale(7),
        borderRadius: moderateScale(8),
        backgroundColor: colors.border,
        justifyContent: 'center',
    },
    bmiGaugeThumb: {
        position: 'absolute',
        left: '52%',
        width: moderateScale(13),
        height: moderateScale(13),
        borderRadius: moderateScale(7),
        backgroundColor: colors.card,
        borderWidth: 2.5,
        borderColor: colors.primary,
    },
    bmiGaugeLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: verticalScale(7),
    },
    bmiGaugeLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
    },

    // ── Health Info Rows ──
    hiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(12),
    },
    hiRowLast: {
        borderBottomWidth: 0,
    },
    hiIcon: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
    },
    hiBody: { flex: 1 },
    hiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(4),
    },
    hiVal: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
    },
    hiTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(5),
    },
    hiTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(8),
    },
    hiEmpty: {
        fontSize: scaleFont(12),
        fontStyle: 'italic',
        color: colors.text3,
    },

    // ── Visit Rows ──
    visitRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    visitIcon: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
        marginTop: verticalScale(1),
    },
    visitBody: { flex: 1 },
    visitTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    visitSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    visitTag: {
        marginTop: verticalScale(5),
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        alignSelf: 'flex-start',
    },
    visitDate: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text2,
        backgroundColor: colors.bgHealth,
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(8),
        overflow: 'hidden',
        marginTop: verticalScale(2),
    },

    // ── Vaccine / Donut ──
    vpctRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    donutWrap: {
        width: moderateScale(60),
        height: moderateScale(60),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(16),
    },
    donutPercent: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: colors.cReminder,
    },
    vpctTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
    },
    vpctSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    vIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    vBody: { flex: 1 },
    vName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    vDate: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
    },

    // ── Tips ──
    tipsRow: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
    },
    tipCard: {
        width: moderateScale(144),
        borderRadius: moderateScale(16),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        padding: scale(14),
        marginRight: scale(10),
        ...shadows.card,
    },
    tipEmoji: { fontSize: scaleFont(22), marginBottom: verticalScale(8) },
    tipTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text,
        marginBottom: verticalScale(3),
    },
    tipSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
        lineHeight: verticalScale(14),
    },

    // ── Bottom Sheet: Blood Type Grid ──
    btGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    btOpt: {
        width: '23%' as unknown as number,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingVertical: verticalScale(12),
        alignItems: 'center',
    },
    btOptSel: {
        borderColor: '#E11D48',
        backgroundColor: colors.cDangerBg,
    },
    btOptText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text2,
    },
    btOptTextSel: {
        color: colors.cDanger,
    },

    // ── Bottom Sheet: Tag Input ──
    tagInputWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: scale(6),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(44),
    },
    tagChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        backgroundColor: colors.cReminderBg,
        paddingVertical: verticalScale(3),
        paddingLeft: scale(10),
        paddingRight: scale(8),
        borderRadius: moderateScale(8),
    },
    tagChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.cReminder,
    },
    tagChipX: {
        fontSize: scaleFont(14),
        color: colors.cReminder,
        opacity: 0.6,
        paddingHorizontal: scale(2),
    },
    tagInput: {
        flex: 1,
        minWidth: scale(100),
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text,
        padding: 0,
    },
    tagHint: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(8),
    },

    // ═══════════════════════════════════
    //  SUB-SCREEN: Shared topbar
    // ═══════════════════════════════════
    subTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        gap: scale(10),
    },
    subBackBtn: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(18),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    subTopbarTitle: {
        flex: 1,
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        letterSpacing: -0.3,
    },
    subAddBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        backgroundColor: colors.primary,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
    },
    subAddBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.card,
    },

    // ═══════════════════════════════════
    //  RECORDS SCREEN
    // ═══════════════════════════════════
    searchFilterWrap: {
        backgroundColor: colors.card,
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    searchWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
    },
    searchInput: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
        padding: 0,
    },
    filterRow: {
        flexDirection: 'row',
        gap: scale(6),
        marginTop: verticalScale(10),
    },
    filterChip: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(4),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    filterChipActive: {
        backgroundColor: colors.primaryBg,
        borderColor: colors.primary,
    },
    filterChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    filterChipTextActive: {
        color: colors.primary,
    },

    // Timeline items
    recYearHdr: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(20),
        paddingBottom: verticalScale(6),
        letterSpacing: -0.3,
    },
    recMonthHdr: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text2,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(8),
    },
    recItem: {
        flexDirection: 'row',
        paddingLeft: scale(20),
        paddingRight: scale(16),
        marginBottom: verticalScale(2),
    },
    recTimeline: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginRight: scale(12),
        width: scale(56),
    },
    recDateCol: {
        alignItems: 'center',
        width: scale(28),
    },
    recDay: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        lineHeight: verticalScale(22),
    },
    recMon: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    recDotCol: {
        alignItems: 'center',
        marginLeft: scale(8),
        paddingTop: verticalScale(6),
    },
    recDot: {
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
    },
    recLine: {
        width: 2,
        flex: 1,
        backgroundColor: colors.border,
        marginTop: verticalScale(4),
        minHeight: verticalScale(60),
    },
    recCard: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        overflow: 'hidden',
        marginBottom: verticalScale(10),
        ...shadows.card,
    },
    recCardTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: scale(14),
        gap: scale(12),
    },
    recIconWrap: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    recTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    recSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    recDiagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(4),
        gap: scale(4),
    },
    recDiagDot: {
        width: moderateScale(6),
        height: moderateScale(6),
        borderRadius: moderateScale(3),
        backgroundColor: colors.text3,
    },
    recDiagText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        flex: 1,
    },
    recCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    recTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        overflow: 'hidden',
    },
    recMetaRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
    },
    recMetaText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10),
        color: colors.text3,
    },
    recEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(64),
        paddingHorizontal: scale(32),
    },
    recEmptyIcon: {
        width: moderateScale(72),
        height: moderateScale(72),
        borderRadius: moderateScale(22),
        backgroundColor: colors.primaryBg,
        borderWidth: 2,
        borderColor: colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(16),
    },
    recEmptyTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
        marginBottom: verticalScale(6),
    },
    recEmptySub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text3,
    },

    // ═══════════════════════════════════
    //  VACCINE SCREEN
    // ═══════════════════════════════════
    vaxHero: {
        borderRadius: 18,
        padding: 16,
        marginBottom: 16,
        overflow: 'hidden',
    },
    vaxHeroContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    vaxDonut: {
        width: 64,
        height: 64,
    },
    vaxDonutTrack: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 5,
        borderColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDonutFill: {
        position: 'absolute',
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 5,
        borderColor: 'transparent',
        transform: [{ rotate: '-90deg' }],
    },
    vaxDonutText: {
        fontFamily: typography.font.black,
        fontSize: 14,
        color: colors.card,
    },
    vaxHeroSup: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 2,
    },
    vaxHeroNum: {
        fontFamily: typography.font.black,
        fontSize: 22,
        color: colors.card,
        lineHeight: 26,
        letterSpacing: -0.5,
    },
    vaxHeroNumSub: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        opacity: 0.7,
    },
    vaxHeroPending: {
        marginTop: 5,
        fontFamily: typography.font.bold,
        fontSize: 9,
        color: 'rgba(255,255,255,0.55)',
        letterSpacing: 0.5,
    },
    vaxProgressTrack: {
        height: 5,
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderRadius: 99,
        overflow: 'hidden',
        marginTop: 12,
    },
    vaxProgressFill: {
        height: '100%',
        backgroundColor: colors.card,
        borderRadius: 99,
    },

    // Section headers
    vaxSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    vaxSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    vaxSecDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    vaxSecLabel: {
        fontFamily: typography.font.black,
        fontSize: 10,
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.7,
    },
    vaxSecCount: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxListCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        overflow: 'hidden',
        marginBottom: verticalScale(14),
    },

    // Vaccine rows
    vaxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(11),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(13),
    },
    vaxRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxRowIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxRowName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vaxRowSub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    vaxRowMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        marginTop: verticalScale(3),
    },
    vaxChip: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxChipDone: {
        backgroundColor: colors.cHealthBg,
        color: colors.cHealth,
        borderColor: '#BBF7D0',
    },
    vaxChipSoon: {
        backgroundColor: colors.cReminderBg,
        color: colors.cReminder,
        borderColor: '#FDE68A',
    },
    vaxChipPending: {
        backgroundColor: colors.cDangerBg,
        color: colors.cDanger,
        borderColor: '#FECDD3',
    },
    vaxChipScheduled: {
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        borderColor: colors.primaryLight,
    },
    vaxChipLabel: {
        fontSize: scaleFont(10),
        color: colors.text3,
        fontWeight: '500',
    },

    // Add button & note
    vaxAddBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        padding: scale(13),
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        borderRadius: moderateScale(14),
    },
    vaxAddBtnText: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.text2,
    },
    vaxNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(8),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(11),
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(12),
        marginTop: verticalScale(12),
    },
    vaxNoteText: {
        flex: 1,
        fontSize: scaleFont(11),
        fontWeight: '500',
        color: colors.primary,
        lineHeight: verticalScale(17),
    },

    // ═══════════════════════════════════
    //  MEDICINE SCREEN
    // ═══════════════════════════════════
    medTodayCard: {
        borderRadius: moderateScale(20),
        padding: scale(16),
        marginBottom: verticalScale(16),
        overflow: 'hidden',
    },
    medTodaySup: {
        fontSize: scaleFont(11),
        fontWeight: '700',
        color: 'rgba(255,255,255,0.7)',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(6),
    },
    medTodayRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        marginBottom: verticalScale(10),
    },
    medTodayNum: {
        fontSize: scaleFont(22),
        fontWeight: '800',
        color: colors.card,
        lineHeight: verticalScale(26),
        letterSpacing: -0.4,
    },
    medTodayNumSub: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        opacity: 0.7,
    },
    medTodayPct: {
        fontSize: scaleFont(20),
        fontWeight: '800',
        color: 'rgba(255,255,255,0.85)',
    },
    medProgressTrack: {
        height: verticalScale(7),
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderRadius: 99,
        overflow: 'hidden',
    },
    medProgressFill: {
        height: '100%',
        backgroundColor: colors.card,
        borderRadius: 99,
    },
    medSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(8),
        paddingHorizontal: scale(2),
    },
    medSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    medSecLabel: {
        fontSize: scaleFont(11),
        fontWeight: '800',
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },

    // Medicine rows
    medRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(13),
    },
    medRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    medRowIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    medRowName: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.text,
    },
    medRowSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    medDaysLeftBadge: {
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        backgroundColor: colors.cReminderBg,
        borderWidth: 1,
        borderColor: '#FDE68A',
        marginRight: scale(4),
    },
    medDaysLeftText: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.cReminder,
    },
    medNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(9),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(11),
        backgroundColor: colors.cReminderBg,
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(12),
        marginTop: verticalScale(4),
    },
    medNoteText: {
        flex: 1,
        fontSize: scaleFont(11),
        fontWeight: '500',
        color: '#92400E',
        lineHeight: verticalScale(17),
    },

    // Detail sheet
    medSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(24),
        borderTopRightRadius: moderateScale(24),
        paddingBottom: verticalScale(32),
        maxHeight: '90%',
    },
    medDetailHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(10),
    },
    medDetailName: {
        fontSize: scaleFont(17),
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.2,
    },
    medDetailSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    medDetailBadge: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },

    // Pill widget
    medPillWidget: {
        backgroundColor: colors.bg,
        borderRadius: moderateScale(16),
        padding: scale(14),
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        marginBottom: verticalScale(14),
    },
    medPillRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: verticalScale(10),
    },
    medPillLabel: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: verticalScale(3),
    },
    medPillNum: {
        fontSize: scaleFont(26),
        fontWeight: '800',
        color: colors.cFamily,
        lineHeight: verticalScale(30),
    },
    medPillTotal: {
        fontSize: scaleFont(12),
        fontWeight: '600',
        color: colors.text3,
    },
    medPillTrack: {
        height: verticalScale(7),
        backgroundColor: colors.border,
        borderRadius: 99,
        overflow: 'hidden',
    },
    medPillFill: {
        height: '100%',
        borderRadius: 99,
    },
    medPillPct: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.text3,
        textAlign: 'right',
        marginTop: verticalScale(5),
    },

    // Info rows
    medInfoCard: {
        backgroundColor: colors.bg,
        borderRadius: moderateScale(14),
        overflow: 'hidden',
        marginHorizontal: scale(20),
        marginBottom: verticalScale(14),
    },
    medInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
    },
    medInfoRowBorder: {
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    medInfoLabel: {
        fontSize: scaleFont(12),
        fontWeight: '600',
        color: colors.text2,
    },
    medInfoValue: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text,
        textAlign: 'right',
    },
    medDetailNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(8),
        marginHorizontal: scale(20),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.bg,
        borderRadius: moderateScale(12),
    },
    medDetailNoteText: {
        flex: 1,
        fontSize: scaleFont(12),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },

    // Dose dots on today card
    medDoseDots: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(5),
        marginTop: verticalScale(8),
        marginBottom: verticalScale(10),
    },
    medDoseDot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
        borderRadius: 99,
        paddingVertical: verticalScale(3),
        paddingLeft: scale(5),
        paddingRight: scale(8),
    },
    medDoseDotCircle: {
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
    },
    medDoseDotText: {
        fontSize: scaleFont(9),
        fontWeight: '700',
    },

    // Detail full-screen header
    mdHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(12),
    },
    mdEditBtn: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // Edit form
    mdEditForm: {
        gap: scale(11),
    },
    mdFieldLabel: {
        fontSize: scaleFont(11),
        fontWeight: '700',
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: verticalScale(5),
    },
    mdInput: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text,
    },
    mdRowGrid: {
        flexDirection: 'row',
        gap: scale(10),
    },
    mdFreqRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(6),
    },
    mdFreqChip: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    mdFreqChipActive: {
        borderColor: colors.cFamily,
        backgroundColor: colors.secondaryBg,
    },
    mdFreqChipText: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text2,
    },
    mdFreqChipTextActive: {
        color: colors.cFamily,
    },
    mdMealChip: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },

    // Time slot rows
    mdSlotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        marginBottom: verticalScale(6),
    },
    mdSlotChip: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        minWidth: scale(80),
        alignItems: 'center',
    },
    mdSlotChipActive: {
        borderColor: colors.cFamily,
        backgroundColor: colors.secondaryBg,
    },
    mdSlotChipText: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text3,
    },
    mdSlotChipTextActive: {
        color: colors.cFamily,
    },
    mdSlotTime: {
        flex: 1,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(10),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text3,
    },
    mdSlotTimeActive: {
        borderColor: colors.secondary,
        color: colors.text,
    },

    // Save / Delete buttons
    mdSaveBtn: {
        borderRadius: moderateScale(14),
        overflow: 'hidden',
        marginTop: verticalScale(2),
    },
    mdSaveBtnInner: {
        paddingVertical: verticalScale(13),
        alignItems: 'center',
    },
    mdSaveBtnText: {
        fontSize: scaleFont(14),
        fontWeight: '800',
        color: colors.card,
    },
    mdDeleteBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        paddingVertical: verticalScale(13),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: '#FECDD3',
        backgroundColor: colors.cDangerBg,
    },
    mdDeleteText: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.cDanger,
    },

    // Choose sheet
    mdChooseOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
        padding: scale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
    },
    mdChooseIcon: {
        width: moderateScale(42),
        height: moderateScale(42),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdChooseTitle: {
        fontSize: scaleFont(14),
        fontWeight: '700',
        color: colors.text,
    },
    mdChooseSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    mdAiBadge: {
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        backgroundColor: colors.primaryBg,
        borderWidth: 1,
        borderColor: colors.primaryLight,
    },
    mdAiBadgeText: {
        fontSize: scaleFont(9),
        fontWeight: '800',
        color: colors.primary,
    },

    // Add sheet header
    mdAddHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mdAddBackBtn: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(15),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdAddTitle: {
        fontSize: scaleFont(16),
        fontWeight: '800',
        color: colors.text,
    },

    // ═══════════════════════════════════
    //  RECORDS: Context menu
    // ═══════════════════════════════════
    recMoreBtn: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    ctxMenu: {
        position: 'absolute',
        right: 0,
        top: verticalScale(30),
        width: scale(145),
        backgroundColor: colors.card,
        borderRadius: moderateScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        zIndex: 50,
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
    },
    ctxItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemText: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text,
    },
    ctxDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    ctxItemDel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemDelText: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.cDanger,
    },

    // ═══════════════════════════════════
    //  RECORDS: Specialty picker modal
    // ═══════════════════════════════════
    specGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(24),
    },
    specItem: {
        width: '30%' as unknown as number,
        alignItems: 'center',
        paddingVertical: verticalScale(14),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    specItemActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    specIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(6),
    },
    specLabel: {
        fontSize: scaleFont(11),
        fontWeight: '600',
        color: colors.text2,
    },
    specLabelActive: {
        color: colors.primary,
        fontWeight: '700',
    },

    // ═══════════════════════════════════
    //  VACCINE: Dose dots
    // ═══════════════════════════════════
    vaxDots: {
        flexDirection: 'row',
        gap: scale(4),
        marginTop: verticalScale(5),
    },
    vaxDotBar: {
        width: scale(20),
        height: verticalScale(3),
        borderRadius: moderateScale(3),
    },

    // ═══════════════════════════════════
    //  VACCINE: Next shot banner
    // ═══════════════════════════════════
    vaxNextShot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        backgroundColor: colors.cReminderBg,
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(14),
        marginBottom: verticalScale(14),
    },
    vaxNextShotIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(9),
        backgroundColor: 'rgba(217,119,6,0.12)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxNextShotBody: {
        flex: 1,
    },
    vaxNextShotLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        color: colors.cReminder,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    vaxNextShotName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginTop: verticalScale(1),
    },
    vaxNextShotDate: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.cReminder,
    },

    // ═══════════════════════════════════
    //  VACCINE: Detail bottom sheet
    // ═══════════════════════════════════
    vaxSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(24),
        borderTopRightRadius: moderateScale(24),
        paddingBottom: verticalScale(32),
        maxHeight: '85%',
    },
    vaxDetailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(10),
    },
    vaxDetailName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
        letterSpacing: -0.2,
    },
    vaxDetailAbbr: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vaxDetailBadge: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },
    vaxDoseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(13),
    },
    vaxDoseRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxDoseNum: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDoseNumText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
    },
    vaxDoseBody: { flex: 1 },
    vaxDoseLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vaxDoseSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    vaxDoseStatus: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
    },

    // ═══════════════════════════════════
    //  VACCINE ROW: scheduled date line
    // ═══════════════════════════════════
    vaxRowSchedLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        marginTop: verticalScale(3),
    } as const,
    vaxRowSchedText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.primary,
    },

    // ═══════════════════════════════════
    //  VACCINE DETAIL – full screen
    // ═══════════════════════════════════
    vdSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        marginBottom: verticalScale(16),
    } as const,
    vdSummaryLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: verticalScale(3),
    } as const,
    vdSummaryProgress: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        letterSpacing: -0.3,
    },
    vdSummarySub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdStatusBadge: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },
    vdStatusBadgeText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
    },

    // Dose items (detail screen)
    vdDoseItem: {
        flexDirection: 'row',
        gap: scale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(13),
    } as const,
    vdDoseItemBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vdDoseDot: {
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(2),
    } as const,
    vdDoseDotDone: {
        backgroundColor: colors.cHealthBg,
        borderWidth: 1.5,
        borderColor: '#BBF7D0',
    },
    vdDoseDotScheduled: {
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
    },
    vdDoseDotEmpty: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
    } as const,
    vdDoseLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: verticalScale(3),
    } as const,
    vdDoseVal: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    vdDosePlace: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdDoseTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        overflow: 'hidden',
        alignSelf: 'flex-start',
        marginTop: verticalScale(4),
    } as const,
    vdDoseTagDone: {
        backgroundColor: colors.cHealthBg,
        color: colors.cHealth,
        borderColor: '#BBF7D0',
    },
    vdDoseTagScheduled: {
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        borderColor: colors.primaryLight,
    },

    // Schedule button (blue bg)
    vdSchedBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        padding: scale(13),
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(14),
        backgroundColor: colors.primaryBg,
    } as const,
    vdSchedBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },

    // Bottom sheet content
    vdSheetContent: {
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(32),
    },
    vdSheetTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
        marginBottom: verticalScale(14),
    },
    vdFieldLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginBottom: verticalScale(6),
    },
    vdFieldInput: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    vdPhotoUpload: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        padding: scale(14),
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        borderRadius: moderateScale(12),
    } as const,
    vdPhotoUploadText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    vdSaveBtn: {
        marginTop: verticalScale(2),
        borderRadius: moderateScale(14),
        overflow: 'hidden',
    },
    vdSaveBtnGrad: {
        paddingVertical: verticalScale(13),
        alignItems: 'center',
    } as const,
    vdSaveBtnText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(14),
        color: colors.card,
    },

    // Remind chips
    vdRemindRow: {
        flexDirection: 'row',
        gap: scale(8),
    } as const,
    vdRemindChip: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(9),
        borderRadius: moderateScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    vdRemindChipActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    vdRemindChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text2,
    },
    vdRemindChipTextActive: {
        color: colors.primary,
    },

    // ═══════════════════════════════════
    //  MEDICINE: Today card extras
    // ═══════════════════════════════════
    medTodayWarn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        marginTop: verticalScale(5),
    },
    medTodayWarnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 0.3,
    },
    medNextDose: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        marginTop: verticalScale(4),
    },
    medNextDoseText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.6)',
    },
    medNextDoseTime: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.9)',
    },

    // Medicine row time chips
    medTimeChips: {
        flexDirection: 'row',
        gap: scale(4),
        marginTop: verticalScale(3),
    },
    medTimeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
        paddingHorizontal: scale(6),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        backgroundColor: colors.bg,
    },
    medTimeChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(9),
        color: colors.text2,
    },

    // ═══════════════════════════════════
    //  RECORD DETAIL
    // ═══════════════════════════════════
    rdHero: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(20),
    },
    rdHeroTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        marginBottom: verticalScale(14),
    },
    rdHeroBack: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdHeroTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(19),
        color: colors.card,
        letterSpacing: -0.2,
        flex: 1,
    },
    rdMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(16),
    },
    rdMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    rdMetaIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(10),
        backgroundColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdMetaLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.6)',
    },
    rdMetaValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.card,
    },
    rdMetaDivider: {
        width: 1,
        height: verticalScale(30),
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    rdTabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: scale(20),
    },
    rdTab: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(4),
        marginRight: scale(20),
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    rdTabActive: {
        borderBottomColor: colors.primary,
    },
    rdTabText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    rdTabTextActive: {
        color: colors.primary,
        fontFamily: typography.font.bold,
    },
    rdInfoCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(18),
        overflow: 'hidden',
    },
    rdInfoRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
    },
    rdInfoRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    rdInfoDiag: {
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
    },
    rdInfoIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdInfoLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(3),
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    rdInfoValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
        lineHeight: verticalScale(20),
    },
    rdInfoEmpty: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text3,
        fontStyle: 'italic',
    },
    rdEmptyWrap: {
        alignItems: 'center',
        padding: scale(20),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        backgroundColor: colors.bg,
    },
    rdEmptyTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(6),
    },
    rdEmptySub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    rdAttachGrid: {
        flexDirection: 'row',
        gap: scale(10),
        marginBottom: verticalScale(12),
    },
    rdAttachBtn: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: verticalScale(16),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        backgroundColor: colors.card,
    },
    rdAttachIcon: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdAttachLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        marginTop: verticalScale(6),
    },
    rdAttachSub: {
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    rdFollowHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(12),
    },
    rdFollowBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(10),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(7),
    },
    rdFollowBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },

    // Follow-up add card
    fuCard: {
        backgroundColor: colors.card,
        borderWidth: 2,
        borderColor: colors.primary,
        borderRadius: moderateScale(16),
        padding: scale(16),
        marginBottom: verticalScale(12),
    },
    fuCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        marginBottom: verticalScale(14),
    },
    fuCardIcon: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(9),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuCardTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    fuField: {
        marginBottom: verticalScale(10),
    },
    fuLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginBottom: verticalScale(5),
    },
    fuInput: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
        fontSize: scaleFont(13),
        color: colors.text,
        backgroundColor: colors.bg,
    },
    fuBtnRow: {
        flexDirection: 'row',
        gap: scale(8),
        marginTop: verticalScale(16),
    },
    fuCancelBtn: {
        flex: 1,
        paddingVertical: verticalScale(11),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        backgroundColor: colors.bg,
        alignItems: 'center',
    },
    fuCancelText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text2,
    },
    fuSaveBtn: {
        flex: 2,
        paddingVertical: verticalScale(11),
        borderRadius: moderateScale(12),
        backgroundColor: colors.primary,
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.25,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    fuSaveText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.card,
    },
    // Saved follow-up item
    fuItem: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        padding: scale(14),
        marginBottom: verticalScale(10),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    fuItemIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuItemBody: {
        flex: 1,
    },
    fuItemDate: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    fuItemPurpose: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    fuItemDelete: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ═══════════════════════════════════
    //  ADD RECORD FORM
    // ═══════════════════════════════════
    arGroup: {
        marginBottom: verticalScale(14),
    },
    arLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text2,
        marginBottom: verticalScale(6),
    },
    arInput: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
        backgroundColor: colors.card,
    },
    arInputIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        backgroundColor: colors.card,
    },
    arInputBare: {
        flex: 1,
        fontSize: scaleFont(13),
        color: colors.text,
        padding: 0,
    },
    arTextarea: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
        backgroundColor: colors.card,
        minHeight: verticalScale(80),
        textAlignVertical: 'top',
    },
    arRow: {
        flexDirection: 'row',
        gap: scale(12),
    },
    arSelectWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        backgroundColor: colors.card,
    },
    arSelectText: {
        flex: 1,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    arSelectPlaceholder: {
        flex: 1,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    arDivider: {
        height: 1.5,
        backgroundColor: colors.border,
        borderRadius: moderateScale(2),
        marginTop: verticalScale(20),
        marginBottom: verticalScale(16),
    },
    arSaveWrap: {
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(28),
        paddingTop: verticalScale(12),
    },

    // ═══════════════════════════════════
    //  NOTIFICATION SCREEN
    // ═══════════════════════════════════
    notiTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        gap: scale(12),
    },
    notiTitle: {
        fontSize: scaleFont(17),
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.2,
    },
    notiUnreadCount: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    notiMarkAllBtn: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(20),
        backgroundColor: colors.secondaryBg,
        borderWidth: 1,
        borderColor: colors.secondary,
    },
    notiMarkAllText: {
        fontSize: scaleFont(11),
        fontWeight: '700',
        color: colors.cFamily,
    },
    notiGroupLabel: {
        fontSize: scaleFont(10),
        fontWeight: '800',
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        paddingHorizontal: scale(4),
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(6),
    },
    notiItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        borderRadius: moderateScale(16),
        marginBottom: verticalScale(3),
    },
    notiItemUnread: {
        backgroundColor: colors.primaryBg,
        borderWidth: 1,
        borderColor: colors.primaryLight,
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
    },
    notiItemRead: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    notiIcon: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(1),
    },
    notiTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: scale(8),
        marginBottom: verticalScale(3),
    },
    notiItemTitle: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text2,
        lineHeight: verticalScale(18),
        flex: 1,
    },
    notiTime: {
        fontSize: scaleFont(10),
        fontWeight: '600',
        color: colors.text3,
        paddingTop: verticalScale(2),
    },
    notiBody: {
        fontSize: scaleFont(11),
        color: colors.text3,
        lineHeight: verticalScale(17),
    },
    notiVaxChips: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        flexWrap: 'wrap',
        marginTop: verticalScale(3),
    },
    notiVaxChip: {
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },
    notiVaxChipText: {
        fontSize: scaleFont(10),
        fontWeight: '700',
    },
    notiVaxDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        marginTop: verticalScale(4),
    },
    notiVaxDateText: {
        fontSize: scaleFont(10),
        fontWeight: '600',
        color: colors.text3,
    },
    notiBadge: {
        position: 'absolute',
        top: verticalScale(4),
        right: scale(4),
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
        backgroundColor: '#EF4444',
        borderWidth: 1.5,
        borderColor: colors.card,
    },
});
