import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import {
    buttonSystem,
    formSystem,
    inputSystem,
    shared,
} from '../../styles/shared';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    statusTopSpacer: { height: verticalScale(4) },
    topbar: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
    },
    topbarRight: {
        flexDirection: 'row',
        gap: scale(8),
    },
    member: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        borderRadius: moderateScale(16),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: verticalScale(11),
        paddingHorizontal: scale(14),
        flexDirection: 'row',
        alignItems: 'flex-start',
        ...shadows.card,
    },
    mAvatar: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(19),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(11),
    },
    mAvatarText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    mDot: {
        position: 'absolute',
        bottom: verticalScale(1),
        right: scale(1),
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
        backgroundColor: colors.success,
        borderWidth: 2,
        borderColor: colors.card,
    },
    mInfo: { flex: 1 },
    mName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    mRole: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    bmiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(10),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    bmiIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    bmiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(4),
    },
    bmiValueRow: { flexDirection: 'row', alignItems: 'flex-end' },
    bmiValue: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
        letterSpacing: -0.7,
    },
    bmiUnit: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10.5),
        color: colors.text3,
        marginLeft: scale(4),
    },
    bmiSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    bmiBadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.success,
        backgroundColor: colors.successBg,
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(16),
        overflow: 'hidden',
    },
    bmiGaugeWrap: {
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(12),
    },
    bmiGaugeTrack: {
        height: verticalScale(6),
        borderRadius: moderateScale(8),
        backgroundColor: colors.border,
        justifyContent: 'center',
    },
    bmiGaugeThumb: {
        position: 'absolute',
        left: '52%',
        width: moderateScale(12),
        height: moderateScale(12),
        borderRadius: moderateScale(6),
        backgroundColor: colors.card,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    bmiGaugeLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: verticalScale(6),
    },
    bmiGaugeLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(9.5),
    },

    // ── Health Info Rows ──
    hiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(12),
    },
    hiRowLast: {
        borderBottomWidth: 0,
    },
    hiIcon: {
        width: moderateScale(42),
        height: moderateScale(42),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(1),
    },
    hiBody: {
        flex: 1,
        justifyContent: 'center',
        paddingTop: verticalScale(1),
    },
    hiLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(2),
    },
    hiValueInline: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
        letterSpacing: -0.3,
    },
    hiTags: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: scale(8),
        marginTop: verticalScale(2),
    },
    hiTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        lineHeight: verticalScale(15),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(16),
        overflow: 'hidden',
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    hiEmpty: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        fontStyle: 'italic',
        color: colors.text3,
        marginTop: verticalScale(4),
    },

    // ── Visit Rows ──
    miniCardRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    miniCardRowLast: {
        borderBottomWidth: 0,
    },
    miniCardRowIcon: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(10),
    },
    miniCardRowBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: verticalScale(30),
    },
    miniCardRowBodyCompact: {
        flex: 1,
        justifyContent: 'center',
        minHeight: 0,
        paddingVertical: verticalScale(2),
    },
    miniCardRowTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    miniCardRowTitleCompact: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13.5),
        color: colors.text,
    },
    miniCardRowSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    healthInfoRowObj: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    healthInfoRowLast: {
        borderBottomWidth: 0,
    },
    hiIconWrap: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    hiLabelTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginBottom: verticalScale(4),
    },
    hiChipsWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: scale(6),
        marginTop: verticalScale(1),
    },
    hiChip: {
        minHeight: verticalScale(22),
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(999),
        backgroundColor: colors.divider,
    },
    hiChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        lineHeight: verticalScale(14),
        color: colors.text2,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    hiChipTextTruncated: {
        maxWidth: scale(130),
    },
    hiChipMutedBtn: {
        borderRadius: moderateScale(999),
    },
    hiChipMuted: {
        minHeight: verticalScale(22),
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(999),
        backgroundColor: colors.divider,
    },
    hiChipMutedText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.5),
        lineHeight: verticalScale(14),
        color: colors.text2,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    hiMetaText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10.5),
        color: colors.text3,
    },
    hiEmptyText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        fontStyle: 'italic',
        color: colors.text3,
    },
    hiBlockWrap: {
        marginTop: verticalScale(5),
        backgroundColor: '#F1F5F9',
        borderRadius: moderateScale(10),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(9),
    },
    hiBlockText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text2,
    },
    tagPreviewWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    tagPreviewChip: {
        minHeight: verticalScale(24),
        alignItems: 'center',
        justifyContent: 'center',
        borderRadius: moderateScale(999),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(5),
        backgroundColor: colors.divider,
    },
    tagPreviewChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        lineHeight: verticalScale(15),
        color: colors.text2,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    visitRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    visitIcon: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(10),
        marginTop: verticalScale(1),
    },
    visitBody: { flex: 1 },
    visitTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    visitSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    visitTag: {
        marginTop: verticalScale(5),
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(999),
        alignSelf: 'flex-start',
    },
    visitDate: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text2,
        backgroundColor: colors.bgHealth,
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(8),
        overflow: 'hidden',
        marginTop: verticalScale(2),
    },

    // ── Vaccine / Donut ──
    vpctRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    donutWrap: {
        width: moderateScale(60),
        height: moderateScale(60),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(16),
    },
    donutSvg: {
        position: 'absolute',
    },
    donutPercent: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: '#0A8F74',
    },
    vpctTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
    },
    vpctSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    vIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    vBody: { flex: 1 },
    vName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    vDate: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
    },

    // ── Tips ──
    tipsRow: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
    },
    tipCard: {
        width: moderateScale(144),
        borderRadius: moderateScale(16),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        padding: scale(14),
        marginRight: scale(10),
        ...shadows.card,
    },
    tipEmoji: { fontSize: scaleFont(22), marginBottom: verticalScale(8) },
    tipTitle: {
        fontSize: scaleFont(12),
        color: colors.text,
        marginBottom: verticalScale(3),
    },
    tipSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
        lineHeight: verticalScale(14),
    },

    // ── Bottom Sheet: Blood Type Grid ──
    btGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    btOpt: {
        width: '23%' as unknown as number,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(10),
        minHeight: verticalScale(44),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.card,
    },
    btOptSel: {
        borderColor: colors.danger,
        backgroundColor: colors.dangerBg,
    },
    btOptText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(12),
        color: colors.text2,
    },
    btOptTextSel: {
        color: colors.danger,
    },

    // ── Bottom Sheet: Tag Input ──
    tagInputWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        alignContent: 'center',
        justifyContent: 'flex-start',
        rowGap: scale(6),
        columnGap: scale(6),
        ...inputSystem.field,
        paddingLeft: scale(10),
        paddingRight: scale(10),
        paddingVertical: 0,
        minHeight: verticalScale(42),
        alignSelf: 'stretch',
        width: '100%',
        overflow: 'hidden',
    },
    tagChip: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(4),
        backgroundColor: colors.divider,
        minHeight: verticalScale(24),
        paddingVertical: verticalScale(3),
        paddingLeft: scale(8),
        paddingRight: scale(6),
        borderRadius: moderateScale(7),
        alignSelf: 'auto',
        maxWidth: '100%',
    },
    tagChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        lineHeight: verticalScale(14),
        color: colors.text2,
        flexShrink: 1,
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    tagChipX: {
        fontSize: scaleFont(13),
        lineHeight: verticalScale(14),
        color: colors.text2,
        opacity: 0.6,
        paddingHorizontal: scale(2),
        textAlignVertical: 'center',
        includeFontPadding: false,
    },
    tagInput: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: scale(72),
        minWidth: scale(72),
        maxWidth: '100%',
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        lineHeight: verticalScale(16),
        color: colors.text,
        paddingHorizontal: 0,
        paddingVertical: 0,
        minHeight: verticalScale(24),
        alignSelf: 'center',
        textAlignVertical: 'center',
    },
    noteInput: {
        ...inputSystem.textarea,
        minHeight: verticalScale(110),
        paddingHorizontal: scale(14),
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    tagHint: {
        fontSize: scaleFont(10.5),
        color: colors.text3,
        marginTop: verticalScale(6),
    },

    // ═══════════════════════════════════
    //  SUB-SCREEN: Shared topbar
    // ═══════════════════════════════════
    subTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.card,
    },
    vaxSubTopbar: {
        backgroundColor: 'transparent',
        paddingHorizontal: scale(16),
        gap: scale(8),
    },
    vaxBackBtn: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
    },
    subBackBtn: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(18),
        alignItems: 'center',
        justifyContent: 'center',
    },
    subTopbarTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(18),
        color: colors.text,
    },
    subTopbarTitleCenterWrap: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: scale(8),
    },
    subTopbarTitleCentered: {
        flex: 0,
        textAlign: 'center',
    },
    subTopbarActionPlaceholder: {
        width: moderateScale(36),
        height: moderateScale(36),
    },
    subAddBtn: {
        ...shared.iconBtn,
    },
    subAddBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(1),
        color: 'transparent',
        width: 0,
        height: 0,
        opacity: 0,
    },
    vaxTopbarActions: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        position: 'relative',
        zIndex: 40,
        elevation: 8,
    },
    vaxAddIconBtn: {
        ...shared.iconBtn,
    },
    vaxDetailTopbar: {
        backgroundColor: colors.bg,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(12),
        gap: scale(8),
    },
    vaxDetailBackBtn: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        backgroundColor: 'transparent',
        borderWidth: 0,
        borderColor: 'transparent',
    },
    vaxDetailTopbarTitle: {
        flex: 1,
        fontFamily: typography.font.bold,
        fontSize: scaleFont(18),
        color: colors.text,
    },
    vaxDetailAddBtn: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(14),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
        ...shadows.card,
        shadowOpacity: 0.08,
        elevation: 2,
    },
    vaxInfoBtn: {
        ...shared.iconBtn,
    },
    vaxInfoTooltip: {
        position: 'absolute',
        top: verticalScale(44),
        right: scale(4),
        width: scale(172),
        zIndex: 50,
        elevation: 10,
    },
    vaxInfoTooltipBody: {
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: '#D7E9E0',
        backgroundColor: '#FCFEFD',
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(9),
        shadowColor: '#1E293B',
        shadowOpacity: 0.06,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 2,
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(7),
    },
    vaxInfoTooltipIconWrap: {
        width: moderateScale(18),
        height: moderateScale(18),
        borderRadius: moderateScale(9),
        backgroundColor: '#EEF8F3',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxInfoTooltipText: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10),
        color: colors.text2,
        lineHeight: verticalScale(15),
    },
    vaxInfoTooltipTextStrong: {
        fontFamily: typography.font.bold,
        color: colors.primary,
    },

    // ═══════════════════════════════════
    //  RECORDS SCREEN
    // ═══════════════════════════════════
    searchFilterWrap: {
        backgroundColor: colors.card,
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    searchWrap: {
        ...inputSystem.fieldIcon,
        gap: scale(10),
        backgroundColor: colors.bg,
        borderColor: colors.border,
        borderRadius: moderateScale(11),
        paddingHorizontal: scale(12),
    },
    searchInput: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text,
        padding: 0,
        textAlignVertical: 'center',
    },
    filterRow: {
        flexDirection: 'row',
        gap: scale(6),
        marginTop: verticalScale(10),
    },
    filterChip: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(4),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    filterChipActive: {
        backgroundColor: colors.primaryBg,
        borderColor: colors.primaryLight,
    },
    filterChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    filterChipTextActive: {
        color: colors.primary,
    },

    // Timeline items
    recYearHdr: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(20),
        paddingBottom: verticalScale(6),
        letterSpacing: -0.3,
    },
    recMonthHdr: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text2,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(8),
    },
    recItem: {
        flexDirection: 'row',
        paddingLeft: scale(20),
        paddingRight: scale(16),
        marginBottom: verticalScale(2),
    },
    recTimeline: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginRight: scale(12),
        width: scale(56),
    },
    recDateCol: {
        alignItems: 'center',
        width: scale(28),
    },
    recDay: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
        lineHeight: verticalScale(22),
    },
    recMon: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    recDotCol: {
        alignItems: 'center',
        marginLeft: scale(8),
        paddingTop: verticalScale(6),
    },
    recDot: {
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
    },
    recLine: {
        width: 2,
        flex: 1,
        backgroundColor: colors.border,
        marginTop: verticalScale(4),
        minHeight: verticalScale(60),
    },
    recCard: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        overflow: 'hidden',
        marginBottom: verticalScale(10),
        ...shadows.card,
    },
    recCardTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: scale(14),
        gap: scale(12),
    },
    recIconWrap: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    recContent: {
        flex: 1,
        gap: verticalScale(5),
    },
    recTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: scale(10),
    },
    recTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    recMetaLine: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    recDiagnosis: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },
    recChipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(2),
    },
    recSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    recDiagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(4),
        gap: scale(4),
    },
    recDiagDot: {
        width: moderateScale(6),
        height: moderateScale(6),
        borderRadius: moderateScale(3),
        backgroundColor: colors.text3,
    },
    recDiagText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        flex: 1,
    },
    recCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    recTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        overflow: 'hidden',
    },
    recMetaRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
    },
    recMetaText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10),
        color: colors.text3,
    },
    recEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(64),
        paddingHorizontal: scale(32),
    },
    recEmptyIcon: {
        width: moderateScale(72),
        height: moderateScale(72),
        borderRadius: moderateScale(22),
        backgroundColor: colors.primaryBg,
        borderWidth: 2,
        borderColor: colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(16),
    },
    recEmptyTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
        marginBottom: verticalScale(6),
    },
    recEmptySub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text3,
    },

    // ═══════════════════════════════════
    //  VACCINE SCREEN
    // ═══════════════════════════════════
    vaxHero: {
        borderRadius: moderateScale(20),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
        marginBottom: verticalScale(16),
        overflow: 'hidden',
        ...shadows.card,
    },
    vaxHeroContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
    },
    vaxHeroBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: verticalScale(62),
    },
    vaxDonut: {
        width: moderateScale(62),
        height: moderateScale(62),
    },
    vaxDonutTrack: {
        width: moderateScale(62),
        height: moderateScale(62),
        borderRadius: moderateScale(31),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDonutSvg: {
        position: 'absolute',
        width: moderateScale(62),
        height: moderateScale(62),
        transform: [{ rotate: '0deg' }],
    },
    vaxDonutText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13.5),
        color: '#0A8F74',
    },
    vaxHeroSup: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.5),
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(2),
    },
    vaxHeroCountRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        gap: scale(4),
        marginBottom: verticalScale(8),
    },
    vaxHeroNum: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
        lineHeight: verticalScale(26),
        letterSpacing: -0.5,
    },
    vaxHeroNumSub: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text2,
    },
    vaxHeroPendingPill: {
        alignSelf: 'flex-start',
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(999),
        backgroundColor: colors.warningBg,
    },
    vaxHeroPendingDot: {
        width: moderateScale(6),
        height: moderateScale(6),
        borderRadius: moderateScale(3),
        backgroundColor: colors.warning,
    },
    vaxHeroPendingText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.warning,
    },

    // Section headers
    vaxSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(8),
        paddingHorizontal: 2,
        marginTop: verticalScale(4),
    },
    vaxSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    vaxSecIconWrap: {
        width: moderateScale(26),
        height: moderateScale(26),
        borderRadius: moderateScale(13),
        borderWidth: 1,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxSecLabel: {
        ...formSystem.sectionTitle,
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.7,
    },
    vaxSecCount: {
        display: 'none',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxListCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        marginBottom: verticalScale(16),
        ...shadows.card,
    },

    // Vaccine rows
    vaxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
    },
    vaxRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxRowIcon: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxRowBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: verticalScale(30),
    },
    vaxRowName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13.5),
        color: colors.text,
    },
    vaxRowSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    vaxRowMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        marginTop: verticalScale(4),
        flexWrap: 'wrap',
    },
    vaxRowMetaSecondary: {
        marginTop: verticalScale(3),
    },
    vaxChip: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxChipDone: {
        backgroundColor: '#F1FFF5',
        color: '#16A34A',
        borderColor: '#A7F3C0',
    },
    vaxChipSoon: {
        backgroundColor: '#FFF7E6',
        color: '#E58A00',
        borderColor: '#FFD47A',
    },
    vaxChipPending: {
        backgroundColor: '#FFF1F4',
        color: '#F43F5E',
        borderColor: '#FDA4AF',
    },
    vaxChipScheduled: {
        backgroundColor: '#EDF4FF',
        color: '#2563EB',
        borderColor: '#BFDBFE',
    },
    vaxChipLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.5),
        color: '#93A3BC',
    },

    // Add button & note
    vaxAddBtn: {
        ...buttonSystem.outline,
        paddingHorizontal: scale(16),
        borderStyle: 'dashed',
        borderRadius: moderateScale(18),
        backgroundColor: colors.card,
    },
    vaxAddBtnText: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.text2,
    },
    vaxNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(8),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(11),
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(12),
        marginTop: verticalScale(12),
    },
    vaxNoteText: {
        flex: 1,
        fontSize: scaleFont(11),
        fontWeight: '500',
        color: colors.primary,
        lineHeight: verticalScale(17),
    },
    // ═══════════════════════════════════
    //  MEDICINE SCREEN
    // ═══════════════════════════════════
    medTodayCard: {
        borderRadius: moderateScale(20),
        padding: scale(16),
        marginBottom: verticalScale(16),
        overflow: 'hidden',
    },
    medTodaySup: {
        fontSize: scaleFont(11),
        fontWeight: '700',
        color: 'rgba(255,255,255,0.7)',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(6),
    },
    medTodayRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        marginBottom: verticalScale(10),
    },
    medTodayNum: {
        fontSize: scaleFont(22),
        fontWeight: '800',
        color: colors.card,
        lineHeight: verticalScale(26),
        letterSpacing: -0.4,
    },
    medTodayNumSub: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        opacity: 0.7,
    },
    medTodayPct: {
        fontSize: scaleFont(20),
        fontWeight: '800',
        color: 'rgba(255,255,255,0.85)',
    },
    medProgressTrack: {
        height: verticalScale(7),
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderRadius: 99,
        overflow: 'hidden',
    },
    medProgressFill: {
        height: '100%',
        backgroundColor: colors.card,
        borderRadius: 99,
    },
    medSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(8),
        paddingHorizontal: scale(2),
    },
    medSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    medSecLabel: {
        fontSize: scaleFont(11),
        fontWeight: '800',
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },

    // Medicine rows
    medRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(13),
    },
    medRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    medRowIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    medRowName: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.text,
    },
    medRowSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    medDaysLeftBadge: {
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        backgroundColor: colors.warningBg,
        borderWidth: 1,
        borderColor: '#FDE68A',
        marginRight: scale(4),
    },
    medDaysLeftText: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.warning,
    },
    medNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(9),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(11),
        backgroundColor: colors.warningBg,
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(12),
        marginTop: verticalScale(4),
    },
    medNoteText: {
        flex: 1,
        fontSize: scaleFont(11),
        fontWeight: '500',
        color: colors.warning,
        lineHeight: verticalScale(17),
    },

    // Detail sheet
    medSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(24),
        borderTopRightRadius: moderateScale(24),
        paddingBottom: verticalScale(32),
        maxHeight: '90%',
    },
    medDetailHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(10),
    },
    medDetailName: {
        fontSize: scaleFont(17),
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.2,
    },
    medDetailSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    medDetailBadge: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },

    // Pill widget
    medPillWidget: {
        backgroundColor: colors.bg,
        borderRadius: moderateScale(16),
        padding: scale(14),
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        marginBottom: verticalScale(14),
    },
    medPillRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: verticalScale(10),
    },
    medPillLabel: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: verticalScale(3),
    },
    medPillNum: {
        fontSize: scaleFont(26),
        fontWeight: '800',
        color: colors.secondary,
        lineHeight: verticalScale(30),
    },
    medPillTotal: {
        fontSize: scaleFont(12),
        fontWeight: '600',
        color: colors.text3,
    },
    medPillTrack: {
        height: verticalScale(7),
        backgroundColor: colors.border,
        borderRadius: 99,
        overflow: 'hidden',
    },
    medPillFill: {
        height: '100%',
        borderRadius: 99,
    },
    medPillPct: {
        fontSize: scaleFont(10),
        fontWeight: '700',
        color: colors.text3,
        textAlign: 'right',
        marginTop: verticalScale(5),
    },

    // Info rows
    medInfoCard: {
        backgroundColor: colors.bg,
        borderRadius: moderateScale(14),
        overflow: 'hidden',
        marginHorizontal: scale(20),
        marginBottom: verticalScale(14),
    },
    medInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
    },
    medInfoRowBorder: {
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    medInfoLabel: {
        fontSize: scaleFont(12),
        fontWeight: '600',
        color: colors.text2,
    },
    medInfoValue: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text,
        textAlign: 'right',
    },
    medDetailNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(8),
        marginHorizontal: scale(20),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.bg,
        borderRadius: moderateScale(12),
    },
    medDetailNoteText: {
        flex: 1,
        fontSize: scaleFont(12),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },

    // Dose dots on today card
    medDoseDots: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(5),
        marginTop: verticalScale(8),
        marginBottom: verticalScale(10),
    },
    medDoseDot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
        borderRadius: 99,
        paddingVertical: verticalScale(3),
        paddingLeft: scale(5),
        paddingRight: scale(8),
    },
    medDoseDotCircle: {
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
    },
    medDoseDotText: {
        fontSize: scaleFont(9),
        fontWeight: '700',
    },

    // Detail full-screen header
    mdHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(12),
    },
    mdEditBtn: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // Edit form
    mdEditForm: {
        gap: scale(11),
    },
    mdFieldLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(6),
    },
    mdInput: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(13),
        paddingVertical: verticalScale(10),
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text,
    },
    mdRowGrid: {
        flexDirection: 'row',
        gap: scale(10),
    },
    mdFreqRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(6),
    },
    mdFreqChip: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    mdFreqChipActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    mdFreqChipText: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text2,
    },
    mdFreqChipTextActive: {
        color: colors.text,
    },
    mdMealChip: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },

    // Time slot rows
    mdSlotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        marginBottom: verticalScale(6),
    },
    mdSlotChip: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        minWidth: scale(80),
        alignItems: 'center',
    },
    mdSlotChipActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    mdSlotChipText: {
        fontSize: scaleFont(12),
        fontWeight: '700',
        color: colors.text3,
    },
    mdSlotChipTextActive: {
        color: colors.text,
    },
    mdSlotTime: {
        flex: 1,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(10),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text3,
    },
    mdSlotTimeActive: {
        borderColor: colors.text2,
        color: colors.text,
    },

    // Save / Delete buttons
    mdSaveBtn: {
        borderRadius: moderateScale(14),
        overflow: 'hidden',
        marginTop: verticalScale(2),
    },
    mdSaveBtnInner: {
        paddingVertical: verticalScale(13),
        alignItems: 'center',
    },
    mdSaveBtnText: {
        fontSize: scaleFont(14),
        fontWeight: '800',
        color: colors.card,
    },
    mdDeleteBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        paddingVertical: verticalScale(13),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: '#FECDD3',
        backgroundColor: colors.dangerBg,
    },
    mdDeleteText: {
        fontSize: scaleFont(13),
        fontWeight: '700',
        color: colors.danger,
    },

    // Choose sheet
    mdChooseOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
        padding: scale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
    },
    mdChooseIcon: {
        width: moderateScale(42),
        height: moderateScale(42),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdChooseTitle: {
        fontSize: scaleFont(14),
        fontWeight: '700',
        color: colors.text,
    },
    mdChooseSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    mdAiBadge: {
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        backgroundColor: colors.primaryBg,
        borderWidth: 1,
        borderColor: colors.primaryLight,
    },
    mdAiBadgeText: {
        fontSize: scaleFont(9),
        fontWeight: '800',
        color: colors.primary,
    },

    // Add sheet header
    mdAddHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mdAddBackBtn: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(15),
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdAddTitle: {
        fontSize: scaleFont(16),
        fontWeight: '800',
        color: colors.text,
    },

    // ═══════════════════════════════════
    //  RECORDS: Context menu
    // ═══════════════════════════════════
    recMoreBtn: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    ctxMenu: {
        position: 'absolute',
        right: 0,
        top: verticalScale(30),
        width: scale(145),
        backgroundColor: colors.card,
        borderRadius: moderateScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        zIndex: 50,
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
    },
    ctxItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemText: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text,
    },
    ctxDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    ctxItemDel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemDelText: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.danger,
    },

    // ═══════════════════════════════════
    //  RECORDS: Specialty picker modal
    // ═══════════════════════════════════
    specGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(24),
    },
    specItem: {
        width: '30%' as unknown as number,
        alignItems: 'center',
        paddingVertical: verticalScale(14),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    specItemActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    specIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: verticalScale(6),
    },
    specLabel: {
        fontSize: scaleFont(11),
        fontWeight: '600',
        color: colors.text2,
    },
    specLabelActive: {
        color: colors.text,
        fontWeight: '700',
    },

    // ═══════════════════════════════════
    //  VACCINE: Dose dots
    // ═══════════════════════════════════
    vaxDots: {
        flexDirection: 'row',
        gap: scale(5),
        marginTop: verticalScale(6),
    },
    vaxDotBar: {
        width: scale(18),
        height: verticalScale(4),
        borderRadius: moderateScale(3),
    },

    // ═══════════════════════════════════
    //  VACCINE: Next shot banner
    // ═══════════════════════════════════
    vaxNextShot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        backgroundColor: colors.warningBg,
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(14),
        marginBottom: verticalScale(14),
    },
    vaxNextShotIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(9),
        backgroundColor: 'rgba(217,119,6,0.12)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxNextShotBody: {
        flex: 1,
    },
    vaxNextShotLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        color: colors.warning,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    vaxNextShotName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginTop: verticalScale(1),
    },
    vaxNextShotDate: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.warning,
    },

    // ═══════════════════════════════════
    //  VACCINE: Detail bottom sheet
    // ═══════════════════════════════════
    vaxSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(24),
        borderTopRightRadius: moderateScale(24),
        paddingBottom: verticalScale(32),
        maxHeight: '85%',
    },
    vaxDetailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(4),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: scale(10),
    },
    vaxDetailName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
        letterSpacing: -0.2,
    },
    vaxDetailAbbr: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vaxDetailBadge: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },
    vaxDoseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(13),
    },
    vaxDoseRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxDoseNum: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDoseNumText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
    },
    vaxDoseBody: { flex: 1 },
    vaxDoseLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vaxDoseSub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    vaxDoseStatus: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
    },

    // ═══════════════════════════════════
    //  VACCINE ROW: scheduled date line
    // ═══════════════════════════════════
    vaxRowSchedLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        marginTop: verticalScale(5),
    } as const,
    vaxRowSchedText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: '#2563EB',
    },

    // ═══════════════════════════════════
    //  VACCINE DETAIL – full screen
    // ═══════════════════════════════════
    vdSummary: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        marginBottom: verticalScale(16),
        ...shadows.card,
        shadowOpacity: 0.08,
        elevation: 2,
    } as const,
    vdSummaryLabel: {
        ...formSystem.sectionTitle,
        color: colors.text3,
        letterSpacing: 0.6,
        marginBottom: verticalScale(4),
    } as const,
    vdSummaryProgress: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
        letterSpacing: -0.3,
    },
    vdSummarySub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdStatusBadge: {
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(20),
        borderWidth: 1.25,
        marginTop: verticalScale(2),
    },
    vdStatusBadgeText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
    },
    vdDoseCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        marginBottom: verticalScale(16),
        ...shadows.card,
        shadowOpacity: 0.08,
        elevation: 2,
    },

    // Dose items (detail screen)
    vdDoseItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(11),
        minHeight: verticalScale(48),
    } as const,
    vdDoseItemBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vdDoseBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: verticalScale(30),
    },
    vdDoseDot: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
    } as const,
    vdDoseDotDone: {
        backgroundColor: colors.successBg,
        borderWidth: 1.5,
        borderColor: '#BBF7D0',
    },
    vdDoseDotScheduled: {
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
    },
    vdDoseDotEmpty: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
    } as const,
    vdDoseLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginBottom: verticalScale(2),
    } as const,
    vdDoseVal: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    vdDosePlace: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdDoseTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(999),
        borderWidth: 1.25,
        overflow: 'hidden',
        alignSelf: 'flex-start',
        marginTop: verticalScale(4),
    } as const,
    vdDoseTagDone: {
        backgroundColor: colors.successBg,
        color: colors.success,
        borderColor: '#BBF7D0',
    },
    vdDoseTagScheduled: {
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        borderColor: colors.primaryLight,
    },

    // Schedule button (blue bg)
    vdSchedBtn: {
        ...buttonSystem.outline,
        minHeight: verticalScale(46),
        paddingHorizontal: scale(16),
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        backgroundColor: colors.card,
        justifyContent: 'center',
    } as const,
    vdSchedBtnText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text2,
    },

    // Bottom sheet content
    vdSheetContent: {
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(28),
    },
    vdSheetTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
        marginBottom: verticalScale(14),
    },
    vdFieldLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(6),
    },
    vdFieldInput: {
        ...inputSystem.field,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text,
        textAlignVertical: 'center',
    },
    vdPhotoUpload: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: scale(8),
        padding: scale(14),
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        borderRadius: moderateScale(12),
    } as const,
    vdPhotoUploadText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    vdSaveBtn: {
        marginTop: verticalScale(2),
        borderRadius: moderateScale(11),
        overflow: 'hidden',
    },
    vdSaveBtnSolid: {
        ...buttonSystem.primary,
        borderRadius: moderateScale(11),
        alignItems: 'center',
        backgroundColor: colors.primary,
        shadowColor: colors.primary,
        shadowOpacity: 0.22,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 4,
    },
    vdSaveBtnGrad: {
        minHeight: verticalScale(38),
        paddingVertical: verticalScale(6),
        alignItems: 'center',
    } as const,
    vdSaveBtnText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(12.5),
        color: colors.card,
    },
    vdAddVaxSaveBtnSpacing: {
        marginTop: verticalScale(8),
    },

    // Remind chips
    vdRemindRow: {
        flexDirection: 'row',
        gap: scale(8),
    } as const,
    vdRemindChip: {
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(5),
        minHeight: verticalScale(36),
        borderRadius: moderateScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vdRemindChipActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    vdRemindChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text2,
    },
    vdRemindChipTextActive: {
        color: colors.text,
    },
    vdRemindSwitchRow: {
        minHeight: verticalScale(36),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    vdRemindSwitchCard: {
        minHeight: verticalScale(52),
        borderRadius: moderateScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: scale(10),
    },
    vdRemindSwitchContent: {
        flex: 1,
        paddingRight: scale(8),
    },
    vdRemindSwitchText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text2,
    },
    vdRemindSwitchHint: {
        marginTop: verticalScale(1),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10.8),
        color: colors.text3,
    },

    // ═══════════════════════════════════
    //  MEDICINE: Today card extras
    // ═══════════════════════════════════
    medTodayWarn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        marginTop: verticalScale(5),
    },
    medTodayWarnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 0.3,
    },
    medNextDose: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        marginTop: verticalScale(4),
    },
    medNextDoseText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.6)',
    },
    medNextDoseTime: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.9)',
    },

    // Medicine row time chips
    medTimeChips: {
        flexDirection: 'row',
        gap: scale(4),
        marginTop: verticalScale(3),
    },
    medTimeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
        paddingHorizontal: scale(6),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        backgroundColor: colors.bg,
    },
    medTimeChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(9),
        color: colors.text2,
    },

    // ═══════════════════════════════════
    //  RECORD DETAIL
    // ═══════════════════════════════════
    rdHero: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(20),
    },
    rdHeroTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        marginBottom: verticalScale(14),
    },
    rdHeroBack: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdHeroTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(19),
        color: colors.card,
        letterSpacing: -0.2,
        flex: 1,
    },
    rdMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(16),
    },
    rdMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    rdMetaIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(10),
        backgroundColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdMetaLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.6)',
    },
    rdMetaValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.card,
    },
    rdMetaDivider: {
        width: 1,
        height: verticalScale(30),
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    rdTabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: scale(16),
    },
    rdTab: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(8),
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    rdTabActive: {
        borderBottomColor: colors.primary,
    },
    rdTabText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text3,
        textAlign: 'center',
    },
    rdTabTextActive: {
        color: colors.primary,
        fontFamily: typography.font.bold,
    },
    rdInfoCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        ...shadows.card,
    },
    rdInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
    },
    rdInfoRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    rdInfoDiag: {
        borderLeftWidth: 0,
        borderLeftColor: 'transparent',
    },
    rdInfoIcon: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdInfoLabel: {
        ...formSystem.fieldLabel,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        marginBottom: verticalScale(4),
        color: colors.text3,
    },
    rdInfoValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        lineHeight: verticalScale(18),
    },
    rdInfoEmpty: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        fontStyle: 'italic',
    },
    rdInfoChipWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
        marginTop: verticalScale(6),
    },
    rdInfoChip: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(5),
        borderRadius: moderateScale(999),
        backgroundColor: colors.bg,
        borderWidth: 1,
        borderColor: colors.border,
    },
    rdInfoChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text2,
    },
    rdInfoRowPressed: {
        backgroundColor: colors.bg,
    },
    rdEditorSheet: {
        paddingBottom: verticalScale(20),
    },
    rdEditorField: {
        marginBottom: verticalScale(6),
    },
    rdEditorLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(8),
    },
    rdEditorInput: {
        ...inputSystem.textarea,
        minHeight: verticalScale(124),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text,
    },
    rdEditorHint: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10.5),
        color: colors.text3,
        lineHeight: verticalScale(14),
        marginTop: verticalScale(6),
    },
    rdEmptyWrap: {
        alignItems: 'center',
        padding: scale(20),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        backgroundColor: colors.bg,
    },
    rdEmptyTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(6),
    },
    rdEmptySub: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    rdAttachGrid: {
        flexDirection: 'row',
        gap: scale(10),
        marginBottom: verticalScale(12),
    },
    rdAttachBtn: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(12),
        backgroundColor: colors.card,
    },
    rdAttachIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdAttachLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11.5),
        marginTop: verticalScale(5),
    },
    rdAttachSub: {
        fontSize: scaleFont(9.5),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdAttachList: {
        gap: verticalScale(10),
        marginTop: verticalScale(8),
    },
    vdAttachListHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(2),
    },
    vdAttachListHeaderText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11.5),
        color: colors.text2,
    },
    vdAttachListCount: {
        minWidth: moderateScale(22),
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(999),
        backgroundColor: colors.primaryBg,
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.primary,
        textAlign: 'center',
    },
    vdAttachItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(12),
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    vdAttachThumb: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(10),
        backgroundColor: colors.bg,
    },
    vdAttachFileThumb: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(10),
        backgroundColor: '#F3F0FF',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vdAttachMeta: {
        flex: 1,
        minWidth: 0,
    },
    vdAttachName: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11.5),
        color: colors.text,
    },
    vdAttachType: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    vdAttachRemoveBtn: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdFollowHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(12),
    },
    rdFollowBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(13),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(7),
        ...shadows.card,
    },
    rdFollowBtnActive: {
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    rdFollowBtnText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11.5),
        color: colors.text2,
    },
    fuSheetContainer: {
        height: '94%',
        overflow: 'hidden',
    },
    fuSheetBack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    fuSheetHeaderTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.primary,
        marginLeft: scale(4),
    },
    fuSheetHeaderAction: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.primary,
    },
    fuSheetBody: {
        padding: scale(20),
        paddingBottom: verticalScale(100),
    },
    fuSheetSection: {
        marginBottom: verticalScale(22),
    },
    fuRequired: {
        color: colors.danger,
    },
    fuSheetField: {
        ...inputSystem.fieldIcon,
        minHeight: verticalScale(40),
        paddingHorizontal: scale(12),
        borderRadius: moderateScale(12),
    },
    fuSheetFieldIcon: {
        marginRight: scale(2),
    },
    fuSheetText: {
        ...inputSystem.textStrong,
        fontSize: scaleFont(11.5),
        color: colors.text,
    },
    fuSheetSelect: {
        ...inputSystem.selectOption,
        minHeight: verticalScale(40),
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(12),
    },
    fuSheetSelectText: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11.5),
        color: colors.text,
    },
    fuSheetSelectPlaceholder: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11.5),
        color: colors.text3,
    },
    fuSheetTextarea: {
        ...inputSystem.textarea,
        flexDirection: 'row',
        alignItems: 'flex-start',
        minHeight: verticalScale(76),
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(10),
    },
    fuSheetTextareaInput: {
        ...inputSystem.textStrong,
        fontSize: scaleFont(11.5),
        color: colors.text,
        height: '100%',
        textAlignVertical: 'top',
    },
    fuReminderStaticCard: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        padding: scale(14),
        backgroundColor: colors.card,
    },
    fuReminderRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    fuReminderCopy: {
        flex: 1,
    },
    fuReminderIcon: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(10),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuReminderTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text,
    },
    fuReminderText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text2,
        marginTop: verticalScale(2),
        lineHeight: verticalScale(16),
    },
    fuReminderSwitch: {
        width: moderateScale(44),
        height: moderateScale(24),
        borderRadius: moderateScale(999),
        backgroundColor: colors.border,
        padding: 2,
        justifyContent: 'center',
    },
    fuReminderSwitchActive: {
        backgroundColor: colors.success,
    },
    fuReminderSwitchThumb: {
        width: moderateScale(20),
        height: moderateScale(20),
        borderRadius: moderateScale(999),
        backgroundColor: colors.card,
        alignSelf: 'flex-start',
    },
    fuReminderSwitchThumbActive: {
        alignSelf: 'flex-end',
    },
    fuSheetFooter: {
        flexDirection: 'row',
        padding: scale(20),
        backgroundColor: colors.card,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        gap: scale(12),
    },
    fuSheetCancelBtn: {
        ...buttonSystem.outline,
        flex: 1,
        minHeight: verticalScale(40),
        borderRadius: moderateScale(12),
    },
    fuSheetCancelText: {
        ...buttonSystem.textOutline,
        color: colors.text,
    },
    fuSheetSaveBtn: {
        ...buttonSystem.primary,
        flex: 2,
        minHeight: verticalScale(40),
        borderRadius: moderateScale(12),
        backgroundColor: colors.primary,
    },
    fuSheetSaveText: {
        ...buttonSystem.textPrimary,
    },

    // Follow-up add card
    fuCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        padding: scale(16),
        marginBottom: verticalScale(12),
        ...shadows.card,
    },
    fuCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        marginBottom: verticalScale(14),
    },
    fuCardIcon: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(9),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuCardTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12.5),
        color: colors.text,
    },
    fuField: {
        marginBottom: verticalScale(10),
    },
    fuReminderInlineRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 0,
    },
    fuReminderInlineCopy: {
        flex: 1,
        paddingRight: scale(12),
    },
    fuReminderInlineText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        lineHeight: verticalScale(17),
    },
    fuLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(5),
    },
    fuInput: {
        ...inputSystem.fieldSoft,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
        fontSize: scaleFont(11.5),
        color: colors.text,
        textAlignVertical: 'center',
    },
    fuBtnRow: {
        flexDirection: 'row',
        gap: scale(8),
        marginTop: verticalScale(16),
    },
    fuCancelBtn: {
        flex: 1,
        ...buttonSystem.outline,
        borderRadius: moderateScale(11),
        backgroundColor: colors.bg,
        alignItems: 'center',
    },
    fuCancelText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12.5),
        color: colors.text2,
    },
    fuSaveBtn: {
        flex: 2,
        ...buttonSystem.primary,
        borderRadius: moderateScale(11),
        backgroundColor: colors.primary,
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.25,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    fuSaveText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12.5),
        color: colors.card,
    },
    // Saved follow-up item
    fuItem: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        padding: scale(14),
        marginBottom: verticalScale(10),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    fuItemIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuItemBody: {
        flex: 1,
    },
    fuItemDate: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    fuItemPurpose: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    fuItemDelete: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ═══════════════════════════════════
    //  ADD RECORD FORM
    // ═══════════════════════════════════
    arGroup: {
        marginBottom: verticalScale(12),
    },
    arLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(6),
    },
    arSectionTitle: {
        ...formSystem.sectionTitle,
        marginBottom: verticalScale(16),
    },
    arInput: {
        ...inputSystem.field,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text,
        textAlignVertical: 'center',
    },
    arInputIcon: {
        ...inputSystem.fieldIcon,
        gap: scale(8),
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(5),
    },
    arInputBare: {
        ...inputSystem.text,
        fontSize: scaleFont(11.5),
        textAlignVertical: 'center',
    },
    arTextarea: {
        ...inputSystem.textarea,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(8),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text,
        minHeight: verticalScale(64),
    },
    arRow: {
        flexDirection: 'row',
        gap: scale(12),
    },
    arSelectWrap: {
        ...inputSystem.selectOption,
        paddingHorizontal: scale(12),
    },
    arSelectText: {
        flex: 1,
        fontSize: scaleFont(11.5),
        color: colors.text,
    },
    arSelectPlaceholder: {
        flex: 1,
        fontSize: scaleFont(11.5),
        color: colors.text3,
    },
    arDivider: {
        height: 1.5,
        backgroundColor: colors.border,
        borderRadius: moderateScale(2),
        marginTop: verticalScale(20),
        marginBottom: verticalScale(16),
    },
    arSaveWrap: {
        backgroundColor: colors.bg,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(24),
        paddingTop: verticalScale(10),
    },
    arSaveInlineWrap: {
        marginTop: verticalScale(20),
        marginBottom: verticalScale(10),
    },
    arSaveBtn: {
        ...buttonSystem.primary,
        backgroundColor: colors.primary,
        minHeight: verticalScale(42),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
        width: '100%',
    },
    arSaveBtnText: {
        ...buttonSystem.textPrimary,
        fontSize: scaleFont(14),
        color: '#fff',
        letterSpacing: 0.1,
    },

    // ═══════════════════════════════════
    //  NOTIFICATION SCREEN
    // ═══════════════════════════════════
    notiPage: {
        backgroundColor: colors.bg,
    },
    notiTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(6),
        gap: scale(12),
    },
    notiTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
        letterSpacing: -0.4,
    },
    notiUnreadCount: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: '#8DAE9D',
        marginTop: verticalScale(3),
    },
    notiGroupLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(10),
    },
    notiItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        borderRadius: moderateScale(16),
        marginBottom: verticalScale(3),
    },
    notiItemUnread: {
        backgroundColor: colors.primaryBg,
        borderWidth: 1,
        borderColor: colors.primaryLight,
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
    },
    notiItemRead: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    notiIcon: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(1),
    },
    notiTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: scale(8),
        marginBottom: verticalScale(3),
    },
    notiItemTitle: {
        fontSize: scaleFont(13),
        fontWeight: '600',
        color: colors.text2,
        lineHeight: verticalScale(18),
        flex: 1,
    },
    notiTime: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    notiBody: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text3,
        lineHeight: verticalScale(17),
    },
    notiVaxChips: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(5),
        flexWrap: 'wrap',
        marginTop: verticalScale(3),
    },
    notiVaxChip: {
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(20),
        borderWidth: 1,
    },
    notiVaxChipText: {
        fontSize: scaleFont(10),
        fontWeight: '700',
    },
    notiVaxDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        marginTop: verticalScale(4),
    },
    notiVaxDateText: {
        fontSize: scaleFont(10),
        fontWeight: '600',
        color: colors.text3,
    },
    notiScrollContent: {
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(28),
        paddingTop: verticalScale(4),
    },
    notiCard: {
        backgroundColor: colors.card,
        borderRadius: moderateScale(18),
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        marginBottom: verticalScale(10),
        ...shadows.card,
    },
    notiCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: scale(10),
        minHeight: verticalScale(32),
    },
    notiCardHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        flex: 1,
    },
    notiHeaderMeta: {
        flex: 1,
    },
    notiHeaderType: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        textTransform: 'uppercase',
        letterSpacing: 0.7,
        marginBottom: verticalScale(2),
    },
    notiTimeWrap: {
        alignItems: 'flex-end',
        paddingTop: verticalScale(2),
    },
    notiSummary: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
        lineHeight: verticalScale(18),
        marginBottom: verticalScale(2),
    },
    notiInfoChip: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(999),
        borderWidth: 0,
    },
    notiInfoChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
    },
    notiChipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: scale(8),
        marginTop: verticalScale(10),
    },
    notiBadge: {
        position: 'absolute',
        top: verticalScale(4),
        right: scale(4),
        width: moderateScale(7),
        height: moderateScale(7),
        borderRadius: moderateScale(4),
        backgroundColor: colors.danger,
        borderWidth: 1.5,
        borderColor: colors.card,
    },
    notiEmptyState: {
        marginTop: verticalScale(24),
        borderRadius: moderateScale(18),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(18),
        alignItems: 'center',
    },
    notiEmptyTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    notiEmptyDesc: {
        marginTop: verticalScale(6),
        textAlign: 'center',
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11.5),
        color: colors.text3,
        lineHeight: verticalScale(16),
    },
});
