import { StyleSheet } from 'react-native';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    statusTopSpacer: { height: 4 },
    topbar: {
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 4,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: 24,
        color: colors.text,
    },
    topbarRight: {
        flexDirection: 'row',
        gap: 8,
    },
    member: {
        marginHorizontal: 20,
        marginTop: 14,
        borderRadius: 16,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingVertical: 11,
        paddingHorizontal: 14,
        flexDirection: 'row',
        alignItems: 'center',
        ...shadows.card,
    },
    mAvatar: {
        width: 38,
        height: 38,
        borderRadius: 19,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 11,
    },
    mAvatarText: {
        fontFamily: typography.font.black,
        fontSize: 13,
        color: colors.primary,
    },
    mDot: {
        position: 'absolute',
        bottom: 1,
        right: 1,
        width: 10,
        height: 10,
        borderRadius: 5,
        backgroundColor: colors.cHealth,
        borderWidth: 2,
        borderColor: colors.card,
    },
    mInfo: { flex: 1 },
    mName: {
        fontFamily: typography.font.bold,
        fontSize: 14,
        color: colors.text,
    },
    mRole: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },
    bmiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingTop: 16,
        paddingBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    bmiIcon: {
        width: 44,
        height: 44,
        borderRadius: 13,
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 14,
    },
    bmiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text3,
        marginBottom: 4,
    },
    bmiValueRow: { flexDirection: 'row', alignItems: 'flex-end' },
    bmiValue: {
        fontFamily: typography.font.black,
        fontSize: 28,
        color: colors.text,
        letterSpacing: -1,
    },
    bmiUnit: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginLeft: 5,
    },
    bmiSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 3,
    },
    bmiBadge: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.cHealth,
        backgroundColor: colors.cHealthBg,
        paddingHorizontal: 13,
        paddingVertical: 6,
        borderRadius: 20,
    },
    bmiGaugeWrap: {
        paddingHorizontal: 18,
        paddingVertical: 14,
    },
    bmiGaugeTrack: {
        height: 7,
        borderRadius: 8,
        backgroundColor: colors.border,
        justifyContent: 'center',
    },
    bmiGaugeThumb: {
        position: 'absolute',
        left: '52%',
        width: 13,
        height: 13,
        borderRadius: 7,
        backgroundColor: colors.card,
        borderWidth: 2.5,
        borderColor: colors.primary,
    },
    bmiGaugeLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 7,
    },
    bmiGaugeLabel: { fontFamily: typography.font.semiBold, fontSize: 10 },

    // ── Health Info Rows ──
    hiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingVertical: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: 12,
    },
    hiRowLast: {
        borderBottomWidth: 0,
    },
    hiIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    hiBody: { flex: 1 },
    hiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text3,
        marginBottom: 4,
    },
    hiVal: {
        fontFamily: typography.font.black,
        fontSize: 17,
    },
    hiTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
    },
    hiTag: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 8,
    },
    hiEmpty: {
        fontSize: 12,
        fontStyle: 'italic',
        color: colors.text3,
    },

    // ── Visit Rows ──
    visitRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        paddingHorizontal: 18,
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    visitIcon: {
        width: 38,
        height: 38,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
        marginTop: 1,
    },
    visitBody: { flex: 1 },
    visitTitle: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    visitSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 3,
    },
    visitTag: {
        marginTop: 5,
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        alignSelf: 'flex-start',
    },
    visitDate: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: colors.text2,
        backgroundColor: '#F1F5F9',
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 8,
        overflow: 'hidden',
        marginTop: 2,
    },

    // ── Vaccine / Donut ──
    vpctRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingVertical: 16,
    },
    donutWrap: {
        width: 60,
        height: 60,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 16,
    },
    donutPercent: {
        fontFamily: typography.font.black,
        fontSize: 13,
        color: '#D97706',
    },
    vpctTitle: {
        fontFamily: typography.font.black,
        fontSize: 15,
        color: colors.text,
    },
    vpctSub: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text3,
        marginTop: 2,
    },
    vRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 18,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    vIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    vBody: { flex: 1 },
    vName: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    vSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },
    vDate: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text3,
    },

    // ── Tips ──
    tipsRow: {
        paddingHorizontal: 20,
        paddingTop: 4,
    },
    tipCard: {
        width: 144,
        borderRadius: 16,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        padding: 14,
        marginRight: 10,
        ...shadows.card,
    },
    tipEmoji: { fontSize: 22, marginBottom: 8 },
    tipTitle: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.text,
        marginBottom: 3,
    },
    tipSub: {
        fontFamily: typography.font.regular,
        fontSize: 10,
        color: colors.text3,
        lineHeight: 14,
    },

    // ── Bottom Sheet: Blood Type Grid ──
    btGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
    },
    btOpt: {
        width: '23%' as unknown as number,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        paddingVertical: 12,
        alignItems: 'center',
    },
    btOptSel: {
        borderColor: '#E11D48',
        backgroundColor: '#FFF1F2',
    },
    btOptText: {
        fontFamily: typography.font.black,
        fontSize: 15,
        color: colors.text2,
    },
    btOptTextSel: {
        color: '#E11D48',
    },

    // ── Bottom Sheet: Tag Input ──
    tagInputWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        gap: 6,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        minHeight: 44,
    },
    tagChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        backgroundColor: '#FFFBEB',
        paddingVertical: 3,
        paddingLeft: 10,
        paddingRight: 8,
        borderRadius: 8,
    },
    tagChipText: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: '#D97706',
    },
    tagChipX: {
        fontSize: 14,
        color: '#D97706',
        opacity: 0.6,
        paddingHorizontal: 2,
    },
    tagInput: {
        flex: 1,
        minWidth: 100,
        fontFamily: typography.font.regular,
        fontSize: 13,
        color: colors.text,
        padding: 0,
    },
    tagHint: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 8,
    },

    // ═══════════════════════════════════
    //  SUB-SCREEN: Shared topbar
    // ═══════════════════════════════════
    subTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 10,
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        gap: 10,
    },
    subBackBtn: {
        width: 36,
        height: 36,
        borderRadius: 18,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    subTopbarTitle: {
        flex: 1,
        fontFamily: typography.font.black,
        fontSize: 18,
        color: colors.text,
        letterSpacing: -0.3,
    },
    subAddBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        backgroundColor: colors.primary,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    subAddBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: '#fff',
    },

    // ═══════════════════════════════════
    //  RECORDS SCREEN
    // ═══════════════════════════════════
    searchFilterWrap: {
        backgroundColor: colors.card,
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    searchWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    searchInput: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
        padding: 0,
    },
    filterRow: {
        flexDirection: 'row',
        gap: 6,
        marginTop: 10,
    },
    filterChip: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingVertical: 8,
        borderRadius: 10,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    filterChipActive: {
        backgroundColor: colors.primaryBg,
        borderColor: colors.primary,
    },
    filterChipText: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text3,
    },
    filterChipTextActive: {
        color: colors.primary,
    },

    // Timeline items
    recYearHdr: {
        fontFamily: typography.font.black,
        fontSize: 18,
        color: colors.text,
        paddingHorizontal: 20,
        paddingTop: 20,
        paddingBottom: 6,
        letterSpacing: -0.3,
    },
    recMonthHdr: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.text2,
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 8,
    },
    recItem: {
        flexDirection: 'row',
        paddingLeft: 20,
        paddingRight: 16,
        marginBottom: 2,
    },
    recTimeline: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        marginRight: 12,
        width: 56,
    },
    recDateCol: {
        alignItems: 'center',
        width: 28,
    },
    recDay: {
        fontFamily: typography.font.black,
        fontSize: 18,
        color: colors.text,
        lineHeight: 22,
    },
    recMon: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: colors.text3,
        marginTop: 1,
    },
    recDotCol: {
        alignItems: 'center',
        marginLeft: 8,
        paddingTop: 6,
    },
    recDot: {
        width: 10,
        height: 10,
        borderRadius: 5,
    },
    recLine: {
        width: 2,
        flex: 1,
        backgroundColor: colors.border,
        marginTop: 4,
        minHeight: 60,
    },
    recCard: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 10,
        ...shadows.card,
    },
    recCardTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: 14,
        gap: 12,
    },
    recIconWrap: {
        width: 38,
        height: 38,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
    },
    recTitle: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    recSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 3,
    },
    recDiagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 4,
        gap: 4,
    },
    recDiagDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
        backgroundColor: colors.text3,
    },
    recDiagText: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        flex: 1,
    },
    recCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 14,
        paddingVertical: 10,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    recTag: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 6,
        overflow: 'hidden',
    },
    recMetaRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
    },
    recMetaText: {
        fontFamily: typography.font.medium,
        fontSize: 10,
        color: colors.text3,
    },
    recEmpty: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 64,
        paddingHorizontal: 32,
    },
    recEmptyIcon: {
        width: 72,
        height: 72,
        borderRadius: 22,
        backgroundColor: colors.primaryBg,
        borderWidth: 2,
        borderColor: '#BFDBFE',
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 16,
    },
    recEmptyTitle: {
        fontFamily: typography.font.black,
        fontSize: 15,
        color: colors.text,
        marginBottom: 6,
    },
    recEmptySub: {
        fontFamily: typography.font.regular,
        fontSize: 13,
        color: colors.text3,
    },

    // ═══════════════════════════════════
    //  VACCINE SCREEN
    // ═══════════════════════════════════
    vaxHero: {
        borderRadius: 18,
        padding: 16,
        marginBottom: 16,
        overflow: 'hidden',
    },
    vaxHeroContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
    },
    vaxDonut: {
        width: 64,
        height: 64,
    },
    vaxDonutTrack: {
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 5,
        borderColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDonutFill: {
        position: 'absolute',
        width: 64,
        height: 64,
        borderRadius: 32,
        borderWidth: 5,
        borderColor: 'transparent',
        transform: [{ rotate: '-90deg' }],
    },
    vaxDonutText: {
        fontFamily: typography.font.black,
        fontSize: 14,
        color: '#fff',
    },
    vaxHeroSup: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: 'rgba(255,255,255,0.7)',
        marginBottom: 2,
    },
    vaxHeroNum: {
        fontFamily: typography.font.black,
        fontSize: 22,
        color: '#fff',
        lineHeight: 26,
        letterSpacing: -0.5,
    },
    vaxHeroNumSub: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        opacity: 0.7,
    },
    vaxHeroPending: {
        marginTop: 5,
        fontFamily: typography.font.bold,
        fontSize: 9,
        color: 'rgba(255,255,255,0.55)',
        letterSpacing: 0.5,
    },
    vaxProgressTrack: {
        height: 5,
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderRadius: 99,
        overflow: 'hidden',
        marginTop: 12,
    },
    vaxProgressFill: {
        height: '100%',
        backgroundColor: '#fff',
        borderRadius: 99,
    },

    // Section headers
    vaxSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    vaxSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    vaxSecDot: {
        width: 6,
        height: 6,
        borderRadius: 3,
    },
    vaxSecLabel: {
        fontFamily: typography.font.black,
        fontSize: 10,
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.7,
    },
    vaxSecCount: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 20,
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxListCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 16,
        overflow: 'hidden',
        marginBottom: 14,
    },

    // Vaccine rows
    vaxRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 11,
        paddingHorizontal: 14,
        paddingVertical: 13,
    },
    vaxRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxRowIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxRowName: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    vaxRowSub: {
        fontFamily: typography.font.medium,
        fontSize: 11,
        color: colors.text3,
    },
    vaxRowMeta: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        marginTop: 3,
    },
    vaxChip: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 20,
        borderWidth: 1,
        overflow: 'hidden',
    },
    vaxChipDone: {
        backgroundColor: '#F0FDF4',
        color: '#16A34A',
        borderColor: '#BBF7D0',
    },
    vaxChipSoon: {
        backgroundColor: '#FFFBEB',
        color: '#D97706',
        borderColor: '#FDE68A',
    },
    vaxChipPending: {
        backgroundColor: '#FFF1F2',
        color: '#E11D48',
        borderColor: '#FECDD3',
    },
    vaxChipScheduled: {
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        borderColor: '#BFDBFE',
    },
    vaxChipLabel: {
        fontSize: 10,
        color: colors.text3,
        fontWeight: '500',
    },

    // Add button & note
    vaxAddBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 13,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        borderRadius: 14,
    },
    vaxAddBtnText: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.text2,
    },
    vaxNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        paddingHorizontal: 13,
        paddingVertical: 11,
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 12,
        marginTop: 12,
    },
    vaxNoteText: {
        flex: 1,
        fontSize: 11,
        fontWeight: '500',
        color: colors.primary,
        lineHeight: 17,
    },

    // ═══════════════════════════════════
    //  MEDICINE SCREEN
    // ═══════════════════════════════════
    medTodayCard: {
        borderRadius: 20,
        padding: 16,
        marginBottom: 16,
        overflow: 'hidden',
    },
    medTodaySup: {
        fontSize: 11,
        fontWeight: '700',
        color: 'rgba(255,255,255,0.7)',
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 6,
    },
    medTodayRow: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        marginBottom: 10,
    },
    medTodayNum: {
        fontSize: 22,
        fontWeight: '800',
        color: '#fff',
        lineHeight: 26,
        letterSpacing: -0.4,
    },
    medTodayNumSub: {
        fontSize: 13,
        fontWeight: '600',
        opacity: 0.7,
    },
    medTodayPct: {
        fontSize: 20,
        fontWeight: '800',
        color: 'rgba(255,255,255,0.85)',
    },
    medProgressTrack: {
        height: 7,
        backgroundColor: 'rgba(255,255,255,0.18)',
        borderRadius: 99,
        overflow: 'hidden',
    },
    medProgressFill: {
        height: '100%',
        backgroundColor: '#fff',
        borderRadius: 99,
    },
    medSecRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 8,
        paddingHorizontal: 2,
    },
    medSecLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    medSecLabel: {
        fontSize: 11,
        fontWeight: '800',
        color: colors.text,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
    },

    // Medicine rows
    medRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 14,
        paddingVertical: 13,
    },
    medRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    medRowIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
    },
    medRowName: {
        fontSize: 13,
        fontWeight: '700',
        color: colors.text,
    },
    medRowSub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },
    medDaysLeftBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 20,
        backgroundColor: '#FFFBEB',
        borderWidth: 1,
        borderColor: '#FDE68A',
        marginRight: 4,
    },
    medDaysLeftText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#D97706',
    },
    medNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 9,
        paddingHorizontal: 13,
        paddingVertical: 11,
        backgroundColor: '#FFFBEB',
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: 12,
        marginTop: 4,
    },
    medNoteText: {
        flex: 1,
        fontSize: 11,
        fontWeight: '500',
        color: '#92400E',
        lineHeight: 17,
    },

    // Detail sheet
    medSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        maxHeight: '90%',
    },
    medDetailHeader: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: 10,
    },
    medDetailName: {
        fontSize: 17,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.2,
    },
    medDetailSub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    medDetailBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        borderWidth: 1,
    },

    // Pill widget
    medPillWidget: {
        backgroundColor: colors.bg,
        borderRadius: 16,
        padding: 14,
        marginHorizontal: 20,
        marginTop: 14,
        marginBottom: 14,
    },
    medPillRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        marginBottom: 10,
    },
    medPillLabel: {
        fontSize: 10,
        fontWeight: '700',
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 3,
    },
    medPillNum: {
        fontSize: 26,
        fontWeight: '800',
        color: '#0D9488',
        lineHeight: 30,
    },
    medPillTotal: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.text3,
    },
    medPillTrack: {
        height: 7,
        backgroundColor: '#E4EAF2',
        borderRadius: 99,
        overflow: 'hidden',
    },
    medPillFill: {
        height: '100%',
        borderRadius: 99,
    },
    medPillPct: {
        fontSize: 10,
        fontWeight: '700',
        color: colors.text3,
        textAlign: 'right',
        marginTop: 5,
    },

    // Info rows
    medInfoCard: {
        backgroundColor: colors.bg,
        borderRadius: 14,
        overflow: 'hidden',
        marginHorizontal: 20,
        marginBottom: 14,
    },
    medInfoRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 13,
        paddingVertical: 10,
    },
    medInfoRowBorder: {
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    medInfoLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: colors.text2,
    },
    medInfoValue: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text,
        textAlign: 'right',
    },
    medDetailNote: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 8,
        marginHorizontal: 20,
        paddingHorizontal: 13,
        paddingVertical: 10,
        backgroundColor: colors.bg,
        borderRadius: 12,
    },
    medDetailNoteText: {
        flex: 1,
        fontSize: 12,
        color: colors.text2,
        lineHeight: 18,
    },

    // Dose dots on today card
    medDoseDots: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 5,
        marginTop: 8,
        marginBottom: 10,
    },
    medDoseDot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        borderRadius: 99,
        paddingVertical: 3,
        paddingLeft: 5,
        paddingRight: 8,
    },
    medDoseDotCircle: {
        width: 7,
        height: 7,
        borderRadius: 4,
    },
    medDoseDotText: {
        fontSize: 9,
        fontWeight: '700',
    },

    // Detail full-screen header
    mdHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: 12,
    },
    mdEditBtn: {
        width: 32,
        height: 32,
        borderRadius: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // Edit form
    mdEditForm: {
        gap: 11,
    },
    mdFieldLabel: {
        fontSize: 11,
        fontWeight: '700',
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: 5,
    },
    mdInput: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        paddingHorizontal: 13,
        paddingVertical: 10,
        fontSize: 13,
        fontWeight: '600',
        color: colors.text,
    },
    mdRowGrid: {
        flexDirection: 'row',
        gap: 10,
    },
    mdFreqRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 6,
    },
    mdFreqChip: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    mdFreqChipActive: {
        borderColor: '#0D9488',
        backgroundColor: '#F0FDFA',
    },
    mdFreqChipText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text2,
    },
    mdFreqChipTextActive: {
        color: '#0D9488',
    },
    mdMealChip: {
        paddingHorizontal: 10,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },

    // Time slot rows
    mdSlotRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 6,
    },
    mdSlotChip: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
        minWidth: 80,
        alignItems: 'center',
    },
    mdSlotChipActive: {
        borderColor: '#0D9488',
        backgroundColor: '#F0FDFA',
    },
    mdSlotChipText: {
        fontSize: 12,
        fontWeight: '700',
        color: colors.text3,
    },
    mdSlotChipTextActive: {
        color: '#0D9488',
    },
    mdSlotTime: {
        flex: 1,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 8,
        fontSize: 13,
        fontWeight: '600',
        color: colors.text3,
    },
    mdSlotTimeActive: {
        borderColor: '#99F6E4',
        color: colors.text,
    },

    // Save / Delete buttons
    mdSaveBtn: {
        borderRadius: 14,
        overflow: 'hidden',
        marginTop: 2,
    },
    mdSaveBtnInner: {
        paddingVertical: 13,
        alignItems: 'center',
    },
    mdSaveBtnText: {
        fontSize: 14,
        fontWeight: '800',
        color: '#fff',
    },
    mdDeleteBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        paddingVertical: 13,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: '#FECDD3',
        backgroundColor: '#FFF1F2',
    },
    mdDeleteText: {
        fontSize: 13,
        fontWeight: '700',
        color: '#E11D48',
    },

    // Choose sheet
    mdChooseOption: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        padding: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 16,
    },
    mdChooseIcon: {
        width: 42,
        height: 42,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdChooseTitle: {
        fontSize: 14,
        fontWeight: '700',
        color: colors.text,
    },
    mdChooseSub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    mdAiBadge: {
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 20,
        backgroundColor: '#EFF6FF',
        borderWidth: 1,
        borderColor: '#93C5FD',
    },
    mdAiBadgeText: {
        fontSize: 9,
        fontWeight: '800',
        color: '#2563EB',
    },

    // Add sheet header
    mdAddHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 20,
        paddingBottom: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mdAddBackBtn: {
        width: 30,
        height: 30,
        borderRadius: 15,
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mdAddTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: colors.text,
    },

    // ═══════════════════════════════════
    //  RECORDS: Context menu
    // ═══════════════════════════════════
    recMoreBtn: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    ctxMenu: {
        position: 'absolute',
        right: 0,
        top: 30,
        width: 145,
        backgroundColor: colors.card,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        zIndex: 50,
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 4 },
    },
    ctxItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 11,
    },
    ctxItemText: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.text,
    },
    ctxDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    ctxItemDel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        paddingHorizontal: 14,
        paddingVertical: 11,
    },
    ctxItemDelText: {
        fontSize: 13,
        fontWeight: '600',
        color: '#E11D48',
    },

    // ═══════════════════════════════════
    //  RECORDS: Specialty picker modal
    // ═══════════════════════════════════
    specGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 8,
        paddingHorizontal: 20,
        paddingTop: 16,
        paddingBottom: 24,
    },
    specItem: {
        width: '30%' as unknown as number,
        alignItems: 'center',
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    specItemActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    specIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        marginBottom: 6,
    },
    specLabel: {
        fontSize: 11,
        fontWeight: '600',
        color: colors.text2,
    },
    specLabelActive: {
        color: colors.primary,
        fontWeight: '700',
    },

    // ═══════════════════════════════════
    //  VACCINE: Dose dots
    // ═══════════════════════════════════
    vaxDots: {
        flexDirection: 'row',
        gap: 4,
        marginTop: 5,
    },
    vaxDotBar: {
        width: 20,
        height: 3,
        borderRadius: 3,
    },

    // ═══════════════════════════════════
    //  VACCINE: Next shot banner
    // ═══════════════════════════════════
    vaxNextShot: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: '#FFFBEB',
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: 14,
        marginBottom: 14,
    },
    vaxNextShotIcon: {
        width: 32,
        height: 32,
        borderRadius: 9,
        backgroundColor: 'rgba(217,119,6,0.12)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxNextShotBody: {
        flex: 1,
    },
    vaxNextShotLabel: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        color: '#D97706',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    vaxNextShotName: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
        marginTop: 1,
    },
    vaxNextShotDate: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: '#D97706',
    },

    // ═══════════════════════════════════
    //  VACCINE: Detail bottom sheet
    // ═══════════════════════════════════
    vaxSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: 24,
        borderTopRightRadius: 24,
        paddingBottom: 32,
        maxHeight: '85%',
    },
    vaxDetailHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 4,
        paddingBottom: 14,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        gap: 10,
    },
    vaxDetailName: {
        fontFamily: typography.font.black,
        fontSize: 17,
        color: colors.text,
        letterSpacing: -0.2,
    },
    vaxDetailAbbr: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    vaxDetailBadge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        borderWidth: 1,
    },
    vaxDoseRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 20,
        paddingVertical: 13,
    },
    vaxDoseRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vaxDoseNum: {
        width: 32,
        height: 32,
        borderRadius: 16,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaxDoseNumText: {
        fontFamily: typography.font.black,
        fontSize: 13,
    },
    vaxDoseBody: { flex: 1 },
    vaxDoseLabel: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    vaxDoseSub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },
    vaxDoseStatus: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 20,
        overflow: 'hidden',
    },

    // ═══════════════════════════════════
    //  VACCINE ROW: scheduled date line
    // ═══════════════════════════════════
    vaxRowSchedLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 3,
    } as const,
    vaxRowSchedText: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: colors.primary,
    },

    // ═══════════════════════════════════
    //  VACCINE DETAIL – full screen
    // ═══════════════════════════════════
    vdSummary: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 16,
        paddingVertical: 12,
        marginBottom: 16,
    } as const,
    vdSummaryLabel: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
        marginBottom: 3,
    } as const,
    vdSummaryProgress: {
        fontFamily: typography.font.black,
        fontSize: 18,
        color: colors.text,
        letterSpacing: -0.3,
    },
    vdSummarySub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    vdStatusBadge: {
        paddingHorizontal: 12,
        paddingVertical: 5,
        borderRadius: 20,
        borderWidth: 1,
    },
    vdStatusBadgeText: {
        fontFamily: typography.font.bold,
        fontSize: 11,
    },

    // Dose items (detail screen)
    vdDoseItem: {
        flexDirection: 'row',
        gap: 12,
        paddingHorizontal: 14,
        paddingVertical: 13,
    } as const,
    vdDoseItemBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    vdDoseDot: {
        width: 22,
        height: 22,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 2,
    } as const,
    vdDoseDotDone: {
        backgroundColor: '#F0FDF4',
        borderWidth: 1.5,
        borderColor: '#BBF7D0',
    },
    vdDoseDotScheduled: {
        backgroundColor: '#EFF6FF',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
    },
    vdDoseDotEmpty: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
    } as const,
    vdDoseLabel: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.4,
        marginBottom: 3,
    } as const,
    vdDoseVal: {
        fontFamily: typography.font.bold,
        fontSize: 14,
        color: colors.text,
    },
    vdDosePlace: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    vdDoseTag: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 20,
        borderWidth: 1,
        overflow: 'hidden',
        alignSelf: 'flex-start',
        marginTop: 4,
    } as const,
    vdDoseTagDone: {
        backgroundColor: '#F0FDF4',
        color: '#16A34A',
        borderColor: '#BBF7D0',
    },
    vdDoseTagScheduled: {
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        borderColor: '#BFDBFE',
    },

    // Schedule button (blue bg)
    vdSchedBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 13,
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 14,
        backgroundColor: colors.primaryBg,
    } as const,
    vdSchedBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.primary,
    },

    // Bottom sheet content
    vdSheetContent: {
        paddingHorizontal: 20,
        paddingBottom: 32,
    },
    vdSheetTitle: {
        fontFamily: typography.font.black,
        fontSize: 15,
        color: colors.text,
        marginBottom: 14,
    },
    vdFieldLabel: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
        marginBottom: 6,
    },
    vdFieldInput: {
        backgroundColor: colors.bg,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 11,
        fontFamily: typography.font.semiBold,
        fontSize: 14,
        color: colors.text,
    },
    vdPhotoUpload: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        padding: 14,
        borderWidth: 1.5,
        borderStyle: 'dashed',
        borderColor: colors.border,
        borderRadius: 12,
    } as const,
    vdPhotoUploadText: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.text3,
    },
    vdSaveBtn: {
        marginTop: 2,
        borderRadius: 14,
        overflow: 'hidden',
    },
    vdSaveBtnGrad: {
        paddingVertical: 13,
        alignItems: 'center',
    } as const,
    vdSaveBtnText: {
        fontFamily: typography.font.black,
        fontSize: 14,
        color: '#fff',
    },

    // Remind chips
    vdRemindRow: {
        flexDirection: 'row',
        gap: 8,
    } as const,
    vdRemindChip: {
        paddingHorizontal: 14,
        paddingVertical: 9,
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    vdRemindChipActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    vdRemindChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.text2,
    },
    vdRemindChipTextActive: {
        color: colors.primary,
    },

    // ═══════════════════════════════════
    //  MEDICINE: Today card extras
    // ═══════════════════════════════════
    medTodayWarn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 5,
    },
    medTodayWarnText: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        color: 'rgba(255,255,255,0.7)',
        letterSpacing: 0.3,
    },
    medNextDose: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        marginTop: 4,
    },
    medNextDoseText: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: 'rgba(255,255,255,0.6)',
    },
    medNextDoseTime: {
        fontFamily: typography.font.black,
        fontSize: 10,
        color: 'rgba(255,255,255,0.9)',
    },

    // Medicine row time chips
    medTimeChips: {
        flexDirection: 'row',
        gap: 4,
        marginTop: 3,
    },
    medTimeChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 3,
        paddingHorizontal: 6,
        paddingVertical: 2,
        borderRadius: 6,
        backgroundColor: colors.bg,
    },
    medTimeChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: 9,
        color: colors.text2,
    },

    // ═══════════════════════════════════
    //  RECORD DETAIL
    // ═══════════════════════════════════
    rdHero: {
        paddingHorizontal: 20,
        paddingTop: 14,
        paddingBottom: 20,
    },
    rdHeroTopRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 14,
    },
    rdHeroBack: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdHeroTitle: {
        fontFamily: typography.font.black,
        fontSize: 19,
        color: '#fff',
        letterSpacing: -0.2,
        flex: 1,
    },
    rdMetaRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 16,
    },
    rdMetaItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    rdMetaIcon: {
        width: 32,
        height: 32,
        borderRadius: 10,
        backgroundColor: 'rgba(255,255,255,0.18)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdMetaLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: 'rgba(255,255,255,0.6)',
    },
    rdMetaValue: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: '#fff',
    },
    rdMetaDivider: {
        width: 1,
        height: 30,
        backgroundColor: 'rgba(255,255,255,0.2)',
    },
    rdTabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: 20,
    },
    rdTab: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 4,
        marginRight: 20,
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    rdTabActive: {
        borderBottomColor: colors.primary,
    },
    rdTabText: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text3,
    },
    rdTabTextActive: {
        color: colors.primary,
        fontFamily: typography.font.bold,
    },
    rdInfoCard: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 18,
        overflow: 'hidden',
    },
    rdInfoRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        paddingHorizontal: 16,
        paddingVertical: 14,
    },
    rdInfoRowBorder: {
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    rdInfoDiag: {
        borderLeftWidth: 3,
        borderLeftColor: colors.primary,
    },
    rdInfoIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdInfoLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text3,
        marginBottom: 3,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    rdInfoValue: {
        fontFamily: typography.font.bold,
        fontSize: 14,
        color: colors.text,
        lineHeight: 20,
    },
    rdInfoEmpty: {
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text3,
        fontStyle: 'italic',
    },
    rdEmptyWrap: {
        alignItems: 'center',
        padding: 20,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        backgroundColor: colors.bg,
    },
    rdEmptyTitle: {
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.text3,
        marginTop: 6,
    },
    rdEmptySub: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 3,
    },
    rdAttachGrid: {
        flexDirection: 'row',
        gap: 10,
        marginBottom: 12,
    },
    rdAttachBtn: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 16,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        backgroundColor: colors.card,
    },
    rdAttachIcon: {
        width: 40,
        height: 40,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
    },
    rdAttachLabel: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        marginTop: 6,
    },
    rdAttachSub: {
        fontSize: 10,
        color: colors.text3,
        marginTop: 2,
    },
    rdFollowHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 12,
    },
    rdFollowBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 10,
        paddingHorizontal: 12,
        paddingVertical: 7,
    },
    rdFollowBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.primary,
    },

    // Follow-up add card
    fuCard: {
        backgroundColor: colors.card,
        borderWidth: 2,
        borderColor: colors.primary,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
    },
    fuCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 14,
    },
    fuCardIcon: {
        width: 28,
        height: 28,
        borderRadius: 9,
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuCardTitle: {
        fontFamily: typography.font.black,
        fontSize: 13,
        color: colors.primary,
    },
    fuField: {
        marginBottom: 10,
    },
    fuLabel: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
        marginBottom: 5,
    },
    fuInput: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        paddingHorizontal: 12,
        paddingVertical: 10,
        fontSize: 13,
        color: colors.text,
        backgroundColor: colors.bg,
    },
    fuBtnRow: {
        flexDirection: 'row',
        gap: 8,
        marginTop: 16,
    },
    fuCancelBtn: {
        flex: 1,
        paddingVertical: 11,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 12,
        backgroundColor: colors.bg,
        alignItems: 'center',
    },
    fuCancelText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text2,
    },
    fuSaveBtn: {
        flex: 2,
        paddingVertical: 11,
        borderRadius: 12,
        backgroundColor: colors.primary,
        alignItems: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.25,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    fuSaveText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: '#fff',
    },
    // Saved follow-up item
    fuItem: {
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        padding: 14,
        marginBottom: 10,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    fuItemIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    fuItemBody: {
        flex: 1,
    },
    fuItemDate: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    fuItemPurpose: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    fuItemDelete: {
        width: 28,
        height: 28,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ═══════════════════════════════════
    //  ADD RECORD FORM
    // ═══════════════════════════════════
    arGroup: {
        marginBottom: 14,
    },
    arLabel: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.text2,
        marginBottom: 6,
    },
    arInput: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
        backgroundColor: colors.card,
    },
    arInputIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: colors.card,
    },
    arInputBare: {
        flex: 1,
        fontSize: 13,
        color: colors.text,
        padding: 0,
    },
    arTextarea: {
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
        backgroundColor: colors.card,
        minHeight: 80,
        textAlignVertical: 'top',
    },
    arRow: {
        flexDirection: 'row',
        gap: 12,
    },
    arSelectWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        backgroundColor: colors.card,
    },
    arSelectText: {
        flex: 1,
        fontSize: 13,
        color: colors.text,
    },
    arSelectPlaceholder: {
        flex: 1,
        fontSize: 13,
        color: colors.text3,
    },
    arDivider: {
        height: 1.5,
        backgroundColor: colors.border,
        borderRadius: 2,
        marginTop: 20,
        marginBottom: 16,
    },
    arSaveWrap: {
        paddingHorizontal: 20,
        paddingBottom: 28,
        paddingTop: 12,
    },

    // ═══════════════════════════════════
    //  NOTIFICATION SCREEN
    // ═══════════════════════════════════
    notiTopbar: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        gap: 12,
    },
    notiTitle: {
        fontSize: 17,
        fontWeight: '800',
        color: colors.text,
        letterSpacing: -0.2,
    },
    notiUnreadCount: {
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },
    notiMarkAllBtn: {
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 20,
        backgroundColor: '#F0FDFA',
        borderWidth: 1,
        borderColor: '#99F6E4',
    },
    notiMarkAllText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#0D9488',
    },
    notiGroupLabel: {
        fontSize: 10,
        fontWeight: '800',
        color: colors.text3,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        paddingHorizontal: 4,
        paddingTop: 10,
        paddingBottom: 6,
    },
    notiItem: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: 12,
        paddingHorizontal: 14,
        paddingVertical: 12,
        borderRadius: 16,
        marginBottom: 3,
    },
    notiItemUnread: {
        backgroundColor: '#F8FAFF',
        borderWidth: 1,
        borderColor: '#E8EFFE',
        borderLeftWidth: 3,
        borderLeftColor: '#2563EB',
    },
    notiItemRead: {
        backgroundColor: 'transparent',
        borderWidth: 1,
        borderColor: 'transparent',
    },
    notiIcon: {
        width: 38,
        height: 38,
        borderRadius: 12,
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: 1,
    },
    notiTitleRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 8,
        marginBottom: 3,
    },
    notiItemTitle: {
        fontSize: 13,
        fontWeight: '600',
        color: colors.text2,
        lineHeight: 18,
        flex: 1,
    },
    notiTime: {
        fontSize: 10,
        fontWeight: '600',
        color: colors.text3,
        paddingTop: 2,
    },
    notiBody: {
        fontSize: 11,
        color: colors.text3,
        lineHeight: 17,
    },
    notiVaxChips: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 5,
        flexWrap: 'wrap',
        marginTop: 3,
    },
    notiVaxChip: {
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 20,
        borderWidth: 1,
    },
    notiVaxChipText: {
        fontSize: 10,
        fontWeight: '700',
    },
    notiVaxDateRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
        marginTop: 4,
    },
    notiVaxDateText: {
        fontSize: 10,
        fontWeight: '600',
        color: colors.text3,
    },
    notiBadge: {
        position: 'absolute',
        top: 4,
        right: 4,
        width: 7,
        height: 7,
        borderRadius: 4,
        backgroundColor: '#EF4444',
        borderWidth: 1.5,
        borderColor: colors.card,
    },
});
