import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { colors, radius, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    topbar: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(4),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    topbarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconBtnSmall: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(10),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(10),
        ...shadows.card,
    },
    pageTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(16),
        color: colors.text,
    },
    heroCard: {
        marginHorizontal: scale(16),
        marginTop: verticalScale(14),
        borderRadius: moderateScale(22),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        ...shadows.card,
    },
    heroStrip: {
        paddingHorizontal: scale(18),
        paddingTop: verticalScale(16),
        paddingBottom: verticalScale(20),
    },
    stripRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    deviceName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    deviceId: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    pencilBtn: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        backgroundColor: 'rgba(255,255,255,0.9)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.95)',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 2,
    },
    avRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(14),
    },
    avWrap: {
        marginRight: scale(14),
        position: 'relative',
    },
    avCircle: {
        width: moderateScale(78),
        height: moderateScale(78),
        borderRadius: moderateScale(39),
        borderWidth: 3,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.2,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: verticalScale(6) },
        elevation: 4,
        overflow: 'hidden',
    },
    avInitials: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        color: colors.primary,
    },
    avCam: {
        position: 'absolute',
        bottom: verticalScale(1),
        right: scale(1),
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primary,
        borderWidth: 2,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.4,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    avOnline: {
        position: 'absolute',
        top: verticalScale(3),
        right: scale(1),
        width: moderateScale(12),
        height: moderateScale(12),
        borderRadius: moderateScale(6),
        backgroundColor: colors.cHealth,
        borderWidth: 2,
        borderColor: '#fff',
    },
    heroMeta: {
        flex: 1,
    },
    hmName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
        letterSpacing: -0.2,
    },
    hmSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text2,
        marginTop: verticalScale(2),
    },
    hmBadges: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: verticalScale(7),
        gap: scale(5),
    },
    hmBadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
    },
    heroContacts: {
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        backgroundColor: colors.card,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    contactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(6),
    },
    contactLabel: {
        width: scale(108),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    contactValue: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    section: {
        paddingHorizontal: scale(16),
        marginTop: verticalScale(20),
    },
    secTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    secTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    fieldCard: {
        borderRadius: radius.lg,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...shadows.card,
        overflow: 'hidden',
    },
    fieldRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    fieldRowMulti: {
        alignItems: 'flex-start',
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(14),
    },
    fIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    fBody: {
        flex: 1,
        minWidth: 0,
    },
    fLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(3),
    },
    fValue: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    fRight: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: scale(6),
        gap: scale(6),
    },
    fBadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        backgroundColor: colors.cHealthBg,
        color: colors.cHealth,
        overflow: 'hidden',
    },
    chevron: { fontSize: scaleFont(16), color: colors.text3 },
    fTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: verticalScale(3),
        gap: scale(5),
    },
    fTag: {
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(20),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
    },
    tagDisease: {
        backgroundColor: colors.cReminderBg,
    },
    tagMedicine: {
        backgroundColor: colors.cMedicalBg,
    },
    fTagText: { fontFamily: typography.font.semiBold, fontSize: scaleFont(11) },
    tagEmpty: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        fontStyle: 'italic',
        marginTop: verticalScale(3),
    },
    btnWrap: {
        paddingHorizontal: scale(16),
        marginTop: verticalScale(24),
    },
    btnSaveWrap: {
        borderRadius: moderateScale(14),
        overflow: 'hidden',
        shadowColor: colors.primary,
        shadowOpacity: 0.28,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
    },
    btnSaveGradient: {
        paddingVertical: verticalScale(15),
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: scale(8),
    },
    btnSaveText: {
        fontFamily: typography.font.bold,
        color: '#fff',
        fontSize: scaleFont(15),
    },
    btnLogout: {
        marginTop: verticalScale(10),
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(13),
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        flexDirection: 'row',
        gap: scale(8),
    },
    btnLogoutText: {
        fontFamily: typography.font.semiBold,
        color: colors.cDanger,
        fontSize: scaleFont(14),
    },

    /* ── Bottom Sheet (profile-specific extras; base in shared.ts) ── */
    sheetKeyboard: {
        justifyContent: 'flex-end',
    },
    sheetSuffix: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    sheetSelectOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        marginBottom: verticalScale(8),
    },
    sheetSelectActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    sheetSelectText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    sheetSelectTextActive: {
        color: colors.primary,
    },
    /* ── Calendar ── */
    calHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: verticalScale(12),
    },
    calMonthYear: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(15),
        color: colors.text,
    },
    calNav: {
        flexDirection: 'row',
        gap: scale(4),
    },
    calNavBtn: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(8),
        alignItems: 'center',
        justifyContent: 'center',
    },
    calWeekRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: verticalScale(2),
    },
    calWeekDay: {
        width: scale(36),
        textAlign: 'center',
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.text3,
        paddingVertical: verticalScale(6),
    },
    calDayCell: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(8),
        alignItems: 'center',
        justifyContent: 'center',
    },
    calDaySel: {
        backgroundColor: colors.text,
        borderRadius: moderateScale(8),
    },
    calDayText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    calDayOther: {
        color: colors.text3,
    },
    calDayTextSel: {
        color: '#fff',
        fontFamily: typography.font.bold,
    },
    calDayTextToday: {
        color: colors.primary,
        fontFamily: typography.font.bold,
    },
    calActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(4),
        borderTopWidth: 1,
        borderTopColor: colors.border,
        marginTop: verticalScale(8),
    },
    calClear: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.primary,
        paddingVertical: verticalScale(6),
    },
    calToday: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.primary,
        paddingVertical: verticalScale(6),
    },
    /* ── Stepper ── */
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.bg,
        borderRadius: moderateScale(14),
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingLeft: scale(14),
        paddingRight: scale(6),
        height: verticalScale(50),
    },
    stepperFocused: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    stepperInput: {
        flex: 1,
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
        color: colors.text,
        paddingVertical: 0,
    },
    stepperControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        marginRight: scale(8),
    },
    stepBtn: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(8),
        backgroundColor: colors.card,
        borderWidth: 1.2,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    stepperUnit: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
});
