import { StyleSheet } from 'react-native';
import { colors, radius, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    topbar: {
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 4,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    topbarLeft: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    iconBtnSmall: {
        width: 34,
        height: 34,
        borderRadius: 10,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 10,
        ...shadows.card,
    },
    pageTitle: {
        fontFamily: typography.font.bold,
        fontSize: 16,
        color: colors.text,
    },
    heroCard: {
        marginHorizontal: 16,
        marginTop: 14,
        borderRadius: 22,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        ...shadows.card,
    },
    heroStrip: {
        paddingHorizontal: 18,
        paddingTop: 16,
        paddingBottom: 20,
    },
    stripRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
    },
    deviceName: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    deviceId: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },
    pencilBtn: {
        width: 30,
        height: 30,
        borderRadius: 9,
        backgroundColor: 'rgba(255,255,255,0.9)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.95)',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.1,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 2,
    },
    avRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 14,
    },
    avWrap: {
        marginRight: 14,
        position: 'relative',
    },
    avCircle: {
        width: 78,
        height: 78,
        borderRadius: 39,
        borderWidth: 3,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.2,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 6 },
        elevation: 4,
        overflow: 'hidden',
    },
    avInitials: {
        fontFamily: typography.font.black,
        fontSize: 26,
        color: colors.primary,
    },
    avCam: {
        position: 'absolute',
        bottom: 1,
        right: 1,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: colors.primary,
        borderWidth: 2,
        borderColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.4,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    avOnline: {
        position: 'absolute',
        top: 3,
        right: 1,
        width: 12,
        height: 12,
        borderRadius: 6,
        backgroundColor: colors.cHealth,
        borderWidth: 2,
        borderColor: '#fff',
    },
    heroMeta: {
        flex: 1,
    },
    hmName: {
        fontFamily: typography.font.black,
        fontSize: 17,
        color: colors.text,
        letterSpacing: -0.2,
    },
    hmSub: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text2,
        marginTop: 2,
    },
    hmBadges: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 7,
        gap: 5,
    },
    hmBadge: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 9,
        paddingVertical: 3,
        borderRadius: 20,
        overflow: 'hidden',
    },
    heroContacts: {
        paddingHorizontal: 18,
        paddingVertical: 13,
        backgroundColor: colors.card,
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    contactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 6,
    },
    contactLabel: {
        width: 108,
        fontFamily: typography.font.medium,
        fontSize: 12,
        color: colors.text3,
    },
    contactValue: {
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
    },
    section: {
        paddingHorizontal: 16,
        marginTop: 20,
    },
    secTitleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    secTitle: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    fieldCard: {
        borderRadius: radius.lg,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        ...shadows.card,
        overflow: 'hidden',
    },
    fieldRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    fieldRowMulti: {
        alignItems: 'flex-start',
        paddingTop: 14,
        paddingBottom: 14,
    },
    fIcon: {
        width: 36,
        height: 36,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: 12,
    },
    fBody: {
        flex: 1,
        minWidth: 0,
    },
    fLabel: {
        fontFamily: typography.font.medium,
        fontSize: 11,
        color: colors.text3,
        marginBottom: 3,
    },
    fValue: {
        fontFamily: typography.font.semiBold,
        fontSize: 14,
        color: colors.text,
    },
    fRight: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 6,
        gap: 6,
    },
    fBadge: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 20,
        backgroundColor: colors.cHealthBg,
        color: colors.cHealth,
        overflow: 'hidden',
    },
    chevron: { fontSize: 16, color: colors.text3 },
    fTags: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginTop: 3,
        gap: 5,
    },
    fTag: {
        paddingHorizontal: 9,
        paddingVertical: 3,
        borderRadius: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 4,
    },
    tagDisease: {
        backgroundColor: colors.cReminderBg,
    },
    tagMedicine: {
        backgroundColor: colors.cMedicalBg,
    },
    fTagText: { fontFamily: typography.font.semiBold, fontSize: 11 },
    tagEmpty: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text3,
        fontStyle: 'italic',
        marginTop: 3,
    },
    btnWrap: {
        paddingHorizontal: 16,
        marginTop: 24,
    },
    btnSaveWrap: {
        borderRadius: 14,
        overflow: 'hidden',
        shadowColor: colors.primary,
        shadowOpacity: 0.28,
        shadowRadius: 20,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    btnSaveGradient: {
        paddingVertical: 15,
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
    },
    btnSaveText: {
        fontFamily: typography.font.bold,
        color: '#fff',
        fontSize: 15,
    },
    btnLogout: {
        marginTop: 10,
        borderRadius: 14,
        paddingVertical: 13,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        flexDirection: 'row',
        gap: 8,
    },
    btnLogoutText: {
        fontFamily: typography.font.semiBold,
        color: colors.cDanger,
        fontSize: 14,
    },

    /* ── Bottom Sheet (profile-specific extras; base in shared.ts) ── */
    sheetKeyboard: {
        justifyContent: 'flex-end',
    },
    sheetSuffix: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.text3,
    },
    sheetSelectOption: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 16,
        paddingVertical: 14,
        borderRadius: 14,
        borderWidth: 1.5,
        borderColor: colors.border,
        backgroundColor: colors.card,
        marginBottom: 8,
    },
    sheetSelectActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    sheetSelectText: {
        fontFamily: typography.font.semiBold,
        fontSize: 14,
        color: colors.text,
    },
    sheetSelectTextActive: {
        color: colors.primary,
    },
    /* ── Calendar ── */
    calHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 12,
    },
    calMonthYear: {
        fontFamily: typography.font.bold,
        fontSize: 15,
        color: colors.text,
    },
    calNav: {
        flexDirection: 'row',
        gap: 4,
    },
    calNavBtn: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calWeekRow: {
        flexDirection: 'row',
        justifyContent: 'space-around',
        marginBottom: 2,
    },
    calWeekDay: {
        width: 36,
        textAlign: 'center',
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.text3,
        paddingVertical: 6,
    },
    calDayCell: {
        width: 36,
        height: 36,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
    },
    calDaySel: {
        backgroundColor: colors.text,
        borderRadius: 8,
    },
    calDayText: {
        fontFamily: typography.font.medium,
        fontSize: 13,
        color: colors.text,
    },
    calDayOther: {
        color: colors.text3,
    },
    calDayTextSel: {
        color: '#fff',
        fontFamily: typography.font.bold,
    },
    calDayTextToday: {
        color: colors.primary,
        fontFamily: typography.font.bold,
    },
    calActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 8,
        paddingBottom: 4,
        borderTopWidth: 1,
        borderTopColor: colors.border,
        marginTop: 8,
    },
    calClear: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.primary,
        paddingVertical: 6,
    },
    calToday: {
        fontFamily: typography.font.semiBold,
        fontSize: 13,
        color: colors.primary,
        paddingVertical: 6,
    },
});
