// src/screens/family/styles.ts
import { Platform, StyleSheet } from 'react-native';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    // ── Layout ──
    container: { flex: 1, backgroundColor: colors.bg },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: 32 },
    statusTopSpacer: { height: Platform.OS === 'android' ? 28 : 0 },

    // ── Topbar ──
    topbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 10,
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: 26,
        color: colors.text,
        letterSpacing: -0.3,
    },
    topbarRight: { flexDirection: 'row', gap: 8, alignItems: 'center' },

    // ── Family Card ──
    fcard: {
        marginHorizontal: 20,
        borderRadius: 22,
        overflow: 'hidden',
        marginBottom: 12,
        ...shadows.card,
        shadowOpacity: 0.1,
        elevation: 5,
    },
    fcardBg: {
        height: 104,
        position: 'relative',
        overflow: 'hidden',
    },
    fcardInner: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 16,
        paddingVertical: 14,
        gap: 13,
    },
    fcardIcon: {
        width: 52,
        height: 52,
        borderRadius: 16,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fcardInfo: { flex: 1 },
    fcardName: {
        fontFamily: typography.font.black,
        fontSize: 18,
        color: '#fff',
        letterSpacing: -0.2,
        lineHeight: 22,
    },
    fcardMeta: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: 'rgba(255,255,255,0.65)',
        marginTop: 2,
    },
    fcardRole: {
        fontFamily: typography.font.semiBold,
        fontSize: 10,
        color: 'rgba(255,255,255,0.55)',
        marginTop: 2,
    },
    fcardArrow: {
        width: 26,
        height: 26,
        borderRadius: 8,
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Add Family Card ──
    addFcard: {
        marginHorizontal: 20,
        borderRadius: 22,
        overflow: 'hidden',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#BFDBFE',
        backgroundColor: '#EFF6FF',
        marginTop: 4,
    },
    addFcardInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 13,
        paddingHorizontal: 16,
        paddingVertical: 18,
    },
    addFcardIc: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#BFDBFE',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
        elevation: 3,
    },
    addFcardTitle: {
        fontFamily: typography.font.black,
        fontSize: 14,
        color: colors.primary,
    },
    addFcardSub: {
        fontFamily: typography.font.medium,
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
    },

    // ── Popup / Create Family Sheet ──
    popupAvWrap: {
        alignItems: 'center',
        marginBottom: 20,
        gap: 8,
    },
    popupAv: {
        width: 72,
        height: 72,
        borderRadius: 36,
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#7C3AED',
        shadowOpacity: 0.2,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    popupAvCam: {
        position: 'absolute',
        bottom: 2,
        right: 2,
        width: 22,
        height: 22,
        borderRadius: 11,
        backgroundColor: '#7C3AED',
        borderWidth: 2.5,
        borderColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    popupAvHint: {
        fontFamily: typography.font.medium,
        fontSize: 11,
        color: colors.text3,
    },
    formGroup: { marginBottom: 14 },
    formLabel: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 6,
    },
    formInput: {
        paddingHorizontal: 16,
        paddingVertical: 13,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        fontFamily: typography.font.semiBold,
        fontSize: 14,
        color: colors.text,
        backgroundColor: colors.card,
    },
    formHint: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 4,
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        backgroundColor: '#EFF6FF',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 14,
        paddingHorizontal: 14,
        paddingVertical: 12,
        marginBottom: 18,
    },
    infoText: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: 12,
        color: colors.primary,
        lineHeight: 18,
    },
    createBtn: {
        borderRadius: 16,
        paddingVertical: 14,
        alignItems: 'center',
        marginTop: 4,
        shadowColor: '#7C3AED',
        shadowOpacity: 0.25,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: 4 },
        elevation: 5,
    },
    createBtnText: {
        fontFamily: typography.font.black,
        fontSize: 15,
        color: '#fff',
    },

    // ── Detail Hero ──
    detailHero: {
        height: 148,
        position: 'relative',
        overflow: 'hidden',
    },
    detailHeroContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingHorizontal: 20,
        paddingBottom: 14,
        gap: 12,
    },
    backBtn: {
        position: 'absolute',
        top: Platform.OS === 'android' ? 36 : 50,
        left: 20,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: 9,
        paddingHorizontal: 11,
        paddingVertical: 6,
    },
    backBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: '#fff',
    },
    davStack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dav: {
        width: 34,
        height: 34,
        borderRadius: 17,
        borderWidth: 2.5,
        borderColor: 'rgba(255,255,255,0.65)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: -8,
    },
    davFirst: { marginLeft: 0 },
    davText: {
        fontFamily: typography.font.black,
        fontSize: 11,
        color: '#fff',
    },
    detailInfo: { flex: 1 },
    detailName: {
        fontFamily: typography.font.black,
        fontSize: 20,
        color: '#fff',
        letterSpacing: -0.3,
    },
    detailSub: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: 'rgba(255,255,255,0.6)',
        marginTop: 2,
    },
    detailMore: {
        width: 34,
        height: 34,
        borderRadius: 17,
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Member Row ──
    mrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 18,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mrowLast: { borderBottomWidth: 0 },
    mav: {
        width: 40,
        height: 40,
        borderRadius: 20,
        alignItems: 'center',
        justifyContent: 'center',
    },
    mavText: {
        fontFamily: typography.font.black,
        fontSize: 13,
        color: '#fff',
    },
    mavDot: {
        position: 'absolute',
        bottom: 1,
        right: 1,
        width: 10,
        height: 10,
        borderRadius: 5,
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: '#22C55E',
    },
    minfo: { flex: 1 },
    mname: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text,
    },
    mbadge: {
        fontFamily: typography.font.bold,
        fontSize: 10,
        backgroundColor: '#EFF6FF',
        color: colors.primary,
        paddingHorizontal: 7,
        paddingVertical: 2,
        borderRadius: 10,
        marginLeft: 4,
        overflow: 'hidden',
    },
    mrole: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 1,
    },

    // ── Add Member Row ──
    addMrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 18,
        paddingVertical: 13,
    },
    addMic: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: '#EFF6FF',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#BFDBFE',
        alignItems: 'center',
        justifyContent: 'center',
    },
    addMlbl: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.primary,
    },

    // ── Danger Zone ──
    dangerCard: {
        marginHorizontal: 20,
        marginTop: 20,
        backgroundColor: '#FFF1F2',
        borderWidth: 1.5,
        borderColor: '#FECDD3',
        borderRadius: 16,
        paddingHorizontal: 16,
        paddingVertical: 14,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    dangerText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: '#E11D48',
    },

    // ── Add Member Screen ──
    inviteHero: {
        height: 120,
        position: 'relative',
        overflow: 'hidden',
    },
    inviteHeroInner: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: 20,
        paddingBottom: 14,
    },
    inviteTitle: {
        fontFamily: typography.font.black,
        fontSize: 22,
        color: '#fff',
        letterSpacing: -0.3,
    },
    methodCard: {
        marginHorizontal: 20,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 20,
        overflow: 'hidden',
        marginBottom: 12,
        ...shadows.card,
    },
    methodInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 14,
        paddingHorizontal: 18,
        paddingVertical: 16,
    },
    methodIc: {
        width: 46,
        height: 46,
        borderRadius: 14,
        alignItems: 'center',
        justifyContent: 'center',
    },
    methodBody: { flex: 1 },
    methodTitle: {
        fontFamily: typography.font.black,
        fontSize: 14,
        color: colors.text,
    },
    methodSub: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 2,
        lineHeight: 16,
    },

    // ── Link Box ──
    linkBox: {
        marginHorizontal: 20,
        backgroundColor: '#EFF6FF',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 18,
        padding: 16,
    },
    linkLabel: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.primary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: 8,
    },
    linkRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        backgroundColor: '#fff',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
    },
    linkUrl: {
        flex: 1,
        fontFamily: typography.font.bold,
        fontSize: 12,
        color: colors.primary,
    },
    copyBtn: {
        backgroundColor: colors.primary,
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 9,
    },
    copyBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: '#fff',
    },
    linkHint: {
        fontFamily: typography.font.regular,
        fontSize: 11,
        color: colors.text3,
        marginTop: 8,
        textAlign: 'center',
    },
    shareRow: {
        flexDirection: 'row',
        gap: 10,
        marginHorizontal: 20,
        marginTop: 12,
    },
    shareBtn: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: 14,
        paddingVertical: 13,
        alignItems: 'center',
        gap: 6,
    },
    shareBtnText: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.text2,
    },

    // ── Member Detail Header ──
    memberHeader: {
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: 20,
        paddingTop: 8,
        paddingBottom: 14,
    },
    memberHeaderTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 14,
    },
    memberBackBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 6,
    },
    memberBackText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.primary,
    },
    memberAv: {
        width: 64,
        height: 64,
        borderRadius: 32,
        alignItems: 'center',
        justifyContent: 'center',
    },
    memberAvText: {
        fontFamily: typography.font.black,
        fontSize: 20,
        color: '#fff',
    },
    memberName: {
        fontFamily: typography.font.black,
        fontSize: 17,
        color: colors.text,
    },
    memberMeta: {
        fontFamily: typography.font.regular,
        fontSize: 12,
        color: colors.text3,
        marginTop: 2,
    },
    roleBadge: {
        alignSelf: 'flex-start',
        fontFamily: typography.font.bold,
        fontSize: 11,
        paddingHorizontal: 10,
        paddingVertical: 3,
        borderRadius: 10,
        overflow: 'hidden',
        marginTop: 6,
    },

    // ── Tabs ──
    tabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    tab: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: 12,
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: colors.primary,
    },
    tabText: {
        fontFamily: typography.font.bold,
        fontSize: 13,
        color: colors.text3,
    },
    tabTextActive: {
        color: colors.primary,
    },

    // ── Profile Rows ──
    prow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        paddingHorizontal: 18,
        paddingVertical: 13,
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    prowLast: { borderBottomWidth: 0 },
    prowIc: {
        width: 38,
        height: 38,
        borderRadius: 11,
        alignItems: 'center',
        justifyContent: 'center',
    },
    prowBody: { flex: 1 },
    prowLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: colors.text3,
        marginBottom: 2,
    },
    prowValue: {
        fontFamily: typography.font.bold,
        fontSize: 14,
        color: colors.text,
    },
    bmiBadgeInline: {
        fontFamily: typography.font.bold,
        fontSize: 11,
        color: colors.primary,
        backgroundColor: '#EFF6FF',
        paddingHorizontal: 8,
        paddingVertical: 2,
        borderRadius: 8,
        overflow: 'hidden',
        marginLeft: 8,
    },

    // ── Read-only Banner ──
    readonlyBanner: {
        marginHorizontal: 20,
        marginTop: 14,
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: '#FFFBEB',
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: 12,
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
    },
    readonlyText: {
        fontFamily: typography.font.semiBold,
        fontSize: 11,
        color: '#D97706',
    },
});
