// src/screens/family/styles.ts
import { Platform, StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    // ── Layout ──
    container: { flex: 1, backgroundColor: colors.bg },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: verticalScale(32) },
    statusTopSpacer: {
        height: Platform.OS === 'android' ? verticalScale(28) : 0,
    },

    // ── Topbar ──
    topbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        color: colors.text,
        letterSpacing: -0.3,
    },
    topbarRight: { flexDirection: 'row', gap: scale(8), alignItems: 'center' },

    // ── Family Card ──
    fcard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(22),
        overflow: 'hidden',
        marginBottom: verticalScale(12),
        ...shadows.card,
        shadowOpacity: 0.1,
        elevation: 5,
    },
    fcardBg: {
        height: verticalScale(104),
        position: 'relative',
        overflow: 'hidden',
    },
    fcardInner: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        gap: scale(13),
    },
    fcardIcon: {
        width: moderateScale(52),
        height: moderateScale(52),
        borderRadius: moderateScale(16),
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fcardInfo: { flex: 1 },
    fcardName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: '#fff',
        letterSpacing: -0.2,
        lineHeight: verticalScale(22),
    },
    fcardMeta: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: 'rgba(255,255,255,0.65)',
        marginTop: verticalScale(2),
    },
    fcardRole: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.55)',
        marginTop: verticalScale(2),
    },
    fcardArrow: {
        width: moderateScale(26),
        height: moderateScale(26),
        borderRadius: moderateScale(8),
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Add Family Card ──
    addFcard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(22),
        overflow: 'hidden',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#BFDBFE',
        backgroundColor: '#EFF6FF',
        marginTop: verticalScale(4),
    },
    addFcardInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(13),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(18),
    },
    addFcardIc: {
        width: moderateScale(44),
        height: moderateScale(44),
        borderRadius: moderateScale(22),
        backgroundColor: '#fff',
        borderWidth: 2,
        borderColor: '#BFDBFE',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#2563EB',
        shadowOpacity: 0.12,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    addFcardTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(14),
        color: colors.primary,
    },
    addFcardSub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
    },

    // ── Popup / Create Family Sheet ──
    popupAvWrap: {
        alignItems: 'center',
        marginBottom: verticalScale(20),
        gap: scale(8),
    },
    popupAv: {
        width: moderateScale(72),
        height: moderateScale(72),
        borderRadius: moderateScale(36),
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: '#7C3AED',
        shadowOpacity: 0.2,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
    },
    popupAvCam: {
        position: 'absolute',
        bottom: verticalScale(2),
        right: scale(2),
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        backgroundColor: '#7C3AED',
        borderWidth: 2.5,
        borderColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    popupAvHint: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    formGroup: { marginBottom: verticalScale(14) },
    formLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(6),
    },
    formInput: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(13),
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
        backgroundColor: colors.card,
    },
    formHint: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(4),
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        backgroundColor: '#EFF6FF',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        marginBottom: verticalScale(18),
    },
    infoText: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.primary,
        lineHeight: verticalScale(18),
    },
    createBtn: {
        borderRadius: moderateScale(16),
        paddingVertical: verticalScale(14),
        alignItems: 'center',
        marginTop: verticalScale(4),
        shadowColor: '#7C3AED',
        shadowOpacity: 0.25,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
    },
    createBtnText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: '#fff',
    },

    // ── Detail Hero ──
    detailHero: {
        height: verticalScale(148),
        position: 'relative',
        overflow: 'hidden',
    },
    detailHeroContent: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        alignItems: 'flex-end',
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(14),
        gap: scale(12),
    },
    backBtn: {
        position: 'absolute',
        top: Platform.OS === 'android' ? verticalScale(36) : verticalScale(50),
        left: scale(20),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: moderateScale(9),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(6),
    },
    backBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: '#fff',
    },
    davStack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dav: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        borderWidth: 2.5,
        borderColor: 'rgba(255,255,255,0.65)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: scale(-8),
    },
    davFirst: { marginLeft: 0 },
    davText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(11),
        color: '#fff',
    },
    detailInfo: { flex: 1 },
    detailName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(20),
        color: '#fff',
        letterSpacing: -0.3,
    },
    detailSub: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: 'rgba(255,255,255,0.6)',
        marginTop: verticalScale(2),
    },
    detailMore: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Member Row ──
    mrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mrowLast: { borderBottomWidth: 0 },
    mav: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(20),
        alignItems: 'center',
        justifyContent: 'center',
    },
    mavText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: '#fff',
    },
    mavDot: {
        position: 'absolute',
        bottom: verticalScale(1),
        right: scale(1),
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
        borderWidth: 2,
        borderColor: '#fff',
        backgroundColor: '#22C55E',
    },
    minfo: { flex: 1 },
    mname: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    mbadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        backgroundColor: '#EFF6FF',
        color: colors.primary,
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(10),
        marginLeft: scale(4),
        overflow: 'hidden',
    },
    mrole: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },

    // ── Add Member Row ──
    addMrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
    },
    addMic: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(20),
        backgroundColor: '#EFF6FF',
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: '#BFDBFE',
        alignItems: 'center',
        justifyContent: 'center',
    },
    addMlbl: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },

    // ── Danger Zone ──
    dangerCard: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(20),
        backgroundColor: '#FFF1F2',
        borderWidth: 1.5,
        borderColor: '#FECDD3',
        borderRadius: moderateScale(16),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    dangerText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: '#E11D48',
    },

    // ── Add Member Screen ──
    inviteHero: {
        height: verticalScale(120),
        position: 'relative',
        overflow: 'hidden',
    },
    inviteHeroInner: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(14),
    },
    inviteTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(22),
        color: '#fff',
        letterSpacing: -0.3,
    },
    methodCard: {
        marginHorizontal: scale(20),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        marginBottom: verticalScale(12),
        ...shadows.card,
    },
    methodInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    methodIc: {
        width: moderateScale(46),
        height: moderateScale(46),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    methodBody: { flex: 1 },
    methodTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    methodSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
        lineHeight: verticalScale(16),
    },

    // ── Link Box ──
    linkBox: {
        marginHorizontal: scale(20),
        backgroundColor: '#EFF6FF',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: moderateScale(18),
        padding: scale(16),
    },
    linkLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.primary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(8),
    },
    linkRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        backgroundColor: '#fff',
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
    },
    linkUrl: {
        flex: 1,
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },
    copyBtn: {
        backgroundColor: colors.primary,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(9),
    },
    copyBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: '#fff',
    },
    linkHint: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(8),
        textAlign: 'center',
    },
    shareRow: {
        flexDirection: 'row',
        gap: scale(10),
        marginHorizontal: scale(20),
        marginTop: verticalScale(12),
    },
    shareBtn: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(13),
        alignItems: 'center',
        gap: scale(6),
    },
    shareBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
    },

    // ── Member Detail Header ──
    memberHeader: {
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(14),
    },
    memberHeaderTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(14),
    },
    memberBackBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    memberBackText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    memberAv: {
        width: moderateScale(64),
        height: moderateScale(64),
        borderRadius: moderateScale(32),
        alignItems: 'center',
        justifyContent: 'center',
    },
    memberAvText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(20),
        color: '#fff',
    },
    memberName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
    },
    memberMeta: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    roleBadge: {
        alignSelf: 'flex-start',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(10),
        overflow: 'hidden',
        marginTop: verticalScale(6),
    },

    // ── Tabs ──
    tabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    tab: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: colors.primary,
    },
    tabText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    tabTextActive: {
        color: colors.primary,
    },

    // ── Profile Rows ──
    prow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    prowLast: { borderBottomWidth: 0 },
    prowIc: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    prowBody: { flex: 1 },
    prowLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(2),
    },
    prowValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    bmiBadgeInline: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.primary,
        backgroundColor: '#EFF6FF',
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(8),
        overflow: 'hidden',
        marginLeft: scale(8),
    },

    // ── Read-only Banner ──
    readonlyBanner: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        backgroundColor: '#FFFBEB',
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(12),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
    },
    readonlyText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: '#D97706',
    },
    tipCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        padding: scale(14),
        marginBottom: verticalScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    tipEmoji: {
        fontSize: scaleFont(20),
    },
    tipTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    tipDesc: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingRight: scale(14),
        overflow: 'hidden',
    },
    stepperFocused: {
        borderColor: colors.cFamily,
    },
    stepperInput: {
        flex: 1,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(13),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    stepperControls: {
        flexDirection: 'column',
        justifyContent: 'center',
        gap: verticalScale(2),
        marginRight: scale(10),
    },
    stepBtn: {
        padding: scale(2),
    },
    stepperUnit: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    // ── Health Detail ──
    cstrip2: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    csicon2: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    countPill: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
        backgroundColor: '#EFF6FF',
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1.5,
        borderColor: '#BFDBFE',
    },
    rcard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    ricon: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(1),
    },
    rbody: { flex: 1 },
    rtitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        lineHeight: verticalScale(17),
    },
    rsub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    rtag: {
        alignSelf: 'flex-start',
        marginTop: verticalScale(5),
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        overflow: 'hidden',
    },
    rdateChip: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text2,
        backgroundColor: '#F1F5F9',
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(8),
        marginTop: verticalScale(2),
    },
    vrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    vic: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vname: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vsub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
});
