// src/screens/family/styles.ts
import { Platform, StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '../../styles/responsive';
import { buttonSystem, formSystem, inputSystem } from '../../styles/shared';
import { colors, shadows, typography } from '../../styles/tokens';

export const styles = StyleSheet.create({
    // ── Layout ──
    container: { flex: 1, backgroundColor: colors.bg },
    scroll: { flex: 1 },
    scrollContent: { paddingBottom: verticalScale(32) },
    statusTopSpacer: {
        height: Platform.OS === 'android' ? verticalScale(28) : 0,
    },

    // ── Topbar ──
    topbar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(10),
    },
    topbarTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(26),
        color: colors.text,
        letterSpacing: -0.3,
    },
    topbarRight: { flexDirection: 'row', gap: scale(8), alignItems: 'center' },

    // ── Family Card ──
    fcard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        marginBottom: verticalScale(10),
        ...shadows.card,
        shadowOpacity: 0.08,
        elevation: 2,
    },
    fcardBg: {
        height: verticalScale(104),
        position: 'relative',
        overflow: 'hidden',
    },
    fcardInner: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        gap: scale(13),
    },
    fcardIcon: {
        width: moderateScale(52),
        height: moderateScale(52),
        borderRadius: moderateScale(16),
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderWidth: 1.5,
        borderColor: 'rgba(255,255,255,0.2)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    fcardInfo: { flex: 1 },
    fcardName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.text,
        letterSpacing: -0.2,
        lineHeight: verticalScale(18),
    },
    fcardMeta: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.75),
        color: '#8FA1B7',
        marginTop: verticalScale(3),
    },
    fcardRole: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: 'rgba(255,255,255,0.55)',
        marginTop: verticalScale(2),
    },
    fcardArrow: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(11),
        backgroundColor: '#F5F8FC',
        borderWidth: 1.25,
        borderColor: '#E6EDF5',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Add Family Card ──
    addFcard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        borderWidth: 1.25,
        borderStyle: 'dashed',
        borderColor: '#B7E8D7',
        backgroundColor: '#F5FCF8',
        marginTop: verticalScale(2),
        ...shadows.card,
        shadowColor: '#B7C7C1',
        shadowOpacity: 0.05,
        elevation: 2,
    },
    addFcardInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(17),
    },
    addFcardIc: {
        width: moderateScale(50),
        height: moderateScale(50),
        borderRadius: moderateScale(25),
        backgroundColor: colors.card,
        borderWidth: 1.25,
        borderColor: '#B7E8D7',
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.08,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: verticalScale(2) },
        elevation: 3,
    },
    addFcardTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
        color: colors.primary,
    },
    addFcardSub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: '#7C8C86',
        marginTop: verticalScale(3),
    },

    // ── Popup / Create Family Sheet ──
    popupAvWrap: {
        alignItems: 'center',
        marginBottom: verticalScale(20),
        gap: scale(8),
    },
    popupAvPressable: {
        borderRadius: moderateScale(36),
    },
    popupAv: {
        width: moderateScale(72),
        height: moderateScale(72),
        borderRadius: moderateScale(36),
        alignItems: 'center',
        justifyContent: 'center',
        shadowColor: colors.primary,
        shadowOpacity: 0.2,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
        overflow: 'visible',
    },
    popupAvPlaceholder: {
        width: '100%',
        height: '100%',
        borderRadius: moderateScale(36),
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
    },
    popupAvImage: {
        width: '100%',
        height: '100%',
        borderRadius: moderateScale(36),
    },
    popupAvCam: {
        position: 'absolute',
        bottom: verticalScale(2),
        right: scale(2),
        width: moderateScale(22),
        height: moderateScale(22),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primary,
        borderWidth: 2.5,
        borderColor: colors.bg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    popupAvHint: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    formGroup: { marginBottom: verticalScale(14) },
    formLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(6),
    },
    formInput: {
        ...inputSystem.field,
        paddingHorizontal: scale(16),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    formHint: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(4),
    },
    infoBox: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(12),
        marginBottom: verticalScale(18),
    },
    infoText: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12),
        color: colors.primary,
        lineHeight: verticalScale(18),
    },
    createBtn: {
        ...buttonSystem.primary,
        borderRadius: moderateScale(16),
        alignItems: 'center',
        marginTop: verticalScale(4),
        shadowColor: colors.primary,
        shadowOpacity: 0.25,
        shadowRadius: 18,
        shadowOffset: { width: 0, height: verticalScale(4) },
        elevation: 5,
    },
    createBtnText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.card,
    },

    // ── Detail Hero ──
    detailHero: {
        minHeight: verticalScale(132),
        position: 'relative',
        overflow: 'hidden',
    },
    detailHeroContent: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(18),
        gap: scale(12),
    },
    backBtn: {
        position: 'absolute',
        top: Platform.OS === 'android' ? verticalScale(36) : verticalScale(50),
        left: scale(20),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        backgroundColor: 'rgba(255,255,255,0.15)',
        borderRadius: moderateScale(9),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(6),
    },
    backBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.card,
    },
    davStack: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    dav: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        borderWidth: 2.5,
        borderColor: 'rgba(255,255,255,0.65)',
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft: scale(-8),
    },
    davFirst: { marginLeft: 0 },
    davText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(11),
        color: colors.card,
    },
    detailInfo: { flex: 1 },
    detailName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(20),
        color: colors.card,
        letterSpacing: -0.3,
        lineHeight: verticalScale(24),
    },
    detailSub: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: 'rgba(255,255,255,0.6)',
        marginTop: verticalScale(2),
    },
    detailMore: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(17),
        backgroundColor: 'rgba(255,255,255,0.15)',
        alignItems: 'center',
        justifyContent: 'center',
    },

    // ── Member Row ──
    mrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    mrowLast: { borderBottomWidth: 0 },
    mav: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(20),
        alignItems: 'center',
        justifyContent: 'center',
    },
    mavText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: '#fff',
    },
    mavDot: {
        position: 'absolute',
        bottom: verticalScale(1),
        right: scale(1),
        width: moderateScale(10),
        height: moderateScale(10),
        borderRadius: moderateScale(5),
        borderWidth: 2,
        borderColor: colors.card,
        backgroundColor: colors.success,
    },
    minfo: { flex: 1 },
    mname: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    mbadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        backgroundColor: colors.primaryBg,
        color: colors.primary,
        paddingHorizontal: scale(7),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(10),
        marginLeft: scale(4),
        overflow: 'hidden',
    },
    mrole: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },

    // ── Add Member Row ──
    addMrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
    },
    addMic: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(20),
        backgroundColor: colors.primaryBg,
        borderWidth: 2,
        borderStyle: 'dashed',
        borderColor: colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addMlbl: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },

    // ── Danger Zone ──
    dangerCard: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(20),
        backgroundColor: colors.dangerBg,
        borderWidth: 1.5,
        borderColor: '#FECACA',
        borderRadius: moderateScale(16),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    dangerText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.danger,
    },

    // ── Add Member Screen ──
    inviteHero: {
        height: verticalScale(150),
        position: 'relative',
        overflow: 'hidden',
    },
    inviteHeroInner: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(14),
    },
    inviteTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(22),
        color: colors.card,
        letterSpacing: -0.3,
    },
    methodCard: {
        marginHorizontal: scale(20),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(20),
        overflow: 'hidden',
        marginBottom: verticalScale(12),
        ...shadows.card,
    },
    methodInner: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(14),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(16),
    },
    methodIc: {
        width: moderateScale(46),
        height: moderateScale(46),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    methodBody: { flex: 1 },
    methodTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    methodSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(2),
        lineHeight: verticalScale(16),
    },

    // ── Link Box ──
    linkRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(12),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
    },
    linkUrl: {
        flex: 1,
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },
    copyBtn: {
        backgroundColor: colors.primary,
        paddingHorizontal: scale(12),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(9),
    },
    copyBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.card,
    },
    linkHint: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(8),
        textAlign: 'center',
    },
    shareRow: {
        flexDirection: 'row',
        gap: scale(10),
        marginHorizontal: scale(20),
        marginTop: verticalScale(12),
    },
    shareBtn: {
        flex: 1,
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(13),
        alignItems: 'center',
        gap: scale(6),
    },
    shareBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
    },

    // ── Member Detail Header ──
    memberHeader: {
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(14),
    },
    memberHeaderTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: verticalScale(14),
    },
    memberBackBtn: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
    },
    memberBackText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    memberAv: {
        width: moderateScale(64),
        height: moderateScale(64),
        borderRadius: moderateScale(32),
        alignItems: 'center',
        justifyContent: 'center',
    },
    memberAvText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(20),
        color: colors.card,
    },
    memberName: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(17),
        color: colors.text,
    },
    memberMeta: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    roleBadge: {
        alignSelf: 'flex-start',
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(10),
        overflow: 'hidden',
        marginTop: verticalScale(6),
    },

    // ── Tabs ──
    tabBar: {
        flexDirection: 'row',
        backgroundColor: colors.card,
        borderBottomWidth: 1.5,
        borderBottomColor: colors.border,
    },
    tab: {
        flex: 1,
        alignItems: 'center',
        paddingVertical: verticalScale(12),
        borderBottomWidth: 2.5,
        borderBottomColor: 'transparent',
    },
    tabActive: {
        borderBottomColor: colors.primary,
    },
    tabText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    tabTextActive: {
        color: colors.primary,
    },

    // ── Profile Rows ──
    prow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    prowLast: { borderBottomWidth: 0 },
    prowIc: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    prowBody: { flex: 1 },
    prowLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(4),
    },
    prowValue: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        lineHeight: verticalScale(18),
    },
    bmiBadgeInline: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.5),
        color: colors.primary,
        backgroundColor: colors.primaryBg,
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(8),
        overflow: 'hidden',
        marginLeft: scale(8),
    },

    // ── Read-only Banner ──
    readonlyBanner: {
        marginHorizontal: scale(20),
        marginTop: verticalScale(14),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.warningBg,
        borderWidth: 1.5,
        borderColor: '#FDE68A',
        borderRadius: moderateScale(12),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
    },
    readonlyText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.warning,
    },
    tipCard: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        padding: scale(14),
        marginBottom: verticalScale(10),
        borderWidth: 1.5,
        borderColor: colors.border,
    },
    tipEmoji: {
        fontSize: scaleFont(20),
    },
    tipTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    tipDesc: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    stepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingRight: scale(14),
        overflow: 'hidden',
    },
    stepperFocused: {
        borderColor: colors.secondary,
    },
    stepperInput: {
        flex: 1,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(13),
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    stepperControls: {
        flexDirection: 'column',
        justifyContent: 'center',
        gap: verticalScale(2),
        marginRight: scale(10),
    },
    stepBtn: {
        padding: scale(2),
    },
    stepperUnit: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text3,
    },
    // ── Health Detail ──
    cstrip2: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    csicon2: {
        width: moderateScale(34),
        height: moderateScale(34),
        borderRadius: moderateScale(10),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    countPill: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
        backgroundColor: colors.primaryBg,
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(20),
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
    },
    rcard: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(13),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    ricon: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(1),
    },
    rbody: { flex: 1 },
    rtitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        lineHeight: verticalScale(17),
    },
    rsub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    rtag: {
        alignSelf: 'flex-start',
        marginTop: verticalScale(5),
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        overflow: 'hidden',
    },
    rdateChip: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text2,
        backgroundColor: colors.bgHealth,
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(8),
        marginTop: verticalScale(2),
    },
    vrow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    vic: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        alignItems: 'center',
        justifyContent: 'center',
    },
    vname: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    vsub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    // ── Invite Link Specifics ──
    linkBox: {
        backgroundColor: colors.primaryBg,
        borderWidth: 1.5,
        borderColor: colors.primaryLight,
        borderRadius: moderateScale(18),
        padding: scale(16),
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    linkLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.primary,
        textTransform: 'uppercase',
        letterSpacing: 0.6,
        marginBottom: verticalScale(4),
    },
    linkText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
        color: colors.text,
    },
    linkPlaceholderText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },
    linkActionBtn: {
        width: scale(42),
        height: scale(42),
        borderRadius: moderateScale(11),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    healthSummaryCard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(20),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        ...shadows.card,
        marginBottom: verticalScale(16),
    },
    // ── BMI Styles ──
    bmiRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingTop: verticalScale(12),
        paddingBottom: verticalScale(10),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    bmiIcon: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    bmiLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(4),
    },
    bmiValueRow: { flexDirection: 'row', alignItems: 'flex-end' },
    bmiValue: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.text,
        letterSpacing: -0.7,
    },
    bmiUnit: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10.5),
        color: colors.text3,
        marginLeft: scale(4),
    },
    bmiSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(3),
    },
    bmiBadge: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.success,
        backgroundColor: colors.successBg,
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(16),
        overflow: 'hidden',
    },
    bmiGaugeWrap: {
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(12),
    },
    bmiGaugeTrack: {
        height: verticalScale(6),
        borderRadius: moderateScale(8),
        backgroundColor: colors.border,
        justifyContent: 'center',
    },
    bmiGaugeThumb: {
        position: 'absolute',
        width: moderateScale(12),
        height: moderateScale(12),
        borderRadius: moderateScale(6),
        backgroundColor: colors.card,
        borderWidth: 2,
        borderColor: colors.primary,
    },
    bmiGaugeLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: verticalScale(6),
    },
    bmiGaugeLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(9.5),
    },
    bmiNoteRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(8),
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
        backgroundColor: colors.bg,
    },
    bmiNoteText: {
        flex: 1,
        fontFamily: typography.font.regular,
        fontSize: scaleFont(10),
        color: colors.text3,
        lineHeight: verticalScale(15),
    },
    healthInfoCard: {
        marginHorizontal: scale(20),
        borderRadius: moderateScale(20),
        backgroundColor: colors.card,
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        ...shadows.card,
    },
    healthInfoRowObj: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    hiIconWrap: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(12),
    },
    hiBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: verticalScale(30),
    },
    hiLabel: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        marginBottom: verticalScale(2),
    },
    hiValueInline: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
        letterSpacing: -0.3,
    },
    hiLabelTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginBottom: verticalScale(4),
        marginTop: verticalScale(1),
    },
    hiChipsWrap: {
        flexDirection: 'row',
        alignItems: 'center',
        flexWrap: 'wrap',
        gap: scale(6),
        marginTop: verticalScale(1),
    },
    hiChip: {
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(999),
        backgroundColor: colors.divider,
    },
    hiChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.text2,
    },
    hiChipTextTruncated: {
        maxWidth: scale(130),
    },
    hiChipMutedBtn: {
        borderRadius: moderateScale(999),
    },
    hiChipMuted: {
        backgroundColor: colors.divider,
        borderRadius: moderateScale(999),
        paddingHorizontal: scale(9),
        paddingVertical: verticalScale(3),
    },
    hiChipMutedText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10.5),
        color: colors.text2,
    },
    hiAddChip: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(16),
        backgroundColor: '#EFF6FF',
    },
    hiAddChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: '#2563EB',
    },
    hiEmptyText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        fontStyle: 'italic',
        color: colors.text3,
    },
    hiBlockWrap: {
        marginTop: verticalScale(5),
        backgroundColor: '#F1F5F9',
        borderRadius: moderateScale(10),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(9),
    },
    hiBlockText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    tagPreviewWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    tagPreviewChip: {
        borderRadius: moderateScale(999),
        paddingHorizontal: scale(11),
        paddingVertical: verticalScale(5),
        backgroundColor: colors.divider,
    },
    tagPreviewChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11),
        color: colors.text2,
    },
    btGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    btOpt: {
        width: '23%' as unknown as number,
        borderWidth: 1.5,
        borderColor: '#FECACA',
        borderRadius: moderateScale(12),
        paddingVertical: verticalScale(12),
        alignItems: 'center',
        backgroundColor: colors.card,
    },
    btOptSel: {
        borderColor: colors.danger,
        backgroundColor: colors.dangerBg,
    },
    btOptText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(15),
        color: colors.danger,
    },
    btOptTextSel: {
        color: colors.danger,
    },
    tagInputWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        alignItems: 'center',
        alignContent: 'flex-start',
        justifyContent: 'flex-start',
        rowGap: scale(6),
        columnGap: scale(6),
        ...inputSystem.field,
        paddingLeft: scale(10),
        paddingRight: scale(10),
        paddingVertical: verticalScale(5),
        minHeight: verticalScale(40),
        alignSelf: 'stretch',
        width: '100%',
        overflow: 'hidden',
    },
    tagChip: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(4),
        backgroundColor: colors.divider,
        paddingVertical: verticalScale(2),
        paddingLeft: scale(8),
        paddingRight: scale(6),
        borderRadius: moderateScale(7),
        alignSelf: 'center',
        maxWidth: '100%',
    },
    tagChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10.5),
        color: colors.text2,
        flexShrink: 1,
    },
    tagChipX: {
        fontSize: scaleFont(13),
        color: colors.text2,
        opacity: 0.6,
        paddingHorizontal: scale(2),
    },
    tagInput: {
        flexGrow: 1,
        flexShrink: 1,
        flexBasis: scale(72),
        minWidth: scale(72),
        maxWidth: '100%',
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        lineHeight: verticalScale(16),
        color: colors.text,
        paddingHorizontal: 0,
        paddingVertical: 0,
        minHeight: verticalScale(20),
        textAlignVertical: 'center',
    },
    tagHint: {
        fontSize: scaleFont(11),
        color: colors.text3,
        marginTop: verticalScale(8),
    },
    healthInfoRow: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    healthInfoRowLast: {
        borderBottomWidth: 0,
    },
    healthInfoLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(5),
    },
    healthInfoValue: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
        lineHeight: verticalScale(18),
    },
    emergencyContactRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    emergencyContactBody: {
        flex: 1,
        marginLeft: scale(12),
    },
    ecAvatar: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
    },
    ecAvatarText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(16),
    },
    ecAddText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: '#2563EB',
        marginLeft: scale(12),
    },
    emergencyContactName: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginBottom: verticalScale(3),
    },
    emergencyContactMeta: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    emergencyCallButton: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(18),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: '#F0FDF4',
        borderWidth: 1,
        borderColor: '#BBF7D0',
    },
    healthAddButton: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        borderTopWidth: 1,
        borderTopColor: colors.border,
        alignItems: 'flex-start',
    },
    healthAddButtonText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    healthSectionHeader: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        justifyContent: 'space-between',
        marginTop: verticalScale(4),
    },
    healthSectionAction: {
        marginRight: scale(20),
        marginBottom: verticalScale(10),
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },
    medicationRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    medAvatar: {
        width: moderateScale(40),
        height: moderateScale(40),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
    },
    medBadge: {
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(4),
        borderRadius: moderateScale(8),
    },
    medBadgeText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
    },
    medicationTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginBottom: verticalScale(3),
    },
    medicationMeta: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(1),
    },
    medicineListRow: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(18),
        paddingVertical: verticalScale(10),
        minHeight: verticalScale(48),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    medicineListRowLast: {
        borderBottomWidth: 0,
    },
    medicineListIcon: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(9),
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(10),
    },
    medicineListBody: {
        flex: 1,
        justifyContent: 'center',
        minHeight: 0,
        paddingVertical: verticalScale(2),
    },
    medicineListTitleCompact: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13.5),
        color: colors.text,
    },
    sheetActions: {
        paddingHorizontal: scale(20),
        gap: verticalScale(10),
    },
    actionDangerBtn: {
        backgroundColor: colors.dangerBg,
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(14),
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#FECACA',
    },
    actionDangerText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.danger,
    },
    actionManageBtn: {
        backgroundColor: colors.card,
        borderRadius: moderateScale(14),
        paddingVertical: verticalScale(14),
        alignItems: 'center',
        borderWidth: 1,
        borderColor: colors.border,
    },
    actionManageText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text2,
    },

    // ── Bottom Sheet Profile Sync ──
    sheetKeyboard: {
        justifyContent: 'flex-end',
    },
    sheetSuffix: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.primary,
    },

    // ── Add Contact Modal ──
    addContactHeader: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
    },
    addContactHeaderTop: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginTop: verticalScale(8),
    },
    addContactTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
    },
    addContactSub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    addContactClose: {
        width: moderateScale(32),
        height: moderateScale(32),
        borderRadius: moderateScale(16),
        backgroundColor: colors.primaryBg,
        borderWidth: 1,
        borderColor: colors.primaryLight,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addContactBody: {
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(20),
        maxHeight: verticalScale(450),
    },
    addContactAvatarWrap: {
        alignItems: 'center',
        marginBottom: verticalScale(14),
    },
    addContactAvatar: {
        width: moderateScale(60),
        height: moderateScale(60),
        borderRadius: moderateScale(18),
        backgroundColor: colors.primaryBg,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addContactAvatarText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(24),
        color: colors.primary,
    },
    addContactLabel: {
        ...formSystem.fieldLabel,
        marginBottom: verticalScale(8),
        marginTop: verticalScale(16),
    },
    addContactInputBox: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1.5,
        borderColor: colors.border,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(14),
        height: moderateScale(48),
        backgroundColor: colors.card,
    },
    addContactInput: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.text,
        height: '100%',
        padding: 0,
    },
    addContactPrefix: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.primary,
    },
    addContactDivider: {
        width: 1,
        height: '50%',
        backgroundColor: colors.border,
        marginHorizontal: scale(12),
    },
    addContactRelations: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
    },
    addContactRelChip: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.bg,
    },
    addContactRelChipActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    addContactRelText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text2,
    },
    addContactRelTextActive: {
        color: colors.text,
    },
    addContactFooter: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(14),
        paddingBottom: verticalScale(30),
    },
    addContactSaveBtn: {
        height: moderateScale(50),
        borderRadius: moderateScale(14),
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
    },
    addContactSaveText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.card,
    },

    // ── Health Info Modal ──
    hiModalSheet: {
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(24),
        borderTopRightRadius: moderateScale(24),
        maxHeight: '90%',
        paddingTop: verticalScale(10),
    },
    hiModalHeader: {
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(14),
        borderBottomWidth: 1,
        borderBottomColor: colors.border,
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    hiModalTitle: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(18),
        color: colors.text,
    },
    hiModalSub: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(2),
    },
    hiModalBody: {
        paddingHorizontal: scale(20),
        paddingVertical: verticalScale(20),
        maxHeight: verticalScale(450),
    },
    hiModalInputRow: {
        flexDirection: 'row',
        gap: scale(12),
        marginBottom: verticalScale(16),
    },
    hiModalInput: {
        flex: 1,
        height: moderateScale(48),
        borderWidth: 1.5,
        borderColor: colors.primary,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(16),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.text,
        backgroundColor: colors.card,
    },
    hiModalAddBtn: {
        backgroundColor: colors.primary,
        borderRadius: moderateScale(14),
        paddingHorizontal: scale(20),
        justifyContent: 'center',
        alignItems: 'center',
        height: moderateScale(48),
    },
    hiModalAddBtnText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.card,
    },
    hiModalSelectedWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(8),
        marginBottom: verticalScale(24),
    },
    hiModalEmptyText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text3,
        fontStyle: 'italic',
    },
    hiModalSelectedChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primaryBg,
        paddingHorizontal: scale(10),
        paddingVertical: verticalScale(6),
        borderRadius: moderateScale(20),
        gap: scale(6),
    },
    hiModalSelectedChipText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.primary,
    },
    hiModalSuggestLabel: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginBottom: verticalScale(12),
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    hiModalSuggestionsWrap: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: scale(10),
    },
    hiModalSugChip: {
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(8),
        borderRadius: moderateScale(20),
        borderWidth: 1,
        borderColor: colors.border,
        backgroundColor: colors.card,
    },
    hiModalSugChipActive: {
        borderColor: colors.text2,
        backgroundColor: colors.card,
    },
    hiModalSugChipText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text2,
    },
    hiModalSugChipTextActive: {
        color: colors.text,
    },
    sheetSelectOption: {
        ...inputSystem.selectOption,
        minHeight: verticalScale(45),
        borderRadius: moderateScale(11),
        paddingHorizontal: scale(13),
        marginBottom: verticalScale(8),
    },
    sheetSelectActive: {
        borderColor: colors.primary,
        backgroundColor: colors.primaryBg,
    },
    sheetSelectText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text,
    },
    sheetSelectTextActive: {
        color: colors.primary,
    },
    sheetStepperContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.card,
        borderRadius: moderateScale(11),
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingLeft: scale(13),
        paddingRight: scale(8),
        minHeight: verticalScale(45),
    },
    sheetStepperInput: {
        flex: 1,
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text,
        lineHeight: scaleFont(16),
        paddingVertical: 0,
        textAlignVertical: 'center',
    },
    sheetStepperControls: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(6),
        marginRight: scale(6),
    },
    sheetStepBtn: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(11),
        backgroundColor: colors.bg,
        borderWidth: 1.2,
        borderColor: colors.border,
        alignItems: 'center',
        justifyContent: 'center',
    },
    sheetStepperUnit: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12.5),
        color: colors.text3,
        marginRight: scale(4),
    },

    // ── Records ──
    recordCard: {
        marginHorizontal: scale(20),
        marginBottom: verticalScale(12),
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        overflow: 'hidden',
        borderWidth: 1.5,
        borderColor: colors.border,
        ...shadows.card,
    },
    recordBodyCompact: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        gap: scale(12),
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
    },
    recordCardTop: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        padding: scale(14),
        gap: scale(12),
    },
    recordIconCard: {
        width: moderateScale(38),
        height: moderateScale(38),
        borderRadius: moderateScale(12),
        alignItems: 'center',
        justifyContent: 'center',
        marginTop: verticalScale(2),
    },
    recordContent: {
        flex: 1,
        gap: verticalScale(5),
    },
    recordMetaLine: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    recordDiagnosis: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(12.5),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },
    recordDiagRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(4),
        gap: scale(4),
    },
    recordDiagDot: {
        width: moderateScale(6),
        height: moderateScale(6),
        borderRadius: moderateScale(3),
        backgroundColor: colors.text3,
    },
    recordDiagText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
        flex: 1,
    },
    recordChipRow: {
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: verticalScale(2),
    },
    recordTag: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(10),
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(2),
        borderRadius: moderateScale(6),
        overflow: 'hidden',
    },
    recordCardFooter: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
        borderTopWidth: 1,
        borderTopColor: colors.border,
    },
    recordMetaRight: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(3),
    },
    recordMetaText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(10),
        color: colors.text3,
    },
    recordMoreBtn: {
        width: moderateScale(28),
        height: moderateScale(28),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
    },
    ctxMenu: {
        position: 'absolute',
        right: 0,
        top: verticalScale(30),
        width: scale(145),
        backgroundColor: colors.card,
        borderRadius: moderateScale(12),
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        zIndex: 50,
        elevation: 10,
        shadowColor: '#000',
        shadowOpacity: 0.12,
        shadowRadius: 16,
        shadowOffset: { width: 0, height: verticalScale(4) },
    },
    ctxItem: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    ctxDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    ctxItemDel: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(11),
    },
    ctxItemDelText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(13),
        color: colors.danger,
    },
    recordHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
    },
    recordHeaderLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(10),
    },
    recordIconWrap: {
        width: moderateScale(30),
        height: moderateScale(30),
        borderRadius: moderateScale(8),
        backgroundColor: 'rgba(255, 255, 255, 0.25)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    recordCategory: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.card,
    },
    recordDate: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(12),
        color: colors.card,
    },
    recordBody: {
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
    },
    recordTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
        lineHeight: verticalScale(20),
    },
    recordLine: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        marginBottom: verticalScale(6),
    },
    recordLineText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text2,
    },
    recordLineBoldText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
    },
    recordAddBtn: {
        marginHorizontal: scale(20),
        marginBottom: verticalScale(24),
        borderWidth: 1,
        borderColor: colors.border,
        borderRadius: moderateScale(16),
        backgroundColor: colors.card,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(14),
        gap: scale(6),
    },
    recordAddBtnText: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(14),
        color: colors.text2,
    },

    // ── Vaccine ──
    vaccineCard: {
        marginHorizontal: scale(20),
        marginBottom: verticalScale(16),
        backgroundColor: colors.card,
        borderRadius: moderateScale(20),
        borderWidth: 1.5,
        borderColor: colors.border,
        overflow: 'hidden',
        ...shadows.card,
    },
    vaccineCardTop: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(16),
        gap: scale(16),
    },
    vaccineProgWrap: {
        width: 56,
        height: 56,
        alignItems: 'center',
        justifyContent: 'center',
    },
    vaccineProgText: {
        fontFamily: typography.font.black,
        fontSize: scaleFont(13),
        color: colors.warning,
    },
    vaccineTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(14),
        color: colors.text,
        marginBottom: verticalScale(4),
    },
    vaccineSub: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11.5),
        color: colors.text3,
    },
    vaccineDivider: {
        height: 1,
        backgroundColor: colors.border,
    },
    vaccineCardBottom: {
        flexDirection: 'row',
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(11),
        backgroundColor: colors.bgHealth,
        gap: scale(8),
    },
    vaccineInfoText: {
        flex: 1,
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
        lineHeight: verticalScale(16),
    },

    // ── Metrics ──
    metricCard: {
        marginHorizontal: scale(20),
        marginBottom: verticalScale(12),
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        borderWidth: 1.5,
        borderColor: colors.border,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(12),
        ...shadows.card,
    },
    metricCardHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: verticalScale(10),
    },
    metricIconWrap: {
        width: 32,
        height: 32,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: scale(10),
    },
    metricTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
        color: colors.text,
        marginRight: scale(10),
    },
    metricStatus: {
        paddingHorizontal: scale(8),
        paddingVertical: verticalScale(3),
        borderRadius: moderateScale(999),
    },
    metricStatusText: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(9.5),
    },
    metricDetailLink: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(11.5),
        color: colors.primary,
        marginRight: scale(2),
    },
    metricChartWrap: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-end',
        height: verticalScale(46),
        marginBottom: verticalScale(10),
        paddingHorizontal: scale(12),
    },
    metricChartCol: {
        alignItems: 'center',
        justifyContent: 'flex-end',
        flex: 1,
        height: '100%',
        marginHorizontal: scale(4),
    },
    metricBarFill: {
        width: '100%',
        maxWidth: scale(36),
        borderRadius: moderateScale(4),
        marginBottom: verticalScale(4),
    },
    metricTextWrap: {
        flex: 1,
        justifyContent: 'flex-end',
        marginBottom: verticalScale(6),
    },
    metricTextVal: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(16),
    },
    metricChartLabel: {
        fontFamily: typography.font.semiBold,
        fontSize: scaleFont(10),
        color: colors.text3,
    },
    metricFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    metricUpdateText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    metricLatestVal: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(13),
    },
});
