import { StyleSheet } from 'react-native';
import {
    moderateScale,
    scale,
    scaleFont,
    verticalScale,
} from '@/src/styles/responsive';
import { colors, shadows, typography } from '@/src/styles/tokens';

export const chatbotStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.bg,
    },
    header: {
        paddingHorizontal: scale(20),
        paddingTop: verticalScale(8),
        paddingBottom: verticalScale(14),
    },
    title: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(17),
        color: colors.text,
        lineHeight: verticalScale(22),
    },
    subtitle: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(13),
        color: colors.text2,
        lineHeight: verticalScale(20),
    },
    chatZone: {
        flex: 1,
        paddingHorizontal: scale(20),
        paddingBottom: verticalScale(12),
    },
    messagesList: {
        paddingTop: verticalScale(10),
        paddingBottom: verticalScale(20),
    },
    emptyStateCard: {
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(14),
        marginBottom: verticalScale(12),
        ...shadows.card,
    },
    emptyStateTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(15),
        color: colors.text,
        marginBottom: verticalScale(6),
    },
    emptyStateText: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12.5),
        color: colors.text2,
        lineHeight: verticalScale(18),
    },
    messageBubble: {
        maxWidth: '85%',
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(14),
        borderRadius: moderateScale(18),
        marginBottom: verticalScale(12),
        ...shadows.card,
    },
    messageUser: {
        alignSelf: 'flex-end',
        backgroundColor: colors.secondaryBg,
        borderTopRightRadius: moderateScale(4),
    },
    messageAi: {
        alignSelf: 'flex-start',
        backgroundColor: colors.card,
        borderTopLeftRadius: moderateScale(4),
    },
    messageText: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.text,
        lineHeight: verticalScale(20),
    },
    messageMeta: {
        marginTop: verticalScale(6),
        fontFamily: typography.font.regular,
        fontSize: scaleFont(11),
        color: colors.text3,
    },
    loader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: verticalScale(10),
    },
    loaderText: {
        marginLeft: scale(10),
        fontFamily: typography.font.medium,
        fontSize: scaleFont(13),
        color: colors.text3,
    },
    inputArea: {
        borderTopWidth: 1,
        borderTopColor: colors.border,
        paddingHorizontal: scale(16),
        paddingVertical: verticalScale(10),
        backgroundColor: colors.card,
    },
    inputRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(12),
    },
    inputWrap: {
        flex: 1,
        backgroundColor: colors.bg,
        borderRadius: moderateScale(16),
        borderWidth: 1,
        borderColor: colors.border,
        paddingHorizontal: scale(14),
        paddingVertical: verticalScale(10),
    },
    textInput: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.text,
        minHeight: verticalScale(36),
        maxHeight: verticalScale(96),
    },
    sendButton: {
        width: moderateScale(42),
        height: moderateScale(42),
        borderRadius: moderateScale(14),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        shadowColor: '#2563EB',
        shadowOpacity: 0.18,
        shadowRadius: 10,
        shadowOffset: { width: 0, height: 3 },
        elevation: 4,
    },
    sendButtonDisabled: {
        backgroundColor: colors.border,
        shadowOpacity: 0,
    },
    headerRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
    },
    headerLeft: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: scale(8),
        flex: 1,
    },
    headerActions: {
        flexDirection: 'row',
        gap: scale(12),
    },
    iconButton: {
        width: moderateScale(36),
        height: moderateScale(36),
        borderRadius: moderateScale(8),
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.card,
        borderWidth: 1,
        borderColor: colors.border,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.5)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContent: {
        width: '90%',
        maxHeight: '70%',
        backgroundColor: colors.card,
        borderRadius: moderateScale(16),
        padding: scale(20),
        ...shadows.card,
    },
    modalTitle: {
        fontFamily: typography.font.bold,
        fontSize: scaleFont(18),
        color: colors.text,
        marginBottom: verticalScale(16),
        textAlign: 'center',
    },
    sessionItem: {
        paddingVertical: verticalScale(12),
        paddingHorizontal: scale(16),
        borderRadius: moderateScale(12),
        backgroundColor: colors.bg,
        marginBottom: verticalScale(8),
        borderWidth: 1,
        borderColor: colors.border,
    },
    sessionTitle: {
        fontFamily: typography.font.medium,
        fontSize: scaleFont(14),
        color: colors.text,
    },
    sessionMeta: {
        fontFamily: typography.font.regular,
        fontSize: scaleFont(12),
        color: colors.text3,
        marginTop: verticalScale(4),
    },
    noSessions: {
        textAlign: 'center',
        fontFamily: typography.font.regular,
        fontSize: scaleFont(14),
        color: colors.text3,
        paddingVertical: verticalScale(20),
    },
});
